# Copy Database

## Connect to Databases

In [1]:
import mysql.connector
from mysql.connector import errorcode

config_aws = {
  'user': 'manodhayan',
  'password': 'Ambience^DB',
  'host': 'hospsqldatabase.czbthbfxmuzs.ap-south-1.rds.amazonaws.com',
  'database': 'hospsqldatabase',
  'raise_on_warnings': True
}

config_gear = {
  'user': 'ambiencesqldb',
  'password': 'Ambience^DB',
  'host': 'den1.mysql2.gear.host',
  'database': 'ambiencesqldb',
  'raise_on_warnings': True
}


'''Connect to the aws_Database'''
try:
#     cnx = mysql.connector.connect(user='ambiencesqldb', password='Ambience^DB',
#                               host="den1.mysql2.gear.host",
#                               database='ambiencesqldb')
    aws_cnx=mysql.connector.connect(**config_aws)
    print("Connected to AWS!")
except mysql.connector.Error as err:
    if err.errno == errorcode.ER_ACCESS_DENIED_ERROR:
        print("Something is wrong with your user name or password")
    elif err.errno == errorcode.ER_BAD_DB_ERROR:
        print("Database does not exist")
    else:
        print(err)
        
aws_cursor = aws_cnx.cursor()

'''Connect to the gear_Database'''
try:
#     cnx = mysql.connector.connect(user='ambiencesqldb', password='Ambience^DB',
#                               host="den1.mysql2.gear.host",
#                               database='ambiencesqldb')
    gear_cnx=mysql.connector.connect(**config_gear)
    print("Connected to GearHost!")
except mysql.connector.Error as err:
    if err.errno == errorcode.ER_ACCESS_DENIED_ERROR:
        print("Something is wrong with your user name or password")
    elif err.errno == errorcode.ER_BAD_DB_ERROR:
        print("Database does not exist")
    else:
        print(err)
        
gear_cursor = gear_cnx.cursor()

Connected to AWS!
Connected to GearHost!

## Get data From Gearhost Database and Copy it to AWS Database

In [12]:
gear_cursor = gear_cnx.cursor()
gear_cursor.execute(("SELECT * FROM hospital_D"))
count=0
for data in gear_cursor:
    count+=1
    query=(("INSERT INTO hospital_A "
               "(Timestamp, Room, Temperature, Humidity) "
               "VALUES (%s, %s, %s, %s)"))
    Timestamp=data[0];room=data[1];temperature=data[2];humidity=data[3]
    query_data=(Timestamp,room,temperature,humidity) 
    print(query,query_data)  
    aws_cursor.execute(query, query_data)
    aws_cnx.commit()
    print("Row {} is Updated!!!".format(count))
    
gear_cnx.commit()

INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 16, 16, 17), 'Surgical Ward', 23, 59)
Row 1 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 16, 18, 10), 'ICU', 25, 42)
Row 2 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 16, 18, 11), 'ICU', 25, 42)
Row 3 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 16, 18, 25), 'Maternity Ward', 22, 49)
Row 4 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 16, 18, 27), 'Maternity Ward', 22, 49)
Row 5 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 16, 18, 27), 'Maternity Ward', 22, 49)
Row 6 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 16, 19, 22), 'Surgical Ward', 22, 49)
Row 7 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 16, 19, 22), 'Surgical Ward', 22, 49)
Row 8 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 16, 19, 22), 'Surgical Ward', 22, 49)
Row 9 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 16, 19, 22), 'Surgical Ward', 22, 49)
Row 10 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 16, 19, 22), 'Surgical Ward', 22, 49)
Row 11 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 16, 19, 22), 'Surgical Ward', 22, 49)
Row 12 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 16, 19, 22), 'Surgical Ward', 22, 49)
Row 13 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 16, 19, 22), 'Surgical Ward', 22, 49)
Row 14 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 16, 19, 22), 'Surgical Ward', 22, 49)
Row 15 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 16, 19, 22), 'Surgical Ward', 22, 49)
Row 16 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 16, 19, 22), 'Surgical Ward', 22, 49)
Row 17 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 16, 19, 29), 'ICU', 25, 42)
Row 18 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 16, 19, 45), 'Maternity Ward', 22, 49)
Row 19 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 16, 19, 45), 'Maternity Ward', 22, 49)
Row 20 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 16, 19, 45), 'Maternity Ward', 22, 49)
Row 21 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 16, 19, 45), 'Maternity Ward', 22, 49)
Row 22 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 16, 19, 45), 'Maternity Ward', 22, 49)
Row 23 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 16, 19, 45), 'Maternity Ward', 22, 49)
Row 24 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 16, 20, 42), 'Surgical Ward', 22, 49)
Row 25 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 16, 20, 42), 'Surgical Ward', 22, 49)
Row 26 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 16, 20, 42), 'Surgical Ward', 22, 49)
Row 27 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 16, 20, 42), 'Surgical Ward', 22, 49)
Row 28 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 16, 20, 42), 'Surgical Ward', 22, 49)
Row 29 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 16, 20, 47), 'Surgical Ward', 22, 49)
Row 30 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 16, 23, 24), 'Surgical Ward', 22, 49)
Row 31 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 16, 27, 26), 'ICU', 25, 42)
Row 32 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 16, 41, 17), 'ICU', 25, 42)
Row 33 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 16, 41, 53), 'Surgical Ward', 22, 50)
Row 34 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 16, 41, 56), 'Maternity Ward', 22, 50)
Row 35 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 16, 42, 37), 'ICU', 25, 42)
Row 36 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 16, 43, 12), 'Surgical Ward', 22, 50)
Row 37 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 16, 43, 17), 'Maternity Ward', 22, 50)
Row 38 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 16, 43, 55), 'ICU', 25, 42)
Row 39 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 16, 44, 32), 'Surgical Ward', 22, 50)
Row 40 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 16, 44, 37), 'Maternity Ward', 22, 50)
Row 41 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 16, 45, 15), 'ICU', 25, 42)
Row 42 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 16, 45, 53), 'Surgical Ward', 22, 50)
Row 43 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 16, 45, 57), 'Maternity Ward', 22, 50)
Row 44 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 16, 46, 17), 'Surgical Ward', 23, 59)
Row 45 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 16, 46, 33), 'ICU', 25, 42)
Row 46 is Updated!!!

INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 16, 47, 7), 'Surgical Ward', 22, 50)
Row 47 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 16, 47, 17), 'Maternity Ward', 22, 50)
Row 48 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 16, 47, 52), 'ICU', 25, 42)
Row 49 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 16, 48, 14), 'Surgical Ward', 22, 50)
Row 50 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 16, 48, 37), 'Maternity Ward', 22, 50)
Row 51 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 16, 49, 11), 'ICU', 25, 42)
Row 52 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 16, 49, 37), 'Surgical Ward', 22, 50)
Row 53 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 16, 49, 50), 'Maternity Ward', 22, 50)
Row 54 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 16, 50, 32), 'ICU', 25, 42)
Row 55 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 16, 50, 57), 'Surgical Ward', 22, 50)
Row 56 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 16, 50, 59), 'Maternity Ward', 22, 50)
Row 57 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 16, 51, 49), 'ICU', 25, 42)
Row 58 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 16, 52, 17), 'Surgical Ward', 22, 50)
Row 59 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 16, 52, 19), 'Maternity Ward', 22, 50)
Row 60 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 16, 53, 8), 'ICU', 25, 42)
Row 61 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 16, 53, 37), 'Surgical Ward', 22, 50)
Row 62 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 16, 53, 41), 'Maternity Ward', 22, 50)
Row 63 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 16, 53, 47), 'Surgical Ward', 23, 59)
Row 64 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 16, 56, 47), 'ICU', 25, 42)
Row 65 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 16, 57, 38), 'Surgical Ward', 22, 50)
Row 66 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 16, 57, 41), 'Maternity Ward', 22, 50)
Row 67 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 16, 58, 10), 'ICU', 25, 42)
Row 68 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 16, 58, 59), 'Surgical Ward', 22, 50)
Row 69 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 16, 59, 2), 'Maternity Ward', 22, 50)
Row 70 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 16, 59, 25), 'ICU', 25, 42)
Row 71 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 17, 0, 19), 'Surgical Ward', 22, 50)
Row 72 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 17, 0, 22), 'Maternity Ward', 22, 50)
Row 73 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 17, 0, 44), 'ICU', 25, 42)
Row 74 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 17, 1, 32), 'Surgical Ward', 22, 50)
Row 75 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 17, 1, 43), 'Maternity Ward', 22, 50)
Row 76 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 17, 2, 3), 'ICU', 25, 42)
Row 77 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 17, 2, 41), 'Surgical Ward', 22, 50)
Row 78 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 17, 3, 2), 'Maternity Ward', 23, 49)
Row 79 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 17, 3, 23), 'ICU', 25, 42)
Row 80 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 17, 4, 2), 'Surgical Ward', 22, 49)
Row 81 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 17, 4, 18), 'Maternity Ward', 22, 49)
Row 82 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 17, 4, 42), 'ICU', 25, 42)
Row 83 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 17, 5, 24), 'Surgical Ward', 22, 49)
Row 84 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 17, 5, 29), 'Maternity Ward', 22, 49)
Row 85 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 17, 6, 2), 'ICU', 25, 42)
Row 86 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 17, 6, 42), 'Surgical Ward', 22, 49)
Row 87 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 17, 6, 45), 'Maternity Ward', 22, 49)
Row 88 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 17, 7, 22), 'ICU', 25, 42)
Row 89 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 17, 8, 12), 'Surgical Ward', 22, 49)
Row 90 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 17, 8, 17), 'Maternity Ward', 22, 49)
Row 91 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 17, 8, 31), 'ICU', 25, 42)
Row 92 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 17, 9, 23), 'Surgical Ward', 22, 49)

Row 93 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 17, 9, 27), 'Maternity Ward', 22, 49)
Row 94 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 17, 9, 39), 'ICU', 25, 42)
Row 95 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 17, 10, 43), 'Surgical Ward', 22, 49)
Row 96 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 17, 10, 47), 'Maternity Ward', 22, 48)
Row 97 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 17, 10, 58), 'ICU', 25, 41)
Row 98 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 17, 12, 14), 'Surgical Ward', 22, 49)
Row 99 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 17, 12, 17), 'Maternity Ward', 22, 51)
Row 100 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 17, 12, 18), 'ICU', 25, 41)
Row 101 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 17, 13, 27), 'Surgical Ward', 22, 49)
Row 102 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 17, 13, 30), 'Maternity Ward', 22, 48)
Row 103 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 17, 13, 37), 'ICU', 25, 41)
Row 104 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 17, 15, 5), 'Surgical Ward', 22, 48)
Row 105 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 17, 15, 10), 'Maternity Ward', 22, 48)
Row 106 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 17, 15, 13), 'ICU', 25, 41)
Row 107 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 17, 16, 16), 'Surgical Ward', 22, 48)
Row 108 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 17, 17, 22), 'Maternity Ward', 22, 48)
Row 109 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 17, 17, 27), 'ICU', 25, 41)
Row 110 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 17, 17, 33), 'ICU', 25, 41)
Row 111 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 17, 18, 27), 'Surgical Ward', 22, 48)
Row 112 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 17, 18, 42), 'Maternity Ward', 22, 48)
Row 113 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 17, 18, 53), 'ICU', 25, 41)
Row 114 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 17, 19, 48), 'Surgical Ward', 22, 48)
Row 115 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 17, 19, 50), 'Maternity Ward', 22, 47)
Row 116 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 17, 20, 12), 'ICU', 25, 41)
Row 117 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 17, 21, 9), 'Surgical Ward', 22, 47)
Row 118 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 17, 21, 11), 'Maternity Ward', 22, 47)
Row 119 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 17, 21, 31), 'ICU', 25, 41)
Row 120 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 17, 22, 29), 'Surgical Ward', 22, 48)
Row 121 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 17, 22, 31), 'Maternity Ward', 22, 47)
Row 122 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 17, 22, 43), 'ICU', 25, 41)
Row 123 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 17, 23, 49), 'Surgical Ward', 22, 47)
Row 124 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 17, 23, 50), 'ICU', 25, 41)
Row 125 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 17, 23, 52), 'Maternity Ward', 22, 47)
Row 126 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 17, 25, 9), 'ICU', 25, 41)
Row 127 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 17, 25, 10), 'Surgical Ward', 22, 47)
Row 128 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 17, 25, 12), 'Maternity Ward', 22, 47)
Row 129 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 17, 26, 29), 'ICU', 25, 41)
Row 130 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 17, 26, 30), 'Surgical Ward', 22, 47)
Row 131 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 17, 26, 32), 'Maternity Ward', 21, 47)
Row 132 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 17, 27, 47), 'ICU', 25, 41)
Row 133 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 17, 27, 50), 'Surgical Ward', 22, 47)
Row 134 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 17, 27, 53), 'Maternity Ward', 22, 47)
Row 135 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 17, 29, 11), 'ICU', 25, 41)
Row 136 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 17, 29, 12), 'Surgical Ward', 22, 47)
Row 137 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 17, 29, 13), 'Maternity Ward', 22, 47)
Row 138 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 17, 30, 24), 'Surgical Ward', 22, 47)
Row 139 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 17, 30, 27), 'ICU', 25, 41)
Row 140 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 17, 30, 33), 'Maternity Ward', 22, 47)

Row 141 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 17, 31, 33), 'Surgical Ward', 21, 47)
Row 142 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 17, 31, 45), 'ICU', 25, 41)
Row 143 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 17, 31, 54), 'Maternity Ward', 22, 47)
Row 144 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 17, 32, 54), 'Surgical Ward', 22, 47)
Row 145 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 17, 33, 4), 'ICU', 25, 41)
Row 146 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 17, 33, 7), 'Maternity Ward', 22, 48)
Row 147 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 17, 34, 14), 'Surgical Ward', 22, 47)
Row 148 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 17, 34, 18), 'Maternity Ward', 22, 48)
Row 149 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 17, 34, 23), 'ICU', 25, 41)
Row 150 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 17, 35, 34), 'Surgical Ward', 21, 47)
Row 151 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 17, 35, 42), 'ICU', 25, 41)
Row 152 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 17, 35, 50), 'Maternity Ward', 22, 48)
Row 153 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 17, 36, 4), 'Emergency Ward', 26, 48)
Row 154 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 17, 36, 54), 'ICU', 25, 41)
Row 155 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 17, 36, 55), 'Surgical Ward', 21, 47)
Row 156 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 17, 36, 59), 'Maternity Ward', 22, 47)
Row 157 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 17, 37, 13), 'Emergency Ward', 21, 48)
Row 158 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 17, 38, 2), 'ICU', 25, 41)
Row 159 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 17, 38, 15), 'Surgical Ward', 21, 47)
Row 160 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 17, 38, 19), 'Maternity Ward', 22, 47)
Row 161 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 17, 38, 34), 'Emergency Ward', 26, 49)
Row 162 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 17, 39, 21), 'ICU', 25, 41)
Row 163 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 17, 39, 37), 'Surgical Ward', 22, 47)
Row 164 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 17, 39, 40), 'Maternity Ward', 22, 47)
Row 165 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 17, 39, 57), 'Emergency Ward', 23, 47)
Row 166 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 17, 40, 40), 'ICU', 25, 41)
Row 167 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 17, 40, 57), 'Surgical Ward', 21, 47)
Row 168 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 17, 41), 'Maternity Ward', 22, 47)
Row 169 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 17, 41, 17), 'Emergency Ward', 23, 47)
Row 170 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 17, 41, 59), 'ICU', 25, 41)
Row 171 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 17, 42, 17), 'Surgical Ward', 21, 47)
Row 172 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 17, 42, 22), 'Maternity Ward', 22, 46)
Row 173 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 17, 42, 38), 'Emergency Ward', 23, 47)
Row 174 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 17, 43, 18), 'ICU', 25, 41)
Row 175 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 17, 43, 37), 'Surgical Ward', 21, 47)
Row 176 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 17, 43, 41), 'Maternity Ward', 22, 47)
Row 177 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 17, 43, 59), 'Emergency Ward', 23, 47)
Row 178 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 17, 44, 37), 'ICU', 25, 41)
Row 179 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 17, 44, 51), 'Surgical Ward', 21, 47)
Row 180 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 17, 45, 1), 'Maternity Ward', 22, 46)
Row 181 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 17, 45, 20), 'Emergency Ward', 23, 47)
Row 182 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 17, 45, 57), 'ICU', 25, 41)
Row 183 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 17, 45, 59), 'Surgical Ward', 21, 47)
Row 184 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 17, 46, 21), 'Maternity Ward', 21, 46)
Row 185 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 17, 46, 41), 'Emergency Ward', 26, 48)
Row 186 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 17, 47, 15), 'ICU', 25, 40)
Row 187 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 17, 47, 20), 'Surgical Ward', 21, 46)
Row 188 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 17, 47, 42), 'Maternity Ward', 21, 47)

Row 189 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 17, 48, 3), 'Emergency Ward', 26, 48)
Row 190 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 17, 48, 40), 'ICU', 25, 40)
Row 191 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 17, 48, 45), 'Surgical Ward', 21, 47)
Row 192 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 17, 49, 3), 'Maternity Ward', 22, 46)
Row 193 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 17, 49, 24), 'Emergency Ward', 26, 48)
Row 194 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 17, 49, 57), 'ICU', 25, 40)
Row 195 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 17, 50, 2), 'Surgical Ward', 21, 46)
Row 196 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 17, 50, 21), 'Maternity Ward', 21, 46)
Row 197 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 17, 50, 39), 'Emergency Ward', 23, 47)
Row 198 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 17, 51, 17), 'ICU', 25, 40)
Row 199 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 17, 51, 28), 'Surgical Ward', 21, 46)
Row 200 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 17, 51, 30), 'Maternity Ward', 22, 46)
Row 201 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 17, 51, 47), 'Emergency Ward', 23, 47)
Row 202 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 17, 52, 13), 'ICU', 25, 40)
Row 203 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 17, 52, 41), 'Surgical Ward', 21, 47)
Row 204 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 17, 52, 45), 'Maternity Ward', 21, 47)
Row 205 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 17, 53, 9), 'Emergency Ward', 26, 48)
Row 206 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 17, 53, 32), 'ICU', 25, 40)
Row 207 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 17, 54, 2), 'Surgical Ward', 21, 47)
Row 208 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 17, 54, 7), 'Maternity Ward', 22, 46)
Row 209 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 17, 54, 32), 'Emergency Ward', 23, 47)
Row 210 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 17, 54, 53), 'ICU', 25, 40)
Row 211 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 17, 55, 25), 'Surgical Ward', 21, 46)
Row 212 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 17, 55, 30), 'Maternity Ward', 22, 47)
Row 213 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 17, 55, 52), 'Emergency Ward', 26, 48)
Row 214 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 17, 56, 13), 'ICU', 25, 40)
Row 215 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 17, 56, 47), 'Surgical Ward', 21, 47)
Row 216 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 17, 56, 50), 'Maternity Ward', 22, 47)
Row 217 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 17, 57, 13), 'Emergency Ward', 26, 48)
Row 218 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 17, 57, 29), 'ICU', 25, 40)
Row 219 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 17, 58, 3), 'Surgical Ward', 21, 47)
Row 220 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 17, 58, 7), 'Maternity Ward', 21, 47)
Row 221 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 17, 58, 33), 'Emergency Ward', 26, 48)
Row 222 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 17, 58, 49), 'ICU', 25, 40)
Row 223 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 18, 1, 18), 'Emergency Ward', 23, 46)
Row 224 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 18, 1, 27), 'ICU', 25, 40)
Row 225 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 18, 1, 48), 'Surgical Ward', 21, 47)
Row 226 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 18, 2, 8), 'Maternity Ward', 22, 47)
Row 227 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 18, 2, 38), 'Emergency Ward', 23, 47)
Row 228 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 18, 2, 47), 'ICU', 25, 41)
Row 229 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 18, 3, 7), 'Surgical Ward', 22, 47)
Row 230 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 18, 3, 28), 'Maternity Ward', 22, 47)
Row 231 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 18, 3, 58), 'Emergency Ward', 26, 48)
Row 232 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 18, 4, 4), 'ICU', 26, 41)
Row 233 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 18, 4, 27), 'Surgical Ward', 22, 47)
Row 234 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 18, 4, 42), 'Maternity Ward', 22, 47)
Row 235 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 18, 5, 12), 'Emergency Ward', 23, 47)

Row 236 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 18, 5, 17), 'ICU', 26, 41)
Row 237 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 18, 5, 47), 'Surgical Ward', 22, 47)
Row 238 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 18, 5, 50), 'Maternity Ward', 22, 48)
Row 239 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 18, 6, 22), 'Emergency Ward', 26, 48)
Row 240 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 18, 6, 24), 'ICU', 26, 41)
Row 241 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 18, 7, 8), 'Surgical Ward', 22, 47)
Row 242 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 18, 7, 11), 'Maternity Ward', 22, 47)
Row 243 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 18, 7, 43), 'Emergency Ward', 23, 47)
Row 244 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 18, 7, 45), 'ICU', 26, 41)
Row 245 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 18, 8, 28), 'Surgical Ward', 22, 48)
Row 246 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 18, 8, 31), 'Maternity Ward', 22, 47)
Row 247 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 18, 9, 2), 'ICU', 26, 40)
Row 248 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 18, 9, 4), 'Emergency Ward', 26, 48)
Row 249 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 18, 9, 48), 'Surgical Ward', 22, 48)
Row 250 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 18, 9, 51), 'Maternity Ward', 22, 48)
Row 251 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 18, 10, 21), 'ICU', 26, 40)
Row 252 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 18, 10, 25), 'Emergency Ward', 26, 48)
Row 253 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 18, 11, 9), 'Surgical Ward', 22, 48)
Row 254 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 18, 11, 12), 'Maternity Ward', 22, 48)
Row 255 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 18, 11, 42), 'ICU', 26, 40)
Row 256 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 18, 11, 47), 'Emergency Ward', 23, 47)
Row 257 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 18, 12, 30), 'Surgical Ward', 22, 48)
Row 258 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 18, 12, 33), 'Maternity Ward', 22, 48)
Row 259 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 18, 13, 1), 'ICU', 26, 41)
Row 260 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 18, 13, 8), 'Emergency Ward', 26, 48)
Row 261 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 18, 13, 43), 'Surgical Ward', 22, 48)
Row 262 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 18, 13, 52), 'Maternity Ward', 22, 48)
Row 263 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 18, 14, 19), 'ICU', 26, 40)
Row 264 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 18, 14, 29), 'Emergency Ward', 26, 48)
Row 265 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 18, 14, 53), 'Surgical Ward', 22, 48)
Row 266 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 18, 15, 15), 'Maternity Ward', 22, 48)
Row 267 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 18, 15, 38), 'ICU', 26, 41)
Row 268 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 18, 15, 50), 'Emergency Ward', 26, 48)
Row 269 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 18, 16, 12), 'Surgical Ward', 22, 48)
Row 270 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 18, 16, 33), 'Maternity Ward', 22, 48)
Row 271 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 18, 16, 57), 'ICU', 26, 41)
Row 272 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 18, 17, 11), 'Emergency Ward', 23, 47)
Row 273 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 18, 17, 33), 'Surgical Ward', 22, 48)
Row 274 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 18, 17, 55), 'Maternity Ward', 22, 48)
Row 275 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 18, 18, 17), 'ICU', 26, 41)
Row 276 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 18, 18, 32), 'Emergency Ward', 26, 48)
Row 277 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 18, 18, 54), 'Surgical Ward', 22, 48)
Row 278 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 18, 19, 8), 'Maternity Ward', 22, 48)
Row 279 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 18, 19, 28), 'ICU', 26, 41)
Row 280 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 18, 19, 47), 'Emergency Ward', 26, 48)
Row 281 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 18, 20, 13), 'Surgical Ward', 22, 48)

Row 282 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 18, 20, 57), 'Emergency Ward', 26, 49)
Row 283 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 18, 21, 34), 'Surgical Ward', 23, 47)
Row 284 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 18, 21, 41), 'Maternity Ward', 22, 50)
Row 285 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 18, 21, 57), 'ICU', 26, 41)
Row 286 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 18, 22, 17), 'Emergency Ward', 26, 48)
Row 287 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 18, 22, 54), 'Surgical Ward', 22, 48)
Row 288 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 18, 22, 57), 'Maternity Ward', 23, 48)
Row 289 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 18, 23, 14), 'ICU', 26, 41)
Row 290 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 18, 23, 38), 'Emergency Ward', 26, 48)
Row 291 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 18, 24, 17), 'Surgical Ward', 23, 47)
Row 292 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 18, 24, 18), 'Maternity Ward', 23, 49)
Row 293 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 18, 24, 33), 'ICU', 26, 41)
Row 294 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 18, 24, 59), 'Emergency Ward', 26, 48)
Row 295 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 18, 25, 39), 'Maternity Ward', 22, 49)
Row 296 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 18, 25, 52), 'ICU', 27, 40)
Row 297 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 18, 26, 21), 'Emergency Ward', 26, 48)
Row 298 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 18, 26, 57), 'Surgical Ward', 23, 47)
Row 299 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 18, 26, 58), 'Maternity Ward', 23, 48)
Row 300 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 18, 27, 11), 'ICU', 27, 40)
Row 301 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 18, 27, 42), 'Emergency Ward', 26, 48)
Row 302 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 18, 28, 9), 'Surgical Ward', 23, 47)
Row 303 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 18, 28, 18), 'Maternity Ward', 23, 48)
Row 304 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 18, 28, 30), 'ICU', 26, 41)
Row 305 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 18, 29, 3), 'Emergency Ward', 26, 48)
Row 306 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 18, 29, 18), 'Surgical Ward', 23, 48)
Row 307 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 18, 29, 39), 'Maternity Ward', 23, 48)
Row 308 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 18, 29, 49), 'ICU', 27, 40)
Row 309 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 18, 30, 24), 'Emergency Ward', 26, 48)
Row 310 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 18, 30, 38), 'Surgical Ward', 23, 48)
Row 311 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 18, 30, 59), 'Maternity Ward', 23, 48)
Row 312 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 18, 31, 8), 'ICU', 27, 40)
Row 313 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 18, 31, 59), 'Surgical Ward', 23, 48)
Row 314 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 18, 32, 20), 'Maternity Ward', 23, 48)
Row 315 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 18, 32, 27), 'ICU', 27, 40)
Row 316 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 18, 33, 7), 'Emergency Ward', 26, 48)
Row 317 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 18, 33, 19), 'Surgical Ward', 23, 48)
Row 318 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 18, 33, 33), 'Maternity Ward', 22, 49)
Row 319 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 18, 33, 39), 'ICU', 27, 40)
Row 320 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 18, 34, 21), 'Emergency Ward', 26, 48)
Row 321 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 18, 34, 40), 'Surgical Ward', 23, 48)
Row 322 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 18, 34, 42), 'Maternity Ward', 23, 49)
Row 323 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 18, 34, 47), 'ICU', 27, 41)
Row 324 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 18, 35, 30), 'Emergency Ward', 26, 48)
Row 325 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 18, 36, 1), 'Surgical Ward', 23, 48)
Row 326 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 18, 36, 2), 'Maternity Ward', 23, 49)
Row 327 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 18, 36, 7), 'ICU', 27, 40)
Row 328 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 18, 36, 52), 'Emergency Ward', 26, 49)

Row 329 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 18, 37, 21), 'Surgical Ward', 23, 48)
Row 330 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 18, 37, 23), 'Maternity Ward', 23, 49)
Row 331 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 18, 37, 27), 'ICU', 27, 40)
Row 332 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 18, 38, 12), 'Emergency Ward', 26, 49)
Row 333 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 18, 38, 41), 'Surgical Ward', 23, 48)
Row 334 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 18, 38, 43), 'Maternity Ward', 23, 49)
Row 335 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 18, 38, 44), 'ICU', 27, 41)
Row 336 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 18, 39, 34), 'Emergency Ward', 26, 49)
Row 337 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 18, 40, 1), 'Surgical Ward', 23, 48)
Row 338 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 18, 40, 3), 'Maternity Ward', 23, 49)
Row 339 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 18, 41, 13), 'Emergency Ward', 26, 49)
Row 340 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 18, 41, 23), 'Surgical Ward', 23, 48)
Row 341 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 18, 41, 31), 'ICU', 27, 41)
Row 342 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 18, 41, 33), 'Maternity Ward', 23, 49)
Row 343 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 18, 42, 18), 'Emergency Ward', 26, 49)
Row 344 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 18, 42, 37), 'Surgical Ward', 23, 48)
Row 345 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 18, 42, 42), 'ICU', 27, 41)
Row 346 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 18, 42, 44), 'Maternity Ward', 23, 49)
Row 347 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 18, 43, 37), 'Emergency Ward', 26, 49)
Row 348 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 18, 43, 44), 'Surgical Ward', 23, 49)
Row 349 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 18, 44, 1), 'ICU', 27, 41)
Row 350 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 18, 44, 5), 'Maternity Ward', 23, 49)
Row 351 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 18, 44, 58), 'Emergency Ward', 26, 49)
Row 352 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 18, 45, 5), 'Surgical Ward', 23, 49)
Row 353 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 18, 45, 25), 'ICU', 27, 41)
Row 354 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 18, 45, 27), 'Maternity Ward', 23, 49)
Row 355 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 18, 46, 20), 'Emergency Ward', 26, 49)
Row 356 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 18, 46, 25), 'Surgical Ward', 23, 49)
Row 357 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 18, 46, 39), 'ICU', 27, 41)
Row 358 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 18, 46, 47), 'Maternity Ward', 23, 49)
Row 359 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 18, 47, 40), 'Emergency Ward', 26, 50)
Row 360 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 18, 47, 47), 'Surgical Ward', 23, 49)
Row 361 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 18, 47, 51), 'ICU', 27, 41)
Row 362 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 18, 47, 59), 'Maternity Ward', 23, 49)
Row 363 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 18, 48, 55), 'Emergency Ward', 26, 50)
Row 364 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 18, 49, 2), 'ICU', 27, 41)
Row 365 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 18, 49, 8), 'Surgical Ward', 23, 49)
Row 366 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 18, 49, 9), 'Maternity Ward', 23, 50)
Row 367 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 18, 50, 4), 'Emergency Ward', 26, 50)
Row 368 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 18, 50, 18), 'ICU', 27, 41)
Row 369 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 18, 50, 27), 'Surgical Ward', 23, 49)
Row 370 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 18, 50, 28), 'Maternity Ward', 23, 49)
Row 371 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 18, 51, 27), 'Emergency Ward', 26, 50)
Row 372 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 18, 51, 37), 'ICU', 27, 41)
Row 373 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 18, 51, 47), 'Surgical Ward', 23, 49)
Row 374 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 18, 51, 48), 'Maternity Ward', 23, 49)

Row 375 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 18, 52, 47), 'Emergency Ward', 26, 51)
Row 376 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 18, 52, 57), 'ICU', 27, 41)
Row 377 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 18, 53, 7), 'Surgical Ward', 23, 49)
Row 378 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 18, 53, 9), 'Maternity Ward', 23, 50)
Row 379 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 18, 54, 8), 'Emergency Ward', 26, 51)
Row 380 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 18, 54, 15), 'ICU', 27, 41)
Row 381 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 18, 54, 28), 'Surgical Ward', 23, 49)
Row 382 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 18, 54, 29), 'Maternity Ward', 23, 50)
Row 383 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 18, 55, 29), 'Emergency Ward', 26, 51)
Row 384 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 18, 55, 34), 'ICU', 27, 41)
Row 385 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 18, 55, 48), 'Surgical Ward', 23, 49)
Row 386 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 18, 55, 50), 'Maternity Ward', 23, 51)
Row 387 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 18, 56, 50), 'Emergency Ward', 26, 51)
Row 388 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 18, 56, 53), 'ICU', 27, 41)
Row 389 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 18, 57, 2), 'Surgical Ward', 23, 49)
Row 390 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 18, 57, 10), 'Maternity Ward', 23, 50)
Row 391 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 18, 58, 11), 'Surgical Ward', 23, 50)
Row 392 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 18, 58, 12), 'Emergency Ward', 26, 52)
Row 393 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 18, 58, 13), 'ICU', 27, 41)
Row 394 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 18, 58, 30), 'Maternity Ward', 23, 51)
Row 395 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 18, 59, 31), 'Surgical Ward', 23, 50)
Row 396 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 18, 59, 32), 'ICU', 27, 41)
Row 397 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 18, 59, 33), 'Emergency Ward', 26, 52)
Row 398 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 18, 59, 51), 'Maternity Ward', 23, 52)
Row 399 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 19, 0, 51), 'ICU', 27, 41)
Row 400 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 19, 0, 52), 'Surgical Ward', 23, 50)
Row 401 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 19, 0, 53), 'Emergency Ward', 26, 52)
Row 402 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 19, 1, 11), 'Maternity Ward', 23, 51)
Row 403 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 19, 2, 3), 'ICU', 27, 41)
Row 404 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 19, 2, 12), 'Surgical Ward', 23, 50)
Row 405 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 19, 2, 14), 'Emergency Ward', 26, 53)
Row 406 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 19, 2, 27), 'Maternity Ward', 23, 52)
Row 407 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 19, 3, 10), 'ICU', 27, 41)
Row 408 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 19, 3, 28), 'Emergency Ward', 26, 53)
Row 409 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 19, 3, 32), 'Surgical Ward', 23, 50)
Row 410 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 19, 3, 34), 'Maternity Ward', 23, 54)
Row 411 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 19, 4, 30), 'ICU', 27, 42)
Row 412 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 19, 4, 38), 'Emergency Ward', 26, 53)
Row 413 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 19, 4, 53), 'Surgical Ward', 23, 50)
Row 414 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 19, 4, 54), 'Maternity Ward', 23, 56)
Row 415 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 19, 5, 49), 'ICU', 27, 42)
Row 416 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 19, 5, 59), 'Emergency Ward', 26, 53)
Row 417 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 19, 6, 13), 'Surgical Ward', 23, 51)
Row 418 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 19, 6, 14), 'Maternity Ward', 23, 53)
Row 419 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 19, 7, 8), 'ICU', 27, 42)
Row 420 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 19, 7, 21), 'Emergency Ward', 26, 53)

Row 421 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 19, 7, 34), 'Surgical Ward', 23, 51)
Row 422 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 19, 7, 35), 'Maternity Ward', 23, 52)
Row 423 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 19, 8, 27), 'ICU', 27, 42)
Row 424 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 19, 8, 42), 'Emergency Ward', 27, 52)
Row 425 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 19, 8, 54), 'Surgical Ward', 23, 51)
Row 426 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 19, 8, 57), 'Maternity Ward', 23, 54)
Row 427 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 19, 9, 47), 'ICU', 27, 42)
Row 428 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 19, 10, 3), 'Emergency Ward', 26, 54)
Row 429 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 19, 10, 15), 'Surgical Ward', 23, 51)
Row 430 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 19, 10, 17), 'Maternity Ward', 23, 54)
Row 431 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 19, 11, 5), 'ICU', 27, 42)
Row 432 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 19, 11, 24), 'Emergency Ward', 26, 54)
Row 433 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 19, 11, 28), 'Surgical Ward', 23, 53)
Row 434 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 19, 11, 37), 'Maternity Ward', 23, 54)
Row 435 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 19, 12, 24), 'ICU', 27, 42)
Row 436 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 19, 12, 37), 'Surgical Ward', 23, 52)
Row 437 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 19, 12, 45), 'Emergency Ward', 27, 53)
Row 438 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 19, 12, 57), 'Maternity Ward', 23, 54)
Row 439 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 19, 13, 43), 'ICU', 27, 42)
Row 440 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 19, 13, 57), 'Surgical Ward', 23, 53)
Row 441 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 19, 14, 7), 'Emergency Ward', 26, 54)
Row 442 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 19, 14, 17), 'Maternity Ward', 23, 55)
Row 443 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 19, 15, 2), 'ICU', 27, 42)
Row 444 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 19, 15, 18), 'Surgical Ward', 23, 53)
Row 445 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 19, 15, 27), 'Emergency Ward', 27, 53)
Row 446 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 19, 15, 37), 'Maternity Ward', 23, 55)
Row 447 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 19, 16, 14), 'ICU', 27, 42)
Row 448 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 19, 16, 38), 'Surgical Ward', 23, 54)
Row 449 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 19, 16, 48), 'Emergency Ward', 27, 53)
Row 450 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 19, 16, 51), 'Maternity Ward', 23, 55)
Row 451 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 19, 17, 22), 'ICU', 27, 42)
Row 452 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 19, 17, 59), 'Surgical Ward', 23, 54)
Row 453 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 19, 18), 'Maternity Ward', 23, 55)
Row 454 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 19, 18, 2), 'Emergency Ward', 26, 54)
Row 455 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 19, 18, 41), 'ICU', 27, 42)
Row 456 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 19, 19, 12), 'Emergency Ward', 27, 54)
Row 457 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 19, 19, 19), 'Surgical Ward', 23, 54)
Row 458 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 19, 19, 20), 'Maternity Ward', 23, 55)
Row 459 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 19, 20), 'ICU', 27, 42)
Row 460 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 19, 20, 34), 'Emergency Ward', 27, 54)
Row 461 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 19, 20, 40), 'Surgical Ward', 24, 54)
Row 462 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 19, 20, 41), 'Maternity Ward', 23, 56)
Row 463 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 19, 21, 19), 'ICU', 27, 42)
Row 464 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 19, 21, 54), 'Emergency Ward', 27, 54)
Row 465 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 19, 22), 'Surgical Ward', 23, 55)
Row 466 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 19, 22, 1), 'Maternity Ward', 23, 55)
Row 467 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 19, 22, 39), 'ICU', 27, 42)

Row 468 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 19, 23, 17), 'Emergency Ward', 27, 54)
Row 469 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 19, 23, 21), 'Surgical Ward', 24, 55)
Row 470 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 19, 23, 22), 'Maternity Ward', 23, 56)
Row 471 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 19, 23, 58), 'ICU', 27, 42)
Row 472 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 19, 24, 37), 'Emergency Ward', 27, 54)
Row 473 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 19, 24, 41), 'Surgical Ward', 24, 55)
Row 474 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 19, 24, 42), 'Maternity Ward', 23, 56)
Row 475 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 19, 25, 17), 'ICU', 27, 42)
Row 476 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 19, 25, 55), 'Surgical Ward', 24, 55)
Row 477 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 19, 25, 58), 'Emergency Ward', 27, 54)
Row 478 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 19, 26, 2), 'Maternity Ward', 23, 56)
Row 479 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 19, 26, 37), 'ICU', 27, 42)
Row 480 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 19, 27, 4), 'Surgical Ward', 23, 55)
Row 481 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 19, 27, 20), 'Emergency Ward', 27, 54)
Row 482 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 19, 27, 22), 'Maternity Ward', 23, 56)
Row 483 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 19, 27, 55), 'ICU', 27, 42)
Row 484 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 19, 28, 24), 'Surgical Ward', 24, 56)
Row 485 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 19, 28, 40), 'Emergency Ward', 27, 54)
Row 486 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 19, 28, 43), 'Maternity Ward', 24, 56)
Row 487 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 19, 29, 14), 'ICU', 27, 42)
Row 488 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 19, 29, 44), 'Surgical Ward', 24, 56)
Row 489 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 19, 30, 1), 'Emergency Ward', 27, 54)
Row 490 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 19, 30, 3), 'Maternity Ward', 23, 56)
Row 491 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 19, 30, 27), 'ICU', 27, 43)
Row 492 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 19, 31, 5), 'Surgical Ward', 24, 56)
Row 493 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 19, 31, 17), 'Maternity Ward', 23, 56)
Row 494 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 19, 31, 24), 'Emergency Ward', 27, 54)
Row 495 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 19, 31, 34), 'ICU', 27, 42)
Row 496 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 19, 32, 27), 'Surgical Ward', 24, 56)
Row 497 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 19, 32, 28), 'Maternity Ward', 23, 57)
Row 498 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 19, 32, 37), 'Emergency Ward', 27, 54)
Row 499 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 19, 32, 53), 'ICU', 27, 42)
Row 500 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 19, 33, 47), 'Surgical Ward', 24, 56)
Row 501 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 19, 33, 48), 'Emergency Ward', 27, 54)
Row 502 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 19, 33, 49), 'Maternity Ward', 23, 57)
Row 503 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 19, 34, 12), 'ICU', 28, 43)
Row 504 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 19, 35, 7), 'Surgical Ward', 24, 56)
Row 505 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 19, 35, 8), 'Maternity Ward', 23, 57)
Row 506 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 19, 35, 9), 'Emergency Ward', 27, 54)
Row 507 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 19, 35, 31), 'ICU', 28, 43)
Row 508 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 19, 36, 27), 'Surgical Ward', 24, 56)
Row 509 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 19, 36, 28), 'Maternity Ward', 23, 57)
Row 510 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 19, 36, 29), 'Emergency Ward', 27, 54)
Row 511 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 19, 36, 50), 'ICU', 28, 43)
Row 512 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 19, 37, 47), 'Surgical Ward', 24, 56)
Row 513 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 19, 37, 48), 'Maternity Ward', 23, 57)

Row 514 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 19, 37, 50), 'Emergency Ward', 27, 54)
Row 515 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 19, 38, 9), 'ICU', 27, 43)
Row 516 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 19, 39, 8), 'Surgical Ward', 24, 57)
Row 517 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 19, 39, 9), 'Maternity Ward', 23, 59)
Row 518 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 19, 39, 11), 'Emergency Ward', 27, 55)
Row 519 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 19, 39, 28), 'ICU', 28, 43)
Row 520 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 19, 40, 21), 'Surgical Ward', 24, 57)
Row 521 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 19, 40, 29), 'Maternity Ward', 24, 59)
Row 522 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 19, 40, 47), 'ICU', 28, 43)
Row 523 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 19, 41, 31), 'Surgical Ward', 24, 57)
Row 524 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 19, 41, 50), 'Maternity Ward', 24, 58)
Row 525 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 19, 41, 55), 'Emergency Ward', 27, 55)
Row 526 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 19, 42, 7), 'ICU', 28, 43)
Row 527 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 19, 42, 51), 'Surgical Ward', 24, 57)
Row 528 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 19, 43, 10), 'Maternity Ward', 23, 58)
Row 529 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 19, 43, 14), 'Emergency Ward', 27, 55)
Row 530 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 19, 43, 27), 'ICU', 28, 43)
Row 531 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 19, 44, 11), 'Surgical Ward', 24, 57)
Row 532 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 19, 44, 30), 'Maternity Ward', 24, 59)
Row 533 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 19, 44, 37), 'Emergency Ward', 27, 55)
Row 534 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 19, 44, 38), 'ICU', 28, 43)
Row 535 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 19, 45, 32), 'Surgical Ward', 24, 57)
Row 536 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 19, 45, 43), 'Maternity Ward', 23, 58)
Row 537 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 19, 45, 47), 'ICU', 28, 43)
Row 538 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 19, 45, 57), 'Emergency Ward', 27, 55)
Row 539 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 19, 46, 52), 'Surgical Ward', 24, 58)
Row 540 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 19, 46, 53), 'Maternity Ward', 24, 59)
Row 541 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 19, 47, 5), 'ICU', 28, 43)
Row 542 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 19, 47, 10), 'Emergency Ward', 27, 56)
Row 543 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 19, 48, 12), 'Surgical Ward', 24, 58)
Row 544 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 19, 48, 13), 'Maternity Ward', 23, 59)
Row 545 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 19, 48, 20), 'Emergency Ward', 27, 56)
Row 546 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 19, 48, 24), 'ICU', 28, 43)
Row 547 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 19, 49, 34), 'Maternity Ward', 24, 60)
Row 548 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 19, 49, 41), 'Emergency Ward', 27, 56)
Row 549 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 19, 49, 43), 'ICU', 28, 43)
Row 550 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 19, 51, 2), 'ICU', 28, 43)
Row 551 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 19, 51, 3), 'Emergency Ward', 27, 56)
Row 552 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 19, 52, 14), 'Maternity Ward', 24, 59)
Row 553 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 19, 52, 21), 'ICU', 28, 43)
Row 554 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 19, 52, 24), 'Emergency Ward', 27, 56)
Row 555 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 19, 53, 40), 'ICU', 28, 43)
Row 556 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 19, 53, 45), 'Emergency Ward', 27, 56)
Row 557 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 19, 54, 48), 'Surgical Ward', 24, 59)
Row 558 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 19, 54, 55), 'Maternity Ward', 24, 60)
Row 559 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 19, 54, 59), 'ICU', 28, 44)

Row 560 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 19, 55, 7), 'Emergency Ward', 27, 57)
Row 561 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 19, 55, 57), 'Surgical Ward', 24, 59)
Row 562 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 19, 56, 17), 'Maternity Ward', 24, 60)
Row 563 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 19, 56, 20), 'ICU', 28, 44)
Row 564 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 19, 56, 28), 'Emergency Ward', 27, 57)
Row 565 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 19, 57, 17), 'Surgical Ward', 24, 59)
Row 566 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 19, 57, 37), 'Maternity Ward', 24, 60)
Row 567 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 19, 57, 38), 'ICU', 28, 44)
Row 568 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 19, 57, 48), 'Emergency Ward', 27, 57)
Row 569 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 19, 58, 39), 'Surgical Ward', 24, 59)
Row 570 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 19, 58, 50), 'ICU', 28, 44)
Row 571 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 19, 58, 57), 'Maternity Ward', 24, 60)
Row 572 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 19, 59, 9), 'Emergency Ward', 27, 57)
Row 573 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 19, 59, 57), 'ICU', 28, 44)
Row 574 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 19, 59, 59), 'Surgical Ward', 24, 60)
Row 575 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 20, 0, 9), 'Maternity Ward', 24, 60)
Row 576 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 20, 0, 30), 'Emergency Ward', 27, 57)
Row 577 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 20, 1, 17), 'ICU', 28, 44)
Row 578 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 20, 1, 18), 'Maternity Ward', 24, 61)
Row 579 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 20, 1, 19), 'Surgical Ward', 24, 60)
Row 580 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 20, 1, 44), 'Emergency Ward', 27, 57)
Row 581 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 20, 2, 37), 'ICU', 28, 44)
Row 582 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 20, 2, 39), 'Maternity Ward', 24, 61)
Row 583 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 20, 2, 40), 'Surgical Ward', 24, 60)
Row 584 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 20, 2, 54), 'Emergency Ward', 27, 58)
Row 585 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 20, 3, 55), 'ICU', 28, 44)
Row 586 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 20, 3, 59), 'Maternity Ward', 23, 60)
Row 587 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 20, 4), 'Surgical Ward', 24, 60)
Row 588 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 20, 4, 17), 'Emergency Ward', 27, 58)
Row 589 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 20, 5, 14), 'ICU', 28, 44)
Row 590 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 20, 5, 20), 'Maternity Ward', 24, 61)
Row 591 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 20, 5, 21), 'Surgical Ward', 24, 60)
Row 592 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 20, 5, 37), 'Emergency Ward', 27, 58)
Row 593 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 20, 6, 33), 'ICU', 28, 44)
Row 594 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 20, 6, 40), 'Maternity Ward', 24, 61)
Row 595 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 20, 6, 41), 'Surgical Ward', 24, 61)
Row 596 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 20, 6, 58), 'Emergency Ward', 27, 58)
Row 597 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 20, 7, 52), 'ICU', 28, 44)
Row 598 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 20, 8, 1), 'Maternity Ward', 24, 61)
Row 599 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 20, 8, 3), 'Surgical Ward', 24, 61)
Row 600 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 20, 8, 19), 'Emergency Ward', 27, 58)
Row 601 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 20, 9, 11), 'ICU', 28, 45)
Row 602 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 20, 9, 15), 'Surgical Ward', 24, 61)
Row 603 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 20, 9, 21), 'Maternity Ward', 24, 61)
Row 604 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 20, 9, 40), 'Emergency Ward', 27, 58)
Row 605 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 20, 10, 24), 'Surgical Ward', 24, 61)
Row 606 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 20, 10, 30), 'ICU', 28, 45)

Row 607 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 20, 10, 41), 'Maternity Ward', 24, 61)
Row 608 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 20, 11, 1), 'Emergency Ward', 27, 58)
Row 609 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 20, 11, 44), 'Surgical Ward', 24, 61)
Row 610 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 20, 11, 50), 'ICU', 28, 45)
Row 611 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 20, 12, 2), 'Maternity Ward', 24, 61)
Row 612 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 20, 12, 22), 'Emergency Ward', 27, 58)
Row 613 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 20, 13, 3), 'ICU', 28, 45)
Row 614 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 20, 13, 5), 'Surgical Ward', 24, 61)
Row 615 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 20, 13, 22), 'Maternity Ward', 24, 61)
Row 616 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 20, 13, 43), 'Emergency Ward', 27, 58)
Row 617 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 20, 14, 9), 'ICU', 28, 45)
Row 618 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 20, 14, 25), 'Surgical Ward', 24, 61)
Row 619 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 20, 14, 37), 'Maternity Ward', 24, 61)
Row 620 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 23, 30, 54), 'Emergency Ward', 28, 62)
Row 621 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 23, 31, 17), 'Maternity Ward', 24, 68)
Row 622 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 23, 31, 29), 'Surgical Ward', 24, 66)
Row 623 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 23, 31, 51), 'ICU', 28, 55)
Row 624 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 23, 32, 15), 'Emergency Ward', 28, 62)
Row 625 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 23, 32, 38), 'Surgical Ward', 24, 66)
Row 626 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 23, 32, 39), 'Maternity Ward', 24, 68)
Row 627 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 23, 32, 58), 'ICU', 28, 54)
Row 628 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 23, 33, 58), 'Surgical Ward', 24, 66)
Row 629 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 23, 33, 59), 'Maternity Ward', 24, 68)
Row 630 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 23, 34, 17), 'ICU', 28, 54)
Row 631 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 23, 34, 57), 'Emergency Ward', 28, 62)
Row 632 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 23, 35, 19), 'Maternity Ward', 24, 68)
Row 633 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 23, 35, 37), 'ICU', 28, 54)
Row 634 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 23, 36, 19), 'Emergency Ward', 28, 62)
Row 635 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 23, 36, 32), 'Maternity Ward', 24, 68)
Row 636 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 23, 36, 39), 'Surgical Ward', 24, 66)
Row 637 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 23, 36, 55), 'ICU', 28, 54)
Row 638 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 23, 37, 41), 'Emergency Ward', 28, 62)
Row 639 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 23, 37, 43), 'Maternity Ward', 24, 68)
Row 640 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 23, 38), 'Surgical Ward', 25, 66)
Row 641 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 23, 38, 14), 'ICU', 28, 54)
Row 642 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 23, 39, 1), 'Emergency Ward', 28, 62)
Row 643 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 23, 39, 2), 'Maternity Ward', 24, 68)
Row 644 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 23, 39, 20), 'Surgical Ward', 24, 67)
Row 645 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 23, 39, 34), 'ICU', 28, 55)
Row 646 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 23, 40, 15), 'Emergency Ward', 28, 62)
Row 647 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 23, 40, 22), 'Maternity Ward', 24, 68)
Row 648 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 23, 40, 40), 'Surgical Ward', 24, 66)
Row 649 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 23, 40, 53), 'ICU', 28, 55)
Row 650 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 23, 41, 25), 'Emergency Ward', 28, 62)
Row 651 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 23, 41, 42), 'Maternity Ward', 24, 68)
Row 652 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 23, 42, 1), 'Surgical Ward', 24, 66)
Row 653 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 23, 42, 12), 'ICU', 28, 55)

Row 654 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 23, 42, 47), 'Emergency Ward', 28, 62)
Row 655 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 23, 43, 3), 'Maternity Ward', 24, 68)
Row 656 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 23, 43, 21), 'Surgical Ward', 24, 67)
Row 657 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 23, 43, 31), 'ICU', 28, 55)
Row 658 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 23, 44, 8), 'Emergency Ward', 28, 62)
Row 659 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 23, 44, 23), 'Maternity Ward', 24, 68)
Row 660 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 23, 44, 42), 'Surgical Ward', 24, 67)
Row 661 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 23, 44, 50), 'ICU', 28, 55)
Row 662 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 23, 45, 29), 'Emergency Ward', 28, 62)
Row 663 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 23, 45, 44), 'Maternity Ward', 24, 69)
Row 664 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 23, 45, 57), 'Surgical Ward', 24, 67)
Row 665 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 23, 46, 2), 'ICU', 28, 55)
Row 666 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 23, 46, 50), 'Emergency Ward', 28, 62)
Row 667 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 23, 47, 4), 'Maternity Ward', 24, 68)
Row 668 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 23, 47, 5), 'Surgical Ward', 24, 67)
Row 669 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 23, 47, 10), 'ICU', 28, 55)
Row 670 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 23, 48, 11), 'Emergency Ward', 28, 62)
Row 671 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 23, 48, 24), 'Maternity Ward', 24, 68)
Row 672 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 23, 48, 27), 'Surgical Ward', 24, 67)
Row 673 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 23, 48, 29), 'ICU', 28, 55)
Row 674 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 23, 49, 32), 'Emergency Ward', 28, 62)
Row 675 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 23, 49, 45), 'Maternity Ward', 24, 68)
Row 676 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 23, 49, 47), 'Surgical Ward', 24, 67)
Row 677 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 23, 49, 48), 'ICU', 28, 55)
Row 678 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 23, 50, 53), 'Emergency Ward', 28, 62)
Row 679 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 23, 50, 58), 'Maternity Ward', 24, 68)
Row 680 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 23, 51, 7), 'Surgical Ward', 25, 66)
Row 681 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 23, 51, 8), 'ICU', 28, 55)
Row 682 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 23, 52, 7), 'Maternity Ward', 24, 68)
Row 683 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 23, 52, 14), 'Emergency Ward', 28, 62)
Row 684 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 23, 52, 27), 'Surgical Ward', 25, 66)
Row 685 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 23, 52, 28), 'ICU', 28, 55)
Row 686 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 23, 53, 28), 'Maternity Ward', 24, 68)
Row 687 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 23, 53, 37), 'Emergency Ward', 28, 62)
Row 688 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 23, 53, 47), 'ICU', 28, 55)
Row 689 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 23, 53, 48), 'Surgical Ward', 24, 67)
Row 690 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 23, 54, 48), 'Maternity Ward', 24, 68)
Row 691 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 23, 54, 50), 'Emergency Ward', 28, 62)
Row 692 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 23, 55, 5), 'ICU', 28, 55)
Row 693 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 23, 55, 7), 'Surgical Ward', 25, 66)
Row 694 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 23, 55, 59), 'Emergency Ward', 28, 62)
Row 695 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 23, 56, 8), 'Maternity Ward', 24, 69)
Row 696 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 23, 56, 24), 'ICU', 28, 55)
Row 697 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 23, 56, 28), 'Surgical Ward', 24, 67)
Row 698 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 23, 57, 21), 'Emergency Ward', 28, 62)
Row 699 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 23, 57, 29), 'Maternity Ward', 24, 68)
Row 700 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 23, 57, 43), 'ICU', 25, 53)

Row 701 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 23, 57, 48), 'Surgical Ward', 25, 66)
Row 702 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 23, 58, 42), 'Emergency Ward', 28, 62)
Row 703 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 23, 58, 49), 'Maternity Ward', 24, 68)
Row 704 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 23, 59, 2), 'ICU', 28, 55)
Row 705 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 12, 23, 59, 9), 'Surgical Ward', 24, 67)
Row 706 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 0, 0, 3), 'Emergency Ward', 28, 62)
Row 707 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 0, 0, 10), 'Maternity Ward', 24, 69)
Row 708 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 0, 0, 14), 'ICU', 28, 55)
Row 709 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 0, 0, 22), 'Surgical Ward', 24, 67)
Row 710 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 0, 1, 22), 'ICU', 28, 55)
Row 711 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 0, 1, 24), 'Emergency Ward', 28, 62)
Row 712 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 0, 1, 30), 'Maternity Ward', 24, 68)
Row 713 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 0, 1, 31), 'Surgical Ward', 25, 66)
Row 714 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 0, 2, 41), 'ICU', 28, 55)
Row 715 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 0, 2, 47), 'Emergency Ward', 28, 62)
Row 716 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 0, 2, 50), 'Maternity Ward', 24, 69)
Row 717 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 0, 2, 52), 'Surgical Ward', 24, 67)
Row 718 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 0, 4), 'ICU', 28, 55)
Row 719 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 0, 4, 7), 'Emergency Ward', 28, 62)
Row 720 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 0, 4, 11), 'Maternity Ward', 24, 68)
Row 721 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 0, 4, 12), 'Surgical Ward', 24, 67)
Row 722 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 0, 5, 19), 'ICU', 28, 55)
Row 723 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 0, 5, 24), 'Maternity Ward', 24, 68)
Row 724 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 0, 5, 28), 'Emergency Ward', 28, 62)
Row 725 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 0, 5, 33), 'Surgical Ward', 24, 67)
Row 726 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 0, 6, 33), 'Maternity Ward', 24, 69)
Row 727 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 0, 6, 39), 'ICU', 28, 55)
Row 728 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 0, 6, 49), 'Emergency Ward', 28, 62)
Row 729 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 0, 6, 53), 'Surgical Ward', 24, 67)
Row 730 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 0, 7, 54), 'Maternity Ward', 24, 68)
Row 731 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 0, 7, 58), 'ICU', 28, 55)
Row 732 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 0, 8, 10), 'Emergency Ward', 28, 62)
Row 733 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 0, 8, 14), 'Surgical Ward', 24, 67)
Row 734 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 0, 9, 14), 'Maternity Ward', 24, 69)
Row 735 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 0, 9, 17), 'ICU', 28, 55)
Row 736 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 0, 9, 24), 'Emergency Ward', 28, 62)
Row 737 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 0, 9, 34), 'Surgical Ward', 24, 67)
Row 738 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 0, 10, 34), 'Emergency Ward', 28, 62)
Row 739 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 0, 10, 37), 'Maternity Ward', 24, 68)
Row 740 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 0, 10, 38), 'ICU', 28, 55)
Row 741 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 0, 10, 55), 'Surgical Ward', 24, 67)
Row 742 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 0, 11, 55), 'Maternity Ward', 24, 69)
Row 743 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 0, 11, 58), 'ICU', 28, 55)
Row 744 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 0, 11, 59), 'Emergency Ward', 28, 62)
Row 745 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 0, 12, 15), 'Surgical Ward', 24, 67)
Row 746 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 0, 13, 14), 'ICU', 28, 55)
Row 747 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 0, 13, 17), 'Maternity Ward', 24, 69)
Row 748 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 0, 13, 19), 'Emergency Ward', 28, 63)
Row 749 is Updated!!!

INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 0, 13, 37), 'Surgical Ward', 24, 67)
Row 750 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 0, 14, 28), 'ICU', 28, 55)
Row 751 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 0, 14, 37), 'Maternity Ward', 24, 68)
Row 752 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 0, 14, 38), 'Emergency Ward', 28, 63)
Row 753 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 0, 14, 49), 'Surgical Ward', 24, 67)
Row 754 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 0, 15, 34), 'ICU', 28, 55)
Row 755 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 0, 15, 57), 'Maternity Ward', 24, 68)
Row 756 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 0, 15, 58), 'Surgical Ward', 24, 67)
Row 757 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 0, 15, 59), 'Emergency Ward', 28, 63)
Row 758 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 0, 16, 53), 'ICU', 28, 55)
Row 759 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 0, 17, 17), 'Maternity Ward', 24, 69)
Row 760 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 0, 17, 19), 'Surgical Ward', 24, 67)
Row 761 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 0, 17, 20), 'Emergency Ward', 28, 63)
Row 762 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 0, 18, 13), 'ICU', 28, 55)
Row 763 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 0, 18, 37), 'Maternity Ward', 24, 68)
Row 764 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 0, 18, 39), 'Surgical Ward', 24, 67)
Row 765 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 0, 18, 42), 'Emergency Ward', 28, 63)
Row 766 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 0, 19, 32), 'ICU', 25, 53)
Row 767 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 0, 19, 50), 'Maternity Ward', 24, 69)
Row 768 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 0, 20, 1), 'Surgical Ward', 24, 67)
Row 769 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 0, 20, 4), 'Emergency Ward', 28, 63)
Row 770 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 0, 20, 51), 'ICU', 28, 55)
Row 771 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 0, 21), 'Maternity Ward', 24, 69)
Row 772 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 0, 21, 20), 'Surgical Ward', 25, 66)
Row 773 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 0, 21, 25), 'Emergency Ward', 28, 63)
Row 774 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 0, 22, 10), 'ICU', 28, 55)
Row 775 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 0, 22, 20), 'Maternity Ward', 24, 69)
Row 776 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 0, 22, 41), 'Surgical Ward', 24, 67)
Row 777 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 0, 22, 45), 'Emergency Ward', 28, 63)
Row 778 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 0, 23, 29), 'ICU', 28, 55)
Row 779 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 0, 23, 40), 'Maternity Ward', 24, 69)
Row 780 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 0, 23, 59), 'Emergency Ward', 28, 63)
Row 781 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 0, 24, 1), 'Surgical Ward', 24, 67)
Row 782 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 0, 24, 51), 'ICU', 28, 55)
Row 783 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 0, 25, 1), 'Maternity Ward', 24, 68)
Row 784 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 0, 25, 9), 'Emergency Ward', 28, 63)
Row 785 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 0, 25, 23), 'Surgical Ward', 24, 67)
Row 786 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 0, 26, 8), 'ICU', 25, 53)
Row 787 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 0, 26, 21), 'Maternity Ward', 24, 69)
Row 788 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 0, 26, 30), 'Emergency Ward', 28, 63)
Row 789 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 0, 26, 42), 'Surgical Ward', 24, 67)
Row 790 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 0, 27, 28), 'ICU', 28, 55)
Row 791 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 0, 27, 41), 'Maternity Ward', 24, 69)
Row 792 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 0, 27, 52), 'Emergency Ward', 28, 63)
Row 793 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 0, 28, 2), 'Surgical Ward', 24, 67)
Row 794 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 0, 28, 39), 'ICU', 28, 55)
Row 795 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 0, 29, 2), 'Maternity Ward', 24, 68)
Row 796 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 0, 29, 13), 'Emergency Ward', 28, 63)

Row 797 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 0, 29, 16), 'Surgical Ward', 24, 67)
Row 798 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 0, 29, 47), 'ICU', 28, 55)
Row 799 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 0, 30, 23), 'Maternity Ward', 25, 67)
Row 800 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 0, 30, 25), 'Surgical Ward', 24, 67)
Row 801 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 0, 30, 34), 'Emergency Ward', 28, 63)
Row 802 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 0, 31, 8), 'ICU', 28, 55)
Row 803 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 0, 31, 43), 'Maternity Ward', 24, 69)
Row 804 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 0, 31, 45), 'Surgical Ward', 24, 67)
Row 805 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 0, 31, 55), 'Emergency Ward', 28, 63)
Row 806 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 0, 32, 25), 'ICU', 28, 55)
Row 807 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 0, 33, 3), 'Maternity Ward', 24, 69)
Row 808 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 0, 33, 7), 'Surgical Ward', 24, 67)
Row 809 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 0, 33, 17), 'Emergency Ward', 28, 63)
Row 810 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 0, 33, 44), 'ICU', 28, 55)
Row 811 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 0, 34, 17), 'Maternity Ward', 24, 69)
Row 812 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 0, 34, 27), 'Surgical Ward', 24, 67)
Row 813 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 0, 34, 37), 'Emergency Ward', 28, 63)
Row 814 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 0, 35, 3), 'ICU', 28, 55)
Row 815 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 0, 35, 27), 'Maternity Ward', 24, 69)
Row 816 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 0, 35, 47), 'Surgical Ward', 24, 67)
Row 817 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 0, 35, 59), 'Emergency Ward', 28, 63)
Row 818 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 0, 36, 22), 'ICU', 28, 55)
Row 819 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 0, 36, 47), 'Maternity Ward', 24, 69)
Row 820 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 0, 37, 7), 'Surgical Ward', 24, 67)
Row 821 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 0, 37, 19), 'Emergency Ward', 28, 63)
Row 822 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 0, 37, 41), 'ICU', 28, 55)
Row 823 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 0, 38, 7), 'Maternity Ward', 24, 69)
Row 824 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 0, 38, 28), 'Surgical Ward', 24, 67)
Row 825 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 0, 38, 34), 'Emergency Ward', 28, 63)
Row 826 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 0, 39), 'ICU', 28, 55)
Row 827 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 0, 39, 27), 'Maternity Ward', 24, 69)
Row 828 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 0, 39, 43), 'Emergency Ward', 28, 63)
Row 829 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 0, 39, 48), 'Surgical Ward', 24, 67)
Row 830 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 0, 40, 19), 'ICU', 28, 55)
Row 831 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 0, 40, 47), 'Maternity Ward', 24, 69)
Row 832 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 0, 41, 4), 'Emergency Ward', 28, 63)
Row 833 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 0, 41, 39), 'ICU', 28, 55)
Row 834 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 0, 42, 8), 'Maternity Ward', 24, 69)
Row 835 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 0, 42, 27), 'Emergency Ward', 28, 63)
Row 836 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 0, 42, 29), 'Surgical Ward', 24, 67)
Row 837 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 0, 42, 51), 'ICU', 28, 55)
Row 838 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 0, 43, 28), 'Maternity Ward', 24, 69)
Row 839 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 0, 43, 42), 'Surgical Ward', 24, 67)
Row 840 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 0, 43, 47), 'Emergency Ward', 28, 63)
Row 841 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 0, 43, 58), 'ICU', 28, 55)
Row 842 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 0, 44, 49), 'Maternity Ward', 24, 69)
Row 843 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 0, 44, 51), 'Surgical Ward', 24, 67)

Row 844 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 0, 45, 8), 'Emergency Ward', 27, 63)
Row 845 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 0, 45, 18), 'ICU', 28, 55)
Row 846 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 0, 46, 9), 'Maternity Ward', 24, 69)
Row 847 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 0, 46, 12), 'Surgical Ward', 24, 67)
Row 848 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 0, 46, 29), 'Emergency Ward', 28, 63)
Row 849 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 0, 46, 37), 'ICU', 28, 55)
Row 850 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 0, 47, 30), 'Maternity Ward', 24, 69)
Row 851 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 0, 47, 32), 'Surgical Ward', 24, 67)
Row 852 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 0, 47, 50), 'Emergency Ward', 28, 63)
Row 853 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 0, 47, 57), 'ICU', 28, 55)
Row 854 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 0, 48, 43), 'Maternity Ward', 24, 69)
Row 855 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 0, 48, 53), 'Surgical Ward', 25, 66)
Row 856 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 0, 49, 11), 'Emergency Ward', 27, 62)
Row 857 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 0, 49, 15), 'ICU', 28, 55)
Row 858 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 0, 49, 52), 'Maternity Ward', 24, 69)
Row 859 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 0, 50, 13), 'Surgical Ward', 24, 67)
Row 860 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 0, 50, 32), 'Emergency Ward', 27, 62)
Row 861 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 0, 50, 34), 'ICU', 28, 55)
Row 862 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 0, 51, 12), 'Maternity Ward', 24, 69)
Row 863 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 0, 51, 34), 'Surgical Ward', 24, 67)
Row 864 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 0, 51, 53), 'ICU', 28, 55)
Row 865 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 0, 51, 54), 'Emergency Ward', 27, 63)
Row 866 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 0, 52, 33), 'Maternity Ward', 24, 69)
Row 867 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 0, 52, 55), 'Surgical Ward', 24, 67)
Row 868 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 0, 53, 8), 'Emergency Ward', 28, 63)
Row 869 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 0, 53, 12), 'ICU', 28, 55)
Row 870 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 0, 53, 53), 'Maternity Ward', 24, 69)
Row 871 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 0, 54, 15), 'Surgical Ward', 24, 67)
Row 872 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 0, 54, 17), 'Emergency Ward', 27, 63)
Row 873 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 0, 54, 31), 'ICU', 28, 55)
Row 874 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 0, 55, 13), 'Maternity Ward', 24, 69)
Row 875 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 0, 55, 35), 'Surgical Ward', 24, 67)
Row 876 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 0, 55, 38), 'Emergency Ward', 27, 63)
Row 877 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 0, 55, 51), 'ICU', 28, 55)
Row 878 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 0, 56, 34), 'Maternity Ward', 24, 69)
Row 879 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 0, 56, 57), 'Surgical Ward', 24, 67)
Row 880 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 0, 57), 'Emergency Ward', 27, 63)
Row 881 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 0, 57, 3), 'ICU', 28, 55)
Row 882 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 0, 57, 54), 'Maternity Ward', 24, 69)
Row 883 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 0, 58, 9), 'Surgical Ward', 24, 67)
Row 884 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 0, 58, 11), 'ICU', 28, 55)
Row 885 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 0, 58, 21), 'Emergency Ward', 27, 63)
Row 886 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 0, 59, 15), 'Maternity Ward', 24, 69)
Row 887 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 0, 59, 18), 'Surgical Ward', 24, 67)
Row 888 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 0, 59, 30), 'ICU', 28, 55)
Row 889 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 0, 59, 42), 'Emergency Ward', 27, 62)
Row 890 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 1, 0, 35), 'Maternity Ward', 24, 69)

Row 891 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 1, 0, 49), 'ICU', 28, 55)
Row 892 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 1, 1, 3), 'Emergency Ward', 28, 62)
Row 893 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 1, 1, 55), 'Maternity Ward', 24, 69)
Row 894 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 1, 1, 59), 'Surgical Ward', 25, 66)
Row 895 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 1, 2, 8), 'ICU', 28, 55)
Row 896 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 1, 2, 24), 'Emergency Ward', 28, 62)
Row 897 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 1, 3, 9), 'Maternity Ward', 24, 69)
Row 898 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 1, 3, 20), 'Surgical Ward', 24, 67)
Row 899 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 1, 3, 27), 'ICU', 28, 55)
Row 900 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 1, 3, 45), 'Emergency Ward', 28, 62)
Row 901 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 1, 4, 18), 'Maternity Ward', 24, 69)
Row 902 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 1, 4, 40), 'Surgical Ward', 24, 67)
Row 903 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 1, 4, 47), 'ICU', 28, 55)
Row 904 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 1, 5, 7), 'Emergency Ward', 28, 62)
Row 905 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 1, 5, 38), 'Maternity Ward', 24, 69)
Row 906 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 1, 6), 'Surgical Ward', 24, 67)
Row 907 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 1, 6, 5), 'ICU', 28, 55)
Row 908 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 1, 6, 28), 'Emergency Ward', 28, 62)
Row 909 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 1, 6, 59), 'Maternity Ward', 24, 69)
Row 910 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 1, 7, 21), 'Surgical Ward', 25, 66)
Row 911 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 1, 7, 24), 'ICU', 28, 55)
Row 912 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 1, 7, 42), 'Emergency Ward', 28, 62)
Row 913 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 1, 8, 20), 'Maternity Ward', 24, 69)
Row 914 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 1, 8, 41), 'Surgical Ward', 24, 67)
Row 915 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 1, 8, 44), 'ICU', 25, 54)
Row 916 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 1, 8, 51), 'Emergency Ward', 28, 62)
Row 917 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 1, 9, 40), 'Maternity Ward', 24, 69)
Row 918 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 1, 10, 2), 'Surgical Ward', 24, 67)
Row 919 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 1, 10, 3), 'ICU', 28, 55)
Row 920 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 1, 10, 12), 'Emergency Ward', 28, 62)
Row 921 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 1, 11), 'Maternity Ward', 23, 69)
Row 922 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 1, 11, 15), 'ICU', 28, 55)
Row 923 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 1, 11, 22), 'Surgical Ward', 24, 67)
Row 924 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 1, 11, 34), 'Emergency Ward', 28, 62)
Row 925 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 1, 12, 20), 'Maternity Ward', 24, 69)
Row 926 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 1, 12, 23), 'ICU', 28, 55)
Row 927 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 1, 12, 37), 'Surgical Ward', 24, 67)
Row 928 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 1, 12, 55), 'Emergency Ward', 28, 62)
Row 929 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 1, 13, 41), 'Maternity Ward', 24, 69)
Row 930 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 1, 13, 42), 'ICU', 28, 55)
Row 931 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 1, 13, 45), 'Surgical Ward', 24, 67)
Row 932 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 1, 14, 17), 'Emergency Ward', 28, 62)
Row 933 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 1, 15, 1), 'ICU', 28, 55)
Row 934 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 1, 15, 2), 'Maternity Ward', 24, 69)
Row 935 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 1, 15, 5), 'Surgical Ward', 24, 67)
Row 936 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 1, 15, 37), 'Emergency Ward', 28, 62)
Row 937 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 1, 16, 20), 'ICU', 28, 55)

Row 938 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 1, 16, 22), 'Maternity Ward', 24, 69)
Row 939 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 1, 16, 27), 'Surgical Ward', 24, 67)
Row 940 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 1, 16, 58), 'Emergency Ward', 28, 62)
Row 941 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 1, 17, 35), 'Maternity Ward', 24, 69)
Row 942 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 1, 17, 39), 'ICU', 28, 56)
Row 943 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 1, 17, 47), 'Surgical Ward', 24, 67)
Row 944 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 1, 18, 19), 'Emergency Ward', 28, 62)
Row 945 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 1, 18, 44), 'Maternity Ward', 24, 70)
Row 946 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 1, 18, 58), 'ICU', 25, 54)
Row 947 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 1, 19, 7), 'Surgical Ward', 24, 67)
Row 948 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 1, 19, 41), 'Emergency Ward', 28, 62)
Row 949 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 1, 20, 4), 'Maternity Ward', 24, 69)
Row 950 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 1, 20, 17), 'ICU', 28, 55)
Row 951 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 1, 20, 27), 'Surgical Ward', 24, 67)
Row 952 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 1, 21, 2), 'Emergency Ward', 28, 62)
Row 953 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 1, 21, 25), 'Maternity Ward', 23, 69)
Row 954 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 1, 21, 37), 'ICU', 28, 56)
Row 955 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 1, 21, 48), 'Surgical Ward', 25, 66)
Row 956 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 1, 22, 17), 'Emergency Ward', 28, 62)
Row 957 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 1, 22, 45), 'Maternity Ward', 24, 70)
Row 958 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 1, 22, 57), 'ICU', 25, 54)
Row 959 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 1, 23, 8), 'Surgical Ward', 24, 67)
Row 960 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 1, 23, 25), 'Emergency Ward', 28, 62)
Row 961 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 1, 24, 7), 'Maternity Ward', 24, 69)
Row 962 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 1, 24, 15), 'ICU', 28, 56)
Row 963 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 1, 24, 29), 'Surgical Ward', 24, 67)
Row 964 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 1, 24, 48), 'Emergency Ward', 28, 62)
Row 965 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 1, 25, 27), 'Maternity Ward', 24, 69)
Row 966 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 1, 25, 28), 'ICU', 28, 56)
Row 967 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 1, 25, 49), 'Surgical Ward', 24, 67)
Row 968 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 1, 26, 8), 'Emergency Ward', 28, 62)
Row 969 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 1, 26, 35), 'ICU', 28, 56)
Row 970 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 1, 26, 48), 'Maternity Ward', 24, 70)
Row 971 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 1, 27, 3), 'Surgical Ward', 25, 66)
Row 972 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 1, 27, 29), 'Emergency Ward', 28, 62)
Row 973 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 1, 27, 54), 'ICU', 28, 56)
Row 974 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 1, 28, 8), 'Maternity Ward', 23, 69)
Row 975 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 1, 28, 12), 'Surgical Ward', 24, 67)
Row 976 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 1, 28, 50), 'Emergency Ward', 28, 62)
Row 977 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 1, 29, 13), 'ICU', 28, 56)
Row 978 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 1, 29, 28), 'Maternity Ward', 24, 69)
Row 979 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 1, 29, 32), 'Surgical Ward', 24, 67)
Row 980 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 1, 30, 11), 'Emergency Ward', 28, 62)
Row 981 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 1, 30, 32), 'ICU', 28, 56)
Row 982 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 1, 30, 48), 'Maternity Ward', 24, 69)
Row 983 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 1, 30, 53), 'Surgical Ward', 24, 67)
Row 984 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 1, 31, 32), 'Emergency Ward', 28, 62)
Row 985 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 1, 31, 51), 'ICU', 28, 56)

Row 986 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 1, 32, 1), 'Maternity Ward', 23, 69)
Row 987 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 1, 32, 13), 'Surgical Ward', 24, 67)
Row 988 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 1, 32, 53), 'Emergency Ward', 27, 62)
Row 989 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 1, 33, 10), 'Maternity Ward', 24, 69)
Row 990 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 1, 33, 11), 'ICU', 28, 56)
Row 991 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 1, 33, 34), 'Surgical Ward', 24, 67)
Row 992 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 1, 34, 14), 'Emergency Ward', 28, 62)
Row 993 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 1, 34, 30), 'ICU', 28, 56)
Row 994 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 1, 34, 31), 'Maternity Ward', 23, 70)
Row 995 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 1, 34, 54), 'Surgical Ward', 24, 67)
Row 996 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 1, 35, 35), 'Emergency Ward', 28, 62)
Row 997 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 1, 35, 49), 'ICU', 28, 56)
Row 998 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 1, 35, 51), 'Maternity Ward', 24, 69)
Row 999 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 1, 36, 14), 'Surgical Ward', 24, 67)
Row 1000 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 1, 36, 50), 'Emergency Ward', 28, 62)
Row 1001 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 1, 37, 8), 'ICU', 28, 56)
Row 1002 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 1, 37, 11), 'Maternity Ward', 24, 69)
Row 1003 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 1, 37, 35), 'Surgical Ward', 25, 66)
Row 1004 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 1, 37, 59), 'Emergency Ward', 28, 62)
Row 1005 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 1, 38, 28), 'ICU', 28, 56)
Row 1006 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 1, 38, 32), 'Maternity Ward', 23, 69)
Row 1007 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 1, 38, 55), 'Surgical Ward', 25, 66)
Row 1008 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 1, 39, 20), 'Emergency Ward', 28, 62)
Row 1009 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 1, 39, 39), 'ICU', 28, 56)
Row 1010 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 1, 39, 52), 'Maternity Ward', 23, 70)
Row 1011 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 1, 40, 17), 'Surgical Ward', 25, 66)
Row 1012 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 1, 40, 41), 'Emergency Ward', 28, 62)
Row 1013 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 1, 40, 48), 'ICU', 28, 56)
Row 1014 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 1, 41, 12), 'Maternity Ward', 23, 69)
Row 1015 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 1, 41, 29), 'Surgical Ward', 24, 67)
Row 1016 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 1, 42, 3), 'Emergency Ward', 28, 62)
Row 1017 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 1, 42, 7), 'ICU', 28, 56)
Row 1018 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 1, 42, 33), 'Maternity Ward', 24, 70)
Row 1019 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 1, 42, 38), 'Surgical Ward', 25, 66)
Row 1020 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 1, 43, 24), 'Emergency Ward', 27, 62)
Row 1021 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 1, 43, 25), 'ICU', 28, 55)
Row 1022 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 1, 43, 53), 'Maternity Ward', 23, 70)
Row 1023 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 1, 43, 59), 'Surgical Ward', 24, 67)
Row 1024 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 1, 44, 44), 'ICU', 28, 56)
Row 1025 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 1, 44, 45), 'Emergency Ward', 28, 62)
Row 1026 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 1, 45, 14), 'Maternity Ward', 24, 70)
Row 1027 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 1, 45, 19), 'Surgical Ward', 24, 67)
Row 1028 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 1, 46, 3), 'ICU', 28, 56)
Row 1029 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 1, 46, 7), 'Emergency Ward', 28, 62)
Row 1030 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 1, 46, 28), 'Maternity Ward', 23, 70)
Row 1031 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 1, 46, 40), 'Surgical Ward', 24, 67)

Row 1032 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 1, 47, 22), 'ICU', 28, 56)
Row 1033 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 1, 47, 28), 'Emergency Ward', 28, 62)
Row 1034 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 1, 47, 37), 'Maternity Ward', 24, 70)
Row 1035 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 1, 48), 'Surgical Ward', 25, 66)
Row 1036 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 1, 48, 42), 'ICU', 28, 56)
Row 1037 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 1, 48, 48), 'Emergency Ward', 28, 62)
Row 1038 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 1, 48, 58), 'Maternity Ward', 23, 70)
Row 1039 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 1, 49, 21), 'Surgical Ward', 24, 67)
Row 1040 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 1, 50, 1), 'ICU', 28, 56)
Row 1041 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 1, 50, 9), 'Emergency Ward', 28, 62)
Row 1042 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 1, 50, 18), 'Maternity Ward', 23, 70)
Row 1043 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 1, 50, 41), 'Surgical Ward', 25, 66)
Row 1044 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 1, 51, 20), 'ICU', 28, 56)
Row 1045 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 1, 51, 24), 'Emergency Ward', 28, 62)
Row 1046 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 1, 51, 38), 'Maternity Ward', 24, 70)
Row 1047 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 1, 52, 2), 'Surgical Ward', 24, 67)
Row 1048 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 1, 52, 33), 'Emergency Ward', 28, 62)
Row 1049 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 1, 52, 39), 'ICU', 28, 56)
Row 1050 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 1, 52, 58), 'Maternity Ward', 23, 70)
Row 1051 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 1, 53, 22), 'Surgical Ward', 24, 67)
Row 1052 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 1, 53, 51), 'ICU', 28, 56)
Row 1053 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 1, 53, 54), 'Emergency Ward', 27, 62)
Row 1054 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 1, 54, 18), 'Maternity Ward', 23, 70)
Row 1055 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 1, 54, 43), 'Surgical Ward', 24, 67)
Row 1056 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 1, 54, 59), 'ICU', 28, 56)
Row 1057 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 1, 55, 15), 'Emergency Ward', 28, 62)
Row 1058 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 1, 55, 39), 'Maternity Ward', 23, 70)
Row 1059 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 1, 55, 57), 'Surgical Ward', 24, 67)
Row 1060 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 1, 56, 18), 'ICU', 28, 56)
Row 1061 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 1, 56, 38), 'Emergency Ward', 28, 62)
Row 1062 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 1, 56, 59), 'Maternity Ward', 23, 70)
Row 1063 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 1, 57, 5), 'Surgical Ward', 25, 66)
Row 1064 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 1, 57, 38), 'ICU', 28, 56)
Row 1065 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 1, 57, 58), 'Emergency Ward', 27, 62)
Row 1066 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 1, 58, 20), 'Maternity Ward', 23, 70)
Row 1067 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 1, 58, 26), 'Surgical Ward', 24, 67)
Row 1068 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 1, 58, 57), 'ICU', 28, 56)
Row 1069 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 1, 59, 19), 'Emergency Ward', 27, 62)
Row 1070 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 1, 59, 40), 'Maternity Ward', 23, 70)
Row 1071 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 1, 59, 48), 'Surgical Ward', 25, 66)
Row 1072 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 2, 0, 15), 'ICU', 28, 56)
Row 1073 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 2, 0, 40), 'Emergency Ward', 28, 62)
Row 1074 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 2, 0, 53), 'Maternity Ward', 24, 70)
Row 1075 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 2, 1, 8), 'Surgical Ward', 24, 67)
Row 1076 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 2, 1, 35), 'ICU', 28, 56)
Row 1077 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 2, 2, 1), 'Emergency Ward', 28, 62)
Row 1078 is Updated!!!

INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 2, 2, 2), 'Maternity Ward', 23, 70)
Row 1079 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 2, 2, 28), 'Surgical Ward', 24, 67)
Row 1080 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 2, 2, 54), 'ICU', 28, 56)
Row 1081 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 2, 3, 22), 'Emergency Ward', 27, 62)
Row 1082 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 2, 3, 23), 'Maternity Ward', 24, 70)
Row 1083 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 2, 3, 48), 'Surgical Ward', 24, 67)
Row 1084 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 2, 4, 13), 'ICU', 28, 56)
Row 1085 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 2, 4, 43), 'Maternity Ward', 24, 70)
Row 1086 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 2, 4, 44), 'Emergency Ward', 28, 62)
Row 1087 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 2, 5, 8), 'Surgical Ward', 24, 67)
Row 1088 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 2, 5, 32), 'ICU', 28, 56)
Row 1089 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 2, 5, 58), 'Emergency Ward', 27, 62)
Row 1090 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 2, 6, 3), 'Maternity Ward', 24, 70)
Row 1091 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 2, 6, 29), 'Surgical Ward', 24, 67)
Row 1092 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 2, 6, 51), 'ICU', 28, 56)
Row 1093 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 2, 7, 8), 'Emergency Ward', 27, 62)
Row 1094 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 2, 7, 24), 'Maternity Ward', 23, 70)
Row 1095 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 2, 7, 49), 'Surgical Ward', 25, 66)
Row 1096 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 2, 8, 3), 'ICU', 28, 56)
Row 1097 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 2, 8, 28), 'Emergency Ward', 27, 62)
Row 1098 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 2, 8, 44), 'Maternity Ward', 23, 70)
Row 1099 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 2, 9, 10), 'Surgical Ward', 24, 67)
Row 1100 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 2, 9, 11), 'ICU', 28, 56)
Row 1101 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 2, 9, 49), 'Emergency Ward', 27, 62)
Row 1102 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 2, 10, 5), 'Maternity Ward', 23, 70)
Row 1103 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 2, 10, 23), 'Surgical Ward', 24, 67)
Row 1104 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 2, 10, 30), 'ICU', 28, 56)
Row 1105 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 2, 11, 10), 'Emergency Ward', 27, 62)
Row 1106 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 2, 11, 25), 'Maternity Ward', 24, 70)
Row 1107 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 2, 11, 32), 'Surgical Ward', 24, 67)
Row 1108 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 2, 11, 49), 'ICU', 28, 56)
Row 1109 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 2, 12, 31), 'Emergency Ward', 27, 62)
Row 1110 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 2, 12, 45), 'Maternity Ward', 23, 70)
Row 1111 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 2, 12, 52), 'Surgical Ward', 24, 67)
Row 1112 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 2, 13, 8), 'ICU', 28, 56)
Row 1113 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 2, 13, 53), 'Emergency Ward', 28, 62)
Row 1114 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 2, 14, 7), 'Maternity Ward', 23, 70)
Row 1115 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 2, 14, 13), 'Surgical Ward', 24, 67)
Row 1116 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 2, 14, 28), 'ICU', 28, 56)
Row 1117 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 2, 15, 14), 'Emergency Ward', 28, 62)
Row 1118 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 2, 15, 19), 'Maternity Ward', 23, 70)
Row 1119 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 2, 15, 33), 'Surgical Ward', 24, 67)
Row 1120 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 2, 15, 48), 'ICU', 28, 56)
Row 1121 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 2, 16, 28), 'Maternity Ward', 23, 70)
Row 1122 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 2, 16, 35), 'Emergency Ward', 27, 62)
Row 1123 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 2, 16, 54), 'Surgical Ward', 24, 67)
Row 1124 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 2, 17, 6), 'ICU', 28, 56)

Row 1125 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 2, 17, 49), 'Maternity Ward', 23, 70)
Row 1126 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 2, 17, 57), 'Emergency Ward', 27, 62)
Row 1127 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 2, 18, 14), 'Surgical Ward', 24, 67)
Row 1128 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 2, 18, 25), 'ICU', 28, 56)
Row 1129 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 2, 19, 9), 'Maternity Ward', 23, 70)
Row 1130 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 2, 19, 18), 'Emergency Ward', 27, 62)
Row 1131 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 2, 19, 35), 'Surgical Ward', 25, 66)
Row 1132 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 2, 19, 44), 'ICU', 28, 56)
Row 1133 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 2, 20, 29), 'Maternity Ward', 24, 70)
Row 1134 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 2, 20, 31), 'Emergency Ward', 27, 62)
Row 1135 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 2, 20, 55), 'Surgical Ward', 24, 67)
Row 1136 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 2, 21, 3), 'ICU', 25, 54)
Row 1137 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 2, 21, 41), 'Emergency Ward', 27, 62)
Row 1138 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 2, 21, 51), 'Maternity Ward', 23, 70)
Row 1139 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 2, 22, 16), 'ICU', 25, 54)
Row 1140 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 2, 22, 18), 'Surgical Ward', 24, 67)
Row 1141 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 2, 23, 2), 'Emergency Ward', 27, 62)
Row 1142 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 2, 23, 10), 'Maternity Ward', 23, 70)
Row 1143 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 2, 23, 23), 'ICU', 28, 56)
Row 1144 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 2, 23, 38), 'Surgical Ward', 24, 67)
Row 1145 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 2, 24, 23), 'Emergency Ward', 27, 62)
Row 1146 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 2, 24, 31), 'Maternity Ward', 24, 70)
Row 1147 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 2, 24, 42), 'ICU', 28, 56)
Row 1148 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 2, 24, 50), 'Surgical Ward', 25, 66)
Row 1149 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 2, 25, 44), 'Emergency Ward', 27, 62)
Row 1150 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 2, 25, 51), 'Maternity Ward', 24, 70)
Row 1151 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 2, 25, 59), 'Surgical Ward', 24, 67)
Row 1152 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 2, 26, 1), 'ICU', 28, 56)
Row 1153 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 2, 27, 5), 'Emergency Ward', 27, 62)
Row 1154 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 2, 27, 11), 'Maternity Ward', 24, 70)
Row 1155 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 2, 27, 19), 'Surgical Ward', 24, 67)
Row 1156 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 2, 27, 20), 'ICU', 28, 56)
Row 1157 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 2, 28, 28), 'Emergency Ward', 27, 62)
Row 1158 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 2, 28, 32), 'Maternity Ward', 23, 70)
Row 1159 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 2, 28, 40), 'ICU', 28, 56)
Row 1160 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 2, 29, 45), 'Maternity Ward', 23, 70)
Row 1161 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 2, 29, 48), 'Emergency Ward', 27, 62)
Row 1162 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 2, 29, 59), 'ICU', 28, 56)
Row 1163 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 2, 30), 'Surgical Ward', 24, 67)
Row 1164 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 2, 30, 54), 'Maternity Ward', 23, 70)
Row 1165 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 2, 31, 9), 'Emergency Ward', 27, 62)
Row 1166 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 2, 31, 18), 'ICU', 28, 56)
Row 1167 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 2, 31, 21), 'Surgical Ward', 24, 67)
Row 1168 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 2, 32, 15), 'Maternity Ward', 23, 70)
Row 1169 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 2, 32, 30), 'Emergency Ward', 28, 62)
Row 1170 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 2, 32, 38), 'ICU', 28, 56)
Row 1171 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 2, 32, 41), 'Surgical Ward', 24, 67)
Row 1172 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 2, 33, 37), 'Maternity Ward', 23, 70)

Row 1173 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 2, 33, 51), 'Emergency Ward', 27, 62)
Row 1174 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 2, 33, 58), 'ICU', 28, 56)
Row 1175 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 2, 34, 2), 'Surgical Ward', 24, 67)
Row 1176 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 2, 34, 55), 'Maternity Ward', 24, 70)
Row 1177 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 2, 35, 5), 'Emergency Ward', 27, 62)
Row 1178 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 2, 35, 15), 'ICU', 28, 56)
Row 1179 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 2, 35, 22), 'Surgical Ward', 24, 67)
Row 1180 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 2, 36, 15), 'Emergency Ward', 27, 62)
Row 1181 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 2, 36, 17), 'Maternity Ward', 24, 70)
Row 1182 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 2, 36, 28), 'ICU', 28, 56)
Row 1183 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 2, 36, 42), 'Surgical Ward', 25, 66)
Row 1184 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 2, 37, 35), 'ICU', 28, 56)
Row 1185 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 2, 37, 38), 'Emergency Ward', 27, 62)
Row 1186 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 2, 37, 39), 'Maternity Ward', 23, 70)
Row 1187 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 2, 38, 3), 'Surgical Ward', 25, 66)
Row 1188 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 2, 38, 55), 'ICU', 28, 56)
Row 1189 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 2, 38, 58), 'Maternity Ward', 23, 70)
Row 1190 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 2, 38, 59), 'Emergency Ward', 27, 62)
Row 1191 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 2, 39, 18), 'Surgical Ward', 24, 67)
Row 1192 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 2, 40, 14), 'ICU', 28, 56)
Row 1193 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 2, 40, 18), 'Maternity Ward', 23, 70)
Row 1194 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 2, 40, 19), 'Emergency Ward', 27, 62)
Row 1195 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 2, 40, 25), 'Surgical Ward', 24, 67)
Row 1196 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 2, 41, 33), 'ICU', 28, 56)
Row 1197 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 2, 41, 38), 'Maternity Ward', 23, 70)
Row 1198 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 2, 41, 39), 'Emergency Ward', 28, 62)
Row 1199 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 2, 41, 47), 'Surgical Ward', 24, 67)
Row 1200 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 2, 42, 52), 'ICU', 28, 56)
Row 1201 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 2, 42, 58), 'Maternity Ward', 23, 70)
Row 1202 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 2, 43), 'Emergency Ward', 28, 62)
Row 1203 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 2, 43, 8), 'Surgical Ward', 24, 67)
Row 1204 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 2, 44, 12), 'ICU', 28, 56)
Row 1205 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 2, 44, 13), 'Maternity Ward', 24, 70)
Row 1206 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 2, 44, 22), 'Emergency Ward', 27, 62)
Row 1207 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 2, 44, 28), 'Surgical Ward', 24, 67)
Row 1208 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 2, 45, 20), 'Maternity Ward', 23, 70)
Row 1209 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 2, 45, 30), 'ICU', 28, 56)
Row 1210 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 2, 45, 43), 'Emergency Ward', 27, 62)
Row 1211 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 2, 45, 48), 'Surgical Ward', 25, 66)
Row 1212 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 2, 46, 41), 'Maternity Ward', 23, 70)
Row 1213 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 2, 46, 49), 'ICU', 28, 56)
Row 1214 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 2, 47, 4), 'Emergency Ward', 27, 62)
Row 1215 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 2, 47, 8), 'Surgical Ward', 24, 67)
Row 1216 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 2, 48, 1), 'Maternity Ward', 23, 70)
Row 1217 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 2, 48, 9), 'ICU', 28, 56)
Row 1218 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 2, 48, 25), 'Emergency Ward', 27, 62)

Row 1219 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 2, 48, 28), 'Surgical Ward', 25, 66)
Row 1220 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 2, 49, 22), 'Maternity Ward', 24, 70)
Row 1221 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 2, 49, 28), 'ICU', 28, 56)
Row 1222 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 2, 49, 39), 'Emergency Ward', 27, 62)
Row 1223 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 2, 49, 49), 'Surgical Ward', 25, 66)
Row 1224 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 2, 50, 40), 'ICU', 25, 54)
Row 1225 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 2, 50, 42), 'Maternity Ward', 23, 70)
Row 1226 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 2, 50, 49), 'Emergency Ward', 27, 62)
Row 1227 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 2, 51, 9), 'Surgical Ward', 24, 67)
Row 1228 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 2, 51, 48), 'ICU', 28, 56)
Row 1229 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 2, 52, 3), 'Maternity Ward', 23, 70)
Row 1230 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 2, 52, 10), 'Emergency Ward', 27, 62)
Row 1231 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 2, 52, 30), 'Surgical Ward', 24, 67)
Row 1232 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 2, 53, 8), 'ICU', 28, 56)
Row 1233 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 2, 53, 23), 'Maternity Ward', 23, 70)
Row 1234 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 2, 53, 31), 'Emergency Ward', 27, 62)
Row 1235 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 2, 53, 43), 'Surgical Ward', 24, 67)
Row 1236 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 2, 54, 26), 'ICU', 28, 56)
Row 1237 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 2, 54, 43), 'Maternity Ward', 23, 70)
Row 1238 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 2, 54, 52), 'Emergency Ward', 27, 62)
Row 1239 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 2, 55, 45), 'ICU', 28, 56)
Row 1240 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 2, 56, 4), 'Maternity Ward', 24, 70)
Row 1241 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 2, 56, 13), 'Surgical Ward', 24, 67)
Row 1242 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 2, 56, 14), 'Emergency Ward', 27, 62)
Row 1243 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 2, 57, 4), 'ICU', 28, 56)
Row 1244 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 2, 57, 24), 'Maternity Ward', 23, 70)
Row 1245 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 2, 57, 33), 'Surgical Ward', 24, 67)
Row 1246 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 2, 57, 34), 'Emergency Ward', 27, 62)
Row 1247 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 2, 58, 24), 'ICU', 28, 55)
Row 1248 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 2, 58, 38), 'Maternity Ward', 23, 70)
Row 1249 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 2, 58, 54), 'Surgical Ward', 24, 67)
Row 1250 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 2, 58, 56), 'Emergency Ward', 27, 62)
Row 1251 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 2, 59, 42), 'ICU', 28, 56)
Row 1252 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 2, 59, 48), 'Maternity Ward', 24, 70)
Row 1253 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 3, 0, 14), 'Surgical Ward', 24, 67)
Row 1254 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 3, 0, 18), 'Emergency Ward', 27, 62)
Row 1255 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 3, 1, 2), 'ICU', 28, 56)
Row 1256 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 3, 1, 8), 'Maternity Ward', 23, 70)
Row 1257 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 3, 1, 35), 'Surgical Ward', 24, 67)
Row 1258 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 3, 1, 39), 'Emergency Ward', 27, 62)
Row 1259 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 3, 2, 21), 'ICU', 28, 56)
Row 1260 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 3, 2, 28), 'Maternity Ward', 24, 70)
Row 1261 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 3, 2, 55), 'Surgical Ward', 24, 67)
Row 1262 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 3, 2, 59), 'Emergency Ward', 27, 62)
Row 1263 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 3, 3, 40), 'ICU', 28, 55)
Row 1264 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 3, 3, 48), 'Maternity Ward', 24, 70)

Row 1265 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 3, 4, 13), 'Emergency Ward', 27, 62)
Row 1266 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 3, 4, 15), 'Surgical Ward', 24, 67)
Row 1267 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 3, 4, 52), 'ICU', 28, 55)
Row 1268 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 3, 5, 8), 'Maternity Ward', 24, 70)
Row 1269 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 3, 5, 23), 'Emergency Ward', 27, 62)
Row 1270 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 3, 5, 36), 'Surgical Ward', 24, 67)
Row 1271 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 3, 6), 'ICU', 28, 56)
Row 1272 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 3, 6, 29), 'Maternity Ward', 23, 70)
Row 1273 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 3, 6, 44), 'Emergency Ward', 27, 62)
Row 1274 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 3, 6, 58), 'Surgical Ward', 24, 67)
Row 1275 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 3, 7, 19), 'ICU', 28, 56)
Row 1276 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 3, 7, 49), 'Maternity Ward', 23, 70)
Row 1277 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 3, 8, 5), 'Emergency Ward', 27, 62)
Row 1278 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 3, 8, 10), 'Surgical Ward', 24, 67)
Row 1279 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 3, 8, 38), 'ICU', 28, 56)
Row 1280 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 3, 9, 9), 'Maternity Ward', 23, 70)
Row 1281 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 3, 9, 19), 'Surgical Ward', 24, 67)
Row 1282 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 3, 9, 26), 'Emergency Ward', 27, 62)
Row 1283 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 3, 9, 58), 'ICU', 28, 56)
Row 1284 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 3, 10, 30), 'Maternity Ward', 23, 70)
Row 1285 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 3, 10, 39), 'Surgical Ward', 24, 67)
Row 1286 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 3, 10, 48), 'Emergency Ward', 27, 62)
Row 1287 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 3, 11, 17), 'ICU', 28, 56)
Row 1288 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 3, 11, 50), 'Maternity Ward', 23, 70)
Row 1289 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 3, 12), 'Surgical Ward', 24, 67)
Row 1290 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 3, 12, 8), 'Emergency Ward', 27, 62)
Row 1291 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 3, 12, 36), 'ICU', 28, 56)
Row 1292 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 3, 13, 4), 'Maternity Ward', 23, 70)
Row 1293 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 3, 13, 20), 'Surgical Ward', 24, 67)
Row 1294 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 3, 13, 29), 'Emergency Ward', 27, 62)
Row 1295 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 3, 13, 54), 'ICU', 28, 56)
Row 1296 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 3, 14, 12), 'Maternity Ward', 24, 70)
Row 1297 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 3, 14, 41), 'Surgical Ward', 24, 67)
Row 1298 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 3, 14, 50), 'Emergency Ward', 27, 62)
Row 1299 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 3, 15, 14), 'ICU', 28, 55)
Row 1300 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 3, 15, 33), 'Maternity Ward', 24, 70)
Row 1301 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 3, 16, 1), 'Surgical Ward', 24, 67)
Row 1302 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 3, 16, 12), 'Emergency Ward', 27, 62)
Row 1303 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 3, 16, 33), 'ICU', 25, 54)
Row 1304 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 3, 16, 53), 'Maternity Ward', 23, 70)
Row 1305 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 3, 17, 22), 'Surgical Ward', 24, 67)
Row 1306 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 3, 17, 33), 'Emergency Ward', 27, 62)
Row 1307 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 3, 17, 52), 'ICU', 28, 55)
Row 1308 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 3, 18, 14), 'Maternity Ward', 23, 70)
Row 1309 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 3, 18, 42), 'Surgical Ward', 24, 67)
Row 1310 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 3, 18, 48), 'Emergency Ward', 27, 62)
Row 1311 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 3, 19, 4), 'ICU', 28, 56)

Row 1312 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 3, 19, 34), 'Maternity Ward', 24, 70)
Row 1313 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 3, 19, 58), 'Emergency Ward', 27, 62)
Row 1314 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 3, 20, 3), 'Surgical Ward', 24, 67)
Row 1315 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 3, 20, 12), 'ICU', 28, 55)
Row 1316 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 3, 20, 54), 'Maternity Ward', 24, 70)
Row 1317 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 3, 21, 18), 'Emergency Ward', 27, 62)
Row 1318 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 3, 21, 23), 'Surgical Ward', 24, 67)
Row 1319 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 3, 21, 31), 'ICU', 28, 55)
Row 1320 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 3, 22, 15), 'Maternity Ward', 23, 70)
Row 1321 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 3, 22, 39), 'Surgical Ward', 24, 67)
Row 1322 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 3, 22, 41), 'Emergency Ward', 27, 62)
Row 1323 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 3, 22, 50), 'ICU', 28, 55)
Row 1324 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 3, 23, 35), 'Maternity Ward', 23, 69)
Row 1325 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 3, 23, 46), 'Surgical Ward', 24, 67)
Row 1326 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 3, 24), 'Emergency Ward', 27, 62)
Row 1327 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 3, 24, 9), 'ICU', 28, 55)
Row 1328 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 3, 24, 56), 'Maternity Ward', 24, 70)
Row 1329 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 3, 25, 6), 'Surgical Ward', 24, 67)
Row 1330 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 3, 25, 21), 'Emergency Ward', 27, 62)
Row 1331 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 3, 25, 28), 'ICU', 28, 55)
Row 1332 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 3, 26, 16), 'Maternity Ward', 24, 70)
Row 1333 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 3, 26, 28), 'Surgical Ward', 24, 67)
Row 1334 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 3, 26, 42), 'Emergency Ward', 27, 62)
Row 1335 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 3, 26, 48), 'ICU', 28, 55)
Row 1336 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 3, 27, 30), 'Maternity Ward', 23, 70)
Row 1337 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 3, 27, 48), 'Surgical Ward', 24, 67)
Row 1338 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 3, 28, 3), 'Emergency Ward', 27, 62)
Row 1339 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 3, 28, 8), 'ICU', 28, 55)
Row 1340 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 3, 28, 38), 'Maternity Ward', 23, 70)
Row 1341 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 3, 29, 8), 'Surgical Ward', 24, 67)
Row 1342 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 3, 29, 24), 'Emergency Ward', 27, 62)
Row 1343 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 3, 29, 26), 'ICU', 25, 53)
Row 1344 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 3, 29, 59), 'Maternity Ward', 23, 70)
Row 1345 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 3, 30, 28), 'Surgical Ward', 24, 67)
Row 1346 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 3, 30, 45), 'ICU', 28, 55)
Row 1347 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 3, 30, 46), 'Emergency Ward', 27, 62)
Row 1348 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 3, 31, 19), 'Maternity Ward', 24, 70)
Row 1349 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 3, 31, 49), 'Surgical Ward', 24, 67)
Row 1350 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 3, 32, 4), 'ICU', 28, 55)
Row 1351 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 3, 32, 8), 'Emergency Ward', 27, 62)
Row 1352 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 3, 32, 40), 'Maternity Ward', 23, 70)
Row 1353 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 3, 33, 9), 'Surgical Ward', 24, 67)
Row 1354 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 3, 33, 16), 'ICU', 28, 55)
Row 1355 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 3, 33, 21), 'Emergency Ward', 27, 62)
Row 1356 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 3, 34), 'Maternity Ward', 23, 70)
Row 1357 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 3, 34, 24), 'ICU', 28, 55)
Row 1358 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 3, 34, 30), 'Surgical Ward', 24, 67)

Row 1359 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 3, 34, 31), 'Emergency Ward', 27, 62)
Row 1360 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 3, 35, 21), 'Maternity Ward', 23, 70)
Row 1361 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 3, 35, 43), 'ICU', 28, 55)
Row 1362 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 3, 35, 50), 'Surgical Ward', 24, 67)
Row 1363 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 3, 35, 52), 'Emergency Ward', 27, 62)
Row 1364 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 3, 36, 41), 'Maternity Ward', 23, 70)
Row 1365 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 3, 37, 2), 'ICU', 25, 53)
Row 1366 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 3, 37, 3), 'Surgical Ward', 24, 67)
Row 1367 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 3, 37, 13), 'Emergency Ward', 27, 62)
Row 1368 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 3, 38, 1), 'Maternity Ward', 24, 69)
Row 1369 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 3, 38, 12), 'Surgical Ward', 24, 67)
Row 1370 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 3, 38, 21), 'ICU', 28, 55)
Row 1371 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 3, 38, 34), 'Emergency Ward', 27, 62)
Row 1372 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 3, 39, 22), 'Maternity Ward', 24, 70)
Row 1373 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 3, 39, 33), 'Surgical Ward', 24, 67)
Row 1374 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 3, 39, 40), 'ICU', 28, 55)
Row 1375 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 3, 39, 55), 'Emergency Ward', 27, 62)
Row 1376 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 3, 40, 42), 'Maternity Ward', 23, 70)
Row 1377 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 3, 40, 53), 'Surgical Ward', 24, 67)
Row 1378 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 3, 41), 'ICU', 28, 55)
Row 1379 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 3, 41, 16), 'Emergency Ward', 27, 62)
Row 1380 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 3, 41, 56), 'Maternity Ward', 24, 70)
Row 1381 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 3, 42, 14), 'Surgical Ward', 24, 67)
Row 1382 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 3, 42, 19), 'ICU', 28, 55)
Row 1383 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 3, 42, 38), 'Emergency Ward', 27, 62)
Row 1384 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 3, 43, 5), 'Maternity Ward', 23, 70)
Row 1385 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 3, 43, 34), 'Surgical Ward', 24, 67)
Row 1386 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 3, 43, 38), 'ICU', 28, 55)
Row 1387 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 3, 43, 58), 'Emergency Ward', 27, 62)
Row 1388 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 3, 44, 25), 'Maternity Ward', 23, 70)
Row 1389 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 3, 44, 55), 'Surgical Ward', 24, 67)
Row 1390 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 3, 44, 58), 'ICU', 25, 53)
Row 1391 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 3, 45, 20), 'Emergency Ward', 27, 63)
Row 1392 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 3, 45, 45), 'Maternity Ward', 24, 70)
Row 1393 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 3, 46, 16), 'Surgical Ward', 24, 67)
Row 1394 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 3, 46, 18), 'ICU', 28, 54)
Row 1395 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 3, 46, 41), 'Emergency Ward', 27, 62)
Row 1396 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 3, 47, 6), 'Maternity Ward', 24, 70)
Row 1397 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 3, 47, 28), 'ICU', 28, 55)
Row 1398 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 3, 47, 36), 'Surgical Ward', 24, 67)
Row 1399 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 3, 47, 55), 'Emergency Ward', 27, 62)
Row 1400 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 3, 48, 28), 'Maternity Ward', 23, 70)
Row 1401 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 3, 48, 36), 'ICU', 28, 55)
Row 1402 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 3, 48, 58), 'Surgical Ward', 24, 67)
Row 1403 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 3, 49, 4), 'Emergency Ward', 27, 62)
Row 1404 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 3, 49, 48), 'Maternity Ward', 23, 70)
Row 1405 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 3, 49, 55), 'ICU', 28, 55)

Row 1406 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 3, 50, 18), 'Surgical Ward', 24, 67)
Row 1407 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 3, 50, 26), 'Emergency Ward', 27, 62)
Row 1408 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 3, 51, 8), 'Maternity Ward', 24, 70)
Row 1409 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 3, 51, 14), 'ICU', 28, 55)
Row 1410 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 3, 51, 30), 'Surgical Ward', 24, 67)
Row 1411 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 3, 51, 48), 'Emergency Ward', 27, 62)
Row 1412 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 3, 52, 28), 'Maternity Ward', 24, 70)
Row 1413 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 3, 52, 33), 'ICU', 28, 54)
Row 1414 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 3, 52, 39), 'Surgical Ward', 24, 67)
Row 1415 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 3, 53, 8), 'Emergency Ward', 27, 62)
Row 1416 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 3, 53, 48), 'Maternity Ward', 23, 70)
Row 1417 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 3, 53, 52), 'ICU', 28, 54)
Row 1418 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 3, 53, 59), 'Surgical Ward', 24, 67)
Row 1419 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 3, 54, 29), 'Emergency Ward', 27, 62)
Row 1420 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 3, 55, 8), 'Maternity Ward', 24, 70)
Row 1421 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 3, 55, 12), 'ICU', 25, 52)
Row 1422 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 3, 55, 20), 'Surgical Ward', 24, 67)
Row 1423 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 3, 55, 50), 'Emergency Ward', 27, 62)
Row 1424 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 3, 56, 22), 'Maternity Ward', 24, 69)
Row 1425 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 3, 56, 31), 'ICU', 28, 54)
Row 1426 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 3, 56, 41), 'Surgical Ward', 24, 67)
Row 1427 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 3, 57, 31), 'Maternity Ward', 23, 70)
Row 1428 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 3, 57, 50), 'ICU', 28, 54)
Row 1429 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 3, 58, 1), 'Surgical Ward', 24, 67)
Row 1430 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 3, 58, 32), 'Emergency Ward', 27, 62)
Row 1431 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 3, 58, 51), 'Maternity Ward', 23, 70)
Row 1432 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 3, 59, 9), 'ICU', 28, 54)
Row 1433 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 3, 59, 22), 'Surgical Ward', 24, 67)
Row 1434 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 3, 59, 53), 'Emergency Ward', 27, 62)
Row 1435 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 4, 0, 12), 'Maternity Ward', 23, 70)
Row 1436 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 4, 0, 28), 'ICU', 28, 54)
Row 1437 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 4, 0, 42), 'Surgical Ward', 24, 67)
Row 1438 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 4, 1, 15), 'Emergency Ward', 27, 62)
Row 1439 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 4, 1, 33), 'Maternity Ward', 23, 70)
Row 1440 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 4, 1, 40), 'ICU', 28, 54)
Row 1441 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 4, 2, 2), 'Surgical Ward', 24, 67)
Row 1442 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 4, 2, 29), 'Emergency Ward', 27, 62)
Row 1443 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 4, 2, 48), 'ICU', 25, 52)
Row 1444 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 4, 2, 52), 'Maternity Ward', 23, 70)
Row 1445 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 4, 3, 23), 'Surgical Ward', 24, 67)
Row 1446 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 4, 3, 39), 'Emergency Ward', 27, 62)
Row 1447 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 4, 4, 8), 'ICU', 28, 54)
Row 1448 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 4, 4, 13), 'Maternity Ward', 23, 70)
Row 1449 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 4, 4, 43), 'Surgical Ward', 24, 67)
Row 1450 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 4, 4, 59), 'Emergency Ward', 27, 62)
Row 1451 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 4, 5, 28), 'ICU', 28, 54)
Row 1452 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 4, 5, 33), 'Maternity Ward', 24, 70)

Row 1453 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 4, 5, 58), 'Surgical Ward', 24, 67)
Row 1454 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 4, 6, 21), 'Emergency Ward', 27, 62)
Row 1455 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 4, 6, 45), 'ICU', 28, 54)
Row 1456 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 4, 6, 54), 'Maternity Ward', 23, 70)
Row 1457 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 4, 7, 6), 'Surgical Ward', 24, 67)
Row 1458 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 4, 7, 42), 'Emergency Ward', 27, 62)
Row 1459 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 4, 8, 4), 'ICU', 28, 54)
Row 1460 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 4, 8, 14), 'Maternity Ward', 23, 70)
Row 1461 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 4, 8, 26), 'Surgical Ward', 24, 67)
Row 1462 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 4, 9, 3), 'Emergency Ward', 27, 62)
Row 1463 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 4, 9, 24), 'ICU', 28, 54)
Row 1464 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 4, 9, 35), 'Maternity Ward', 23, 70)
Row 1465 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 4, 9, 48), 'Surgical Ward', 24, 67)
Row 1466 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 4, 10, 25), 'Emergency Ward', 27, 62)
Row 1467 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 4, 10, 43), 'ICU', 28, 54)
Row 1468 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 4, 10, 48), 'Maternity Ward', 23, 70)
Row 1469 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 4, 11, 8), 'Surgical Ward', 24, 67)
Row 1470 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 4, 11, 45), 'Emergency Ward', 27, 62)
Row 1471 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 4, 11, 58), 'Maternity Ward', 23, 70)
Row 1472 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 4, 12, 2), 'ICU', 28, 54)
Row 1473 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 4, 12, 28), 'Surgical Ward', 24, 67)
Row 1474 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 4, 13, 8), 'Emergency Ward', 27, 62)
Row 1475 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 4, 13, 18), 'Maternity Ward', 23, 70)
Row 1476 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 4, 13, 21), 'ICU', 28, 54)
Row 1477 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 4, 13, 48), 'Surgical Ward', 24, 67)
Row 1478 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 4, 14, 28), 'Emergency Ward', 27, 62)
Row 1479 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 4, 14, 38), 'Maternity Ward', 23, 70)
Row 1480 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 4, 14, 40), 'ICU', 28, 54)
Row 1481 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 4, 15, 9), 'Surgical Ward', 24, 67)
Row 1482 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 4, 15, 49), 'Emergency Ward', 27, 62)
Row 1483 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 4, 15, 52), 'ICU', 28, 54)
Row 1484 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 4, 15, 58), 'Maternity Ward', 24, 70)
Row 1485 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 4, 16, 29), 'Surgical Ward', 24, 67)
Row 1486 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 4, 17), 'ICU', 28, 54)
Row 1487 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 4, 17, 3), 'Emergency Ward', 27, 62)
Row 1488 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 4, 17, 19), 'Maternity Ward', 23, 70)
Row 1489 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 4, 17, 50), 'Surgical Ward', 24, 67)
Row 1490 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 4, 18, 12), 'Emergency Ward', 27, 62)
Row 1491 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 4, 18, 19), 'ICU', 28, 54)
Row 1492 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 4, 18, 39), 'Maternity Ward', 24, 70)
Row 1493 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 4, 19, 10), 'Surgical Ward', 24, 67)
Row 1494 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 4, 19, 33), 'Emergency Ward', 27, 62)
Row 1495 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 4, 19, 38), 'ICU', 25, 51)
Row 1496 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 4, 19, 59), 'Maternity Ward', 23, 70)
Row 1497 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 4, 20, 23), 'Surgical Ward', 24, 67)
Row 1498 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 4, 20, 54), 'Emergency Ward', 27, 62)
Row 1499 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 4, 20, 58), 'ICU', 28, 54)

Row 1500 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 4, 21, 20), 'Maternity Ward', 23, 70)
Row 1501 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 4, 21, 32), 'Surgical Ward', 24, 67)
Row 1502 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 4, 22, 16), 'Emergency Ward', 27, 62)
Row 1503 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 4, 22, 18), 'ICU', 25, 51)
Row 1504 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 4, 22, 41), 'Maternity Ward', 23, 70)
Row 1505 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 4, 22, 53), 'Surgical Ward', 24, 67)
Row 1506 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 4, 23, 36), 'ICU', 28, 54)
Row 1507 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 4, 23, 38), 'Emergency Ward', 27, 62)
Row 1508 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 4, 24, 1), 'Maternity Ward', 23, 70)
Row 1509 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 4, 24, 13), 'Surgical Ward', 24, 67)
Row 1510 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 4, 24, 55), 'ICU', 28, 54)
Row 1511 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 4, 24, 58), 'Emergency Ward', 27, 62)
Row 1512 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 4, 25, 14), 'Maternity Ward', 23, 70)
Row 1513 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 4, 25, 34), 'Surgical Ward', 24, 67)
Row 1514 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 4, 26, 14), 'ICU', 28, 54)
Row 1515 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 4, 26, 19), 'Emergency Ward', 27, 62)
Row 1516 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 4, 26, 23), 'Maternity Ward', 23, 70)
Row 1517 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 4, 26, 54), 'Surgical Ward', 24, 67)
Row 1518 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 4, 27, 33), 'ICU', 28, 54)
Row 1519 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 4, 27, 35), 'Maternity Ward', 23, 70)
Row 1520 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 4, 27, 40), 'Emergency Ward', 27, 62)
Row 1521 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 4, 28, 15), 'Surgical Ward', 24, 67)
Row 1522 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 4, 28, 52), 'ICU', 28, 54)
Row 1523 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 4, 28, 55), 'Maternity Ward', 24, 70)
Row 1524 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 4, 29, 1), 'Emergency Ward', 27, 62)
Row 1525 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 4, 29, 35), 'Surgical Ward', 24, 67)
Row 1526 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 4, 30, 4), 'ICU', 28, 54)
Row 1527 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 4, 30, 15), 'Maternity Ward', 23, 70)
Row 1528 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 4, 30, 22), 'Emergency Ward', 27, 62)
Row 1529 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 4, 30, 56), 'Surgical Ward', 24, 67)
Row 1530 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 4, 31, 12), 'ICU', 25, 50)
Row 1531 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 4, 31, 36), 'Maternity Ward', 23, 70)
Row 1532 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 4, 31, 38), 'Emergency Ward', 27, 62)
Row 1533 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 4, 32, 18), 'Surgical Ward', 24, 67)
Row 1534 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 4, 32, 31), 'ICU', 28, 54)
Row 1535 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 4, 32, 48), 'Emergency Ward', 27, 62)
Row 1536 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 4, 32, 56), 'Maternity Ward', 23, 70)
Row 1537 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 4, 33, 38), 'Surgical Ward', 24, 67)
Row 1538 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 4, 33, 50), 'ICU', 28, 54)
Row 1539 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 4, 34, 8), 'Emergency Ward', 27, 62)
Row 1540 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 4, 34, 18), 'Maternity Ward', 23, 70)
Row 1541 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 4, 34, 50), 'Surgical Ward', 24, 67)
Row 1542 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 4, 35, 10), 'ICU', 28, 54)
Row 1543 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 4, 35, 29), 'Emergency Ward', 27, 62)
Row 1544 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 4, 35, 38), 'Maternity Ward', 23, 70)
Row 1545 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 4, 35, 59), 'Surgical Ward', 24, 67)

Row 1546 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 4, 36, 30), 'ICU', 28, 54)
Row 1547 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 4, 36, 50), 'Emergency Ward', 27, 62)
Row 1548 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 4, 36, 58), 'Maternity Ward', 23, 70)
Row 1549 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 4, 37, 20), 'Surgical Ward', 24, 67)
Row 1550 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 4, 37, 48), 'ICU', 28, 54)
Row 1551 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 4, 38, 11), 'Emergency Ward', 27, 62)
Row 1552 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 4, 38, 18), 'Maternity Ward', 23, 70)
Row 1553 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 4, 38, 40), 'Surgical Ward', 24, 67)
Row 1554 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 4, 39, 8), 'ICU', 28, 54)
Row 1555 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 4, 39, 31), 'Maternity Ward', 24, 70)
Row 1556 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 4, 39, 32), 'Emergency Ward', 27, 62)
Row 1557 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 4, 40, 1), 'Surgical Ward', 24, 67)
Row 1558 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 4, 40, 26), 'ICU', 28, 54)
Row 1559 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 4, 40, 40), 'Maternity Ward', 23, 70)
Row 1560 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 4, 40, 53), 'Emergency Ward', 27, 62)
Row 1561 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 4, 41, 45), 'ICU', 28, 54)
Row 1562 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 4, 42, 1), 'Maternity Ward', 23, 70)
Row 1563 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 4, 42, 14), 'Emergency Ward', 27, 62)
Row 1564 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 4, 42, 42), 'Surgical Ward', 24, 67)
Row 1565 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 4, 43, 4), 'ICU', 28, 54)
Row 1566 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 4, 43, 21), 'Maternity Ward', 24, 70)
Row 1567 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 4, 43, 35), 'Emergency Ward', 27, 62)
Row 1568 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 4, 44, 18), 'ICU', 28, 54)
Row 1569 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 4, 44, 41), 'Maternity Ward', 23, 70)
Row 1570 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 4, 44, 58), 'Emergency Ward', 27, 62)
Row 1571 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 4, 45, 22), 'Surgical Ward', 24, 67)
Row 1572 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 4, 45, 24), 'ICU', 28, 54)
Row 1573 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 4, 46, 2), 'Maternity Ward', 24, 70)
Row 1574 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 4, 46, 11), 'Emergency Ward', 27, 62)
Row 1575 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 4, 46, 43), 'Surgical Ward', 24, 67)
Row 1576 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 4, 46, 44), 'ICU', 28, 54)
Row 1577 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 4, 47, 20), 'Emergency Ward', 27, 62)
Row 1578 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 4, 47, 22), 'Maternity Ward', 24, 70)
Row 1579 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 4, 48, 3), 'ICU', 28, 54)
Row 1580 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 4, 48, 4), 'Surgical Ward', 24, 67)
Row 1581 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 4, 48, 41), 'Emergency Ward', 27, 62)
Row 1582 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 4, 48, 43), 'Maternity Ward', 23, 70)
Row 1583 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 4, 49, 18), 'Surgical Ward', 24, 67)
Row 1584 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 4, 49, 22), 'ICU', 28, 54)
Row 1585 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 4, 50, 4), 'Emergency Ward', 27, 62)
Row 1586 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 4, 50, 5), 'Maternity Ward', 23, 70)
Row 1587 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 4, 50, 26), 'Surgical Ward', 24, 67)
Row 1588 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 4, 50, 41), 'ICU', 28, 54)
Row 1589 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 4, 51, 23), 'Maternity Ward', 23, 70)
Row 1590 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 4, 51, 24), 'Emergency Ward', 27, 62)
Row 1591 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 4, 51, 48), 'Surgical Ward', 24, 67)

Row 1592 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 4, 52), 'ICU', 28, 54)
Row 1593 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 4, 52, 44), 'Maternity Ward', 24, 70)
Row 1594 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 4, 52, 45), 'Emergency Ward', 27, 62)
Row 1595 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 4, 53, 8), 'Surgical Ward', 24, 67)
Row 1596 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 4, 53, 19), 'ICU', 25, 50)
Row 1597 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 4, 53, 58), 'Maternity Ward', 23, 69)
Row 1598 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 4, 54, 6), 'Emergency Ward', 27, 62)
Row 1599 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 4, 54, 28), 'Surgical Ward', 24, 67)
Row 1600 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 4, 54, 38), 'ICU', 28, 54)
Row 1601 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 4, 55, 6), 'Maternity Ward', 23, 70)
Row 1602 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 4, 55, 28), 'Emergency Ward', 27, 62)
Row 1603 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 4, 55, 48), 'Surgical Ward', 24, 67)
Row 1604 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 4, 55, 58), 'ICU', 25, 50)
Row 1605 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 4, 56, 28), 'Maternity Ward', 23, 69)
Row 1606 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 4, 56, 48), 'Emergency Ward', 27, 62)
Row 1607 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 4, 57, 8), 'Surgical Ward', 24, 67)
Row 1608 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 4, 57, 18), 'ICU', 28, 54)
Row 1609 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 4, 57, 48), 'Maternity Ward', 23, 69)
Row 1610 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 4, 58, 9), 'Emergency Ward', 27, 62)
Row 1611 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 4, 58, 30), 'ICU', 28, 54)
Row 1612 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 4, 58, 31), 'Surgical Ward', 24, 67)
Row 1613 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 4, 59, 8), 'Maternity Ward', 23, 69)
Row 1614 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 4, 59, 30), 'Emergency Ward', 27, 62)
Row 1615 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 4, 59, 38), 'ICU', 28, 54)
Row 1616 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 4, 59, 49), 'Surgical Ward', 24, 67)
Row 1617 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 5, 0, 28), 'Maternity Ward', 23, 69)
Row 1618 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 5, 0, 45), 'Emergency Ward', 27, 62)
Row 1619 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 5, 0, 56), 'ICU', 28, 54)
Row 1620 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 5, 1, 10), 'Surgical Ward', 24, 67)
Row 1621 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 5, 1, 48), 'Maternity Ward', 23, 69)
Row 1622 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 5, 1, 54), 'Emergency Ward', 27, 62)
Row 1623 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 5, 2, 15), 'ICU', 28, 54)
Row 1624 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 5, 2, 30), 'Surgical Ward', 24, 67)
Row 1625 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 5, 3, 9), 'Maternity Ward', 23, 69)
Row 1626 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 5, 3, 15), 'Emergency Ward', 27, 62)
Row 1627 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 5, 3, 34), 'ICU', 28, 54)
Row 1628 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 5, 3, 44), 'Surgical Ward', 24, 67)
Row 1629 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 5, 4, 29), 'Maternity Ward', 23, 69)
Row 1630 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 5, 4, 38), 'Emergency Ward', 27, 62)
Row 1631 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 5, 4, 53), 'Surgical Ward', 24, 67)
Row 1632 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 5, 4, 54), 'ICU', 28, 54)
Row 1633 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 5, 5, 50), 'Maternity Ward', 23, 69)
Row 1634 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 5, 5, 58), 'Emergency Ward', 27, 62)
Row 1635 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 5, 6, 12), 'ICU', 28, 54)
Row 1636 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 5, 6, 13), 'Surgical Ward', 24, 67)
Row 1637 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 5, 7, 10), 'Maternity Ward', 24, 69)

Row 1638 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 5, 7, 19), 'Emergency Ward', 27, 62)
Row 1639 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 5, 7, 31), 'ICU', 28, 54)
Row 1640 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 5, 7, 34), 'Surgical Ward', 24, 67)
Row 1641 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 5, 8, 23), 'Maternity Ward', 23, 69)
Row 1642 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 5, 8, 40), 'Emergency Ward', 27, 62)
Row 1643 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 5, 8, 50), 'ICU', 28, 54)
Row 1644 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 5, 8, 54), 'Surgical Ward', 24, 67)
Row 1645 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 5, 9, 32), 'Maternity Ward', 23, 69)
Row 1646 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 5, 10, 1), 'Emergency Ward', 27, 62)
Row 1647 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 5, 10, 10), 'ICU', 28, 54)
Row 1648 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 5, 10, 14), 'Surgical Ward', 24, 67)
Row 1649 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 5, 10, 53), 'Maternity Ward', 24, 69)
Row 1650 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 5, 11, 22), 'Emergency Ward', 27, 62)
Row 1651 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 5, 11, 29), 'ICU', 28, 54)
Row 1652 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 5, 11, 35), 'Surgical Ward', 24, 67)
Row 1653 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 5, 12, 13), 'Maternity Ward', 23, 69)
Row 1654 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 5, 12, 41), 'ICU', 28, 54)
Row 1655 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 5, 12, 43), 'Emergency Ward', 27, 62)
Row 1656 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 5, 12, 55), 'Surgical Ward', 24, 67)
Row 1657 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 5, 13, 33), 'Maternity Ward', 23, 69)
Row 1658 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 5, 13, 49), 'ICU', 28, 54)
Row 1659 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 5, 14, 4), 'Emergency Ward', 27, 62)
Row 1660 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 5, 14, 16), 'Surgical Ward', 24, 67)
Row 1661 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 5, 14, 54), 'Maternity Ward', 24, 69)
Row 1662 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 5, 15, 9), 'ICU', 28, 54)
Row 1663 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 5, 15, 19), 'Emergency Ward', 27, 62)
Row 1664 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 5, 15, 36), 'Surgical Ward', 24, 67)
Row 1665 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 5, 16, 14), 'Maternity Ward', 24, 69)
Row 1666 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 5, 16, 28), 'ICU', 28, 53)
Row 1667 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 5, 16, 29), 'Emergency Ward', 27, 62)
Row 1668 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 5, 16, 58), 'Surgical Ward', 24, 67)
Row 1669 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 5, 17, 35), 'Maternity Ward', 23, 69)
Row 1670 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 5, 17, 46), 'ICU', 28, 53)
Row 1671 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 5, 17, 49), 'Emergency Ward', 27, 62)
Row 1672 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 5, 18, 10), 'Surgical Ward', 24, 67)
Row 1673 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 5, 18, 55), 'Maternity Ward', 23, 69)
Row 1674 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 5, 19, 5), 'ICU', 28, 53)
Row 1675 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 5, 19, 10), 'Emergency Ward', 27, 62)
Row 1676 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 5, 19, 19), 'Surgical Ward', 24, 67)
Row 1677 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 5, 20, 16), 'Maternity Ward', 23, 69)
Row 1678 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 5, 20, 24), 'ICU', 28, 53)
Row 1679 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 5, 20, 31), 'Emergency Ward', 27, 62)
Row 1680 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 5, 20, 40), 'Surgical Ward', 24, 67)
Row 1681 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 5, 21, 36), 'Maternity Ward', 23, 69)
Row 1682 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 5, 21, 43), 'ICU', 25, 49)
Row 1683 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 5, 21, 53), 'Emergency Ward', 27, 62)
Row 1684 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 5, 22), 'Surgical Ward', 24, 67)
Row 1685 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 5, 22, 49), 'Maternity Ward', 23, 69)

Row 1686 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 5, 23, 3), 'ICU', 28, 53)
Row 1687 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 5, 23, 14), 'Emergency Ward', 27, 62)
Row 1688 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 5, 23, 21), 'Surgical Ward', 24, 67)
Row 1689 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 5, 23, 58), 'Maternity Ward', 24, 69)
Row 1690 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 5, 24, 22), 'ICU', 28, 54)
Row 1691 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 5, 24, 35), 'Emergency Ward', 27, 62)
Row 1692 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 5, 24, 41), 'Surgical Ward', 24, 67)
Row 1693 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 5, 25, 19), 'Maternity Ward', 23, 69)
Row 1694 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 5, 25, 41), 'ICU', 28, 53)
Row 1695 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 5, 25, 58), 'Emergency Ward', 27, 62)
Row 1696 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 5, 26, 2), 'Surgical Ward', 24, 67)
Row 1697 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 5, 26, 39), 'Maternity Ward', 23, 69)
Row 1698 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 5, 26, 53), 'ICU', 28, 54)
Row 1699 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 5, 27, 18), 'Emergency Ward', 27, 62)
Row 1700 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 5, 27, 22), 'Surgical Ward', 24, 67)
Row 1701 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 5, 28), 'Maternity Ward', 24, 69)
Row 1702 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 5, 28, 1), 'ICU', 28, 53)
Row 1703 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 5, 28, 38), 'Emergency Ward', 27, 62)
Row 1704 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 5, 28, 43), 'Surgical Ward', 24, 67)
Row 1705 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 5, 29, 20), 'ICU', 25, 50)
Row 1706 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 5, 29, 21), 'Maternity Ward', 23, 69)
Row 1707 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 5, 29, 53), 'Emergency Ward', 27, 62)
Row 1708 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 5, 30, 3), 'Surgical Ward', 24, 67)
Row 1709 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 5, 30, 39), 'ICU', 28, 54)
Row 1710 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 5, 30, 40), 'Maternity Ward', 23, 69)
Row 1711 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 5, 31, 2), 'Emergency Ward', 27, 62)
Row 1712 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 5, 31, 23), 'Surgical Ward', 24, 67)
Row 1713 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 5, 31, 58), 'ICU', 28, 53)
Row 1714 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 5, 32, 1), 'Maternity Ward', 23, 69)
Row 1715 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 5, 32, 23), 'Emergency Ward', 27, 62)
Row 1716 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 5, 32, 38), 'Surgical Ward', 24, 67)
Row 1717 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 5, 33, 18), 'ICU', 28, 54)
Row 1718 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 5, 33, 21), 'Maternity Ward', 23, 69)
Row 1719 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 5, 33, 44), 'Emergency Ward', 27, 62)
Row 1720 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 5, 33, 46), 'Surgical Ward', 24, 67)
Row 1721 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 5, 34, 36), 'ICU', 28, 54)
Row 1722 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 5, 34, 42), 'Maternity Ward', 24, 69)
Row 1723 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 5, 35, 5), 'Emergency Ward', 27, 62)
Row 1724 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 5, 35, 6), 'Surgical Ward', 24, 67)
Row 1725 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 5, 35, 55), 'ICU', 28, 54)
Row 1726 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 5, 36, 2), 'Maternity Ward', 23, 69)
Row 1727 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 5, 36, 28), 'Emergency Ward', 27, 62)
Row 1728 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 5, 36, 29), 'Surgical Ward', 24, 67)
Row 1729 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 5, 37, 15), 'ICU', 25, 50)
Row 1730 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 5, 37, 16), 'Maternity Ward', 24, 69)
Row 1731 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 5, 37, 48), 'Surgical Ward', 24, 67)
Row 1732 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 5, 37, 50), 'Emergency Ward', 27, 62)
Row 1733 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 5, 38, 24), 'Maternity Ward', 23, 69)

Row 1734 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 5, 38, 34), 'ICU', 28, 54)
Row 1735 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 5, 39, 8), 'Surgical Ward', 24, 67)
Row 1736 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 5, 39, 9), 'Emergency Ward', 27, 62)
Row 1737 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 5, 39, 45), 'Maternity Ward', 23, 69)
Row 1738 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 5, 39, 53), 'ICU', 28, 54)
Row 1739 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 5, 40, 28), 'Surgical Ward', 24, 67)
Row 1740 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 5, 40, 30), 'Emergency Ward', 27, 62)
Row 1741 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 5, 41, 5), 'ICU', 28, 54)
Row 1742 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 5, 41, 6), 'Maternity Ward', 23, 69)
Row 1743 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 5, 41, 49), 'Surgical Ward', 24, 67)
Row 1744 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 5, 41, 52), 'Emergency Ward', 27, 62)
Row 1745 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 5, 42, 13), 'ICU', 28, 54)
Row 1746 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 5, 42, 26), 'Maternity Ward', 24, 69)
Row 1747 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 5, 43, 9), 'Surgical Ward', 24, 67)
Row 1748 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 5, 43, 12), 'Emergency Ward', 27, 62)
Row 1749 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 5, 43, 32), 'ICU', 25, 50)
Row 1750 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 5, 43, 46), 'Maternity Ward', 24, 69)
Row 1751 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 5, 44, 29), 'Emergency Ward', 27, 62)
Row 1752 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 5, 44, 30), 'Surgical Ward', 24, 67)
Row 1753 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 5, 44, 51), 'ICU', 28, 54)
Row 1754 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 5, 45, 8), 'Maternity Ward', 23, 69)
Row 1755 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 5, 45, 36), 'Emergency Ward', 27, 62)
Row 1756 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 5, 45, 50), 'Surgical Ward', 24, 67)
Row 1757 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 5, 46, 10), 'ICU', 28, 53)
Row 1758 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 5, 46, 28), 'Maternity Ward', 23, 69)
Row 1759 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 5, 46, 58), 'Emergency Ward', 27, 62)
Row 1760 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 5, 47, 4), 'Surgical Ward', 24, 67)
Row 1761 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 5, 47, 29), 'ICU', 28, 54)
Row 1762 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 5, 47, 48), 'Maternity Ward', 23, 69)
Row 1763 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 5, 48, 13), 'Surgical Ward', 24, 67)
Row 1764 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 5, 48, 19), 'Emergency Ward', 27, 62)
Row 1765 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 5, 48, 48), 'ICU', 28, 54)
Row 1766 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 5, 49, 8), 'Maternity Ward', 24, 69)
Row 1767 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 5, 49, 33), 'Surgical Ward', 24, 67)
Row 1768 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 5, 49, 40), 'Emergency Ward', 27, 62)
Row 1769 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 5, 50, 8), 'ICU', 25, 50)
Row 1770 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 5, 50, 28), 'Maternity Ward', 24, 69)
Row 1771 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 5, 50, 54), 'Surgical Ward', 24, 67)
Row 1772 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 5, 51, 1), 'Emergency Ward', 27, 62)
Row 1773 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 5, 51, 28), 'ICU', 28, 54)
Row 1774 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 5, 51, 41), 'Maternity Ward', 23, 69)
Row 1775 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 5, 52, 14), 'Surgical Ward', 24, 67)
Row 1776 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 5, 52, 22), 'Emergency Ward', 27, 62)
Row 1777 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 5, 52, 46), 'ICU', 28, 54)
Row 1778 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 5, 52, 50), 'Maternity Ward', 23, 69)
Row 1779 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 5, 53, 35), 'Surgical Ward', 24, 67)
Row 1780 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 5, 53, 43), 'Emergency Ward', 27, 62)

Row 1781 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 5, 54, 5), 'ICU', 28, 54)
Row 1782 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 5, 54, 11), 'Maternity Ward', 23, 69)
Row 1783 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 5, 54, 55), 'Surgical Ward', 24, 67)
Row 1784 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 5, 55, 4), 'Emergency Ward', 27, 62)
Row 1785 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 5, 55, 18), 'ICU', 28, 54)
Row 1786 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 5, 55, 31), 'Maternity Ward', 24, 69)
Row 1787 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 5, 56, 15), 'Surgical Ward', 24, 67)
Row 1788 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 5, 56, 25), 'ICU', 28, 54)
Row 1789 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 5, 56, 26), 'Emergency Ward', 27, 62)
Row 1790 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 5, 56, 52), 'Maternity Ward', 24, 69)
Row 1791 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 5, 57, 36), 'Surgical Ward', 24, 67)
Row 1792 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 5, 57, 48), 'Emergency Ward', 27, 62)
Row 1793 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 5, 58, 12), 'Maternity Ward', 23, 69)
Row 1794 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 5, 58, 56), 'Surgical Ward', 24, 67)
Row 1795 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 5, 59, 1), 'Emergency Ward', 27, 62)
Row 1796 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 5, 59, 3), 'ICU', 28, 54)
Row 1797 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 5, 59, 32), 'Maternity Ward', 24, 69)
Row 1798 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 6, 0, 10), 'Emergency Ward', 27, 62)
Row 1799 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 6, 0, 18), 'Surgical Ward', 24, 67)
Row 1800 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 6, 0, 22), 'ICU', 28, 54)
Row 1801 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 6, 0, 53), 'Maternity Ward', 24, 69)
Row 1802 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 6, 1, 30), 'Surgical Ward', 24, 67)
Row 1803 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 6, 1, 32), 'Emergency Ward', 27, 62)
Row 1804 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 6, 1, 41), 'ICU', 28, 54)
Row 1805 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 6, 2, 13), 'Maternity Ward', 24, 69)
Row 1806 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 6, 2, 39), 'Surgical Ward', 24, 67)
Row 1807 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 6, 2, 53), 'Emergency Ward', 27, 62)
Row 1808 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 6, 3, 1), 'ICU', 28, 54)
Row 1809 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 6, 3, 34), 'Maternity Ward', 24, 69)
Row 1810 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 6, 4), 'Surgical Ward', 24, 67)
Row 1811 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 6, 4, 14), 'Emergency Ward', 27, 62)
Row 1812 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 6, 4, 20), 'ICU', 28, 53)
Row 1813 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 6, 4, 54), 'Maternity Ward', 24, 69)
Row 1814 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 6, 5, 20), 'Surgical Ward', 24, 67)
Row 1815 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 6, 5, 36), 'Emergency Ward', 27, 62)
Row 1816 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 6, 5, 39), 'ICU', 28, 53)
Row 1817 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 6, 6, 8), 'Maternity Ward', 24, 69)
Row 1818 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 6, 6, 42), 'Surgical Ward', 24, 67)
Row 1819 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 6, 6, 56), 'Emergency Ward', 27, 62)
Row 1820 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 6, 6, 58), 'ICU', 28, 53)
Row 1821 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 6, 7, 18), 'Maternity Ward', 23, 69)
Row 1822 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 6, 8, 1), 'Surgical Ward', 24, 67)
Row 1823 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 6, 8, 18), 'Emergency Ward', 27, 62)
Row 1824 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 6, 8, 19), 'ICU', 28, 53)
Row 1825 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 6, 8, 38), 'Maternity Ward', 24, 69)
Row 1826 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 6, 9, 22), 'Surgical Ward', 24, 67)

Row 1827 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 6, 9, 29), 'ICU', 25, 49)
Row 1828 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 6, 9, 38), 'Emergency Ward', 27, 62)
Row 1829 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 6, 9, 58), 'Maternity Ward', 23, 69)
Row 1830 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 6, 10, 38), 'ICU', 28, 53)
Row 1831 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 6, 10, 42), 'Surgical Ward', 24, 67)
Row 1832 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 6, 10, 59), 'Emergency Ward', 27, 62)
Row 1833 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 6, 11, 18), 'Maternity Ward', 24, 69)
Row 1834 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 6, 11, 56), 'ICU', 28, 54)
Row 1835 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 6, 12, 3), 'Surgical Ward', 24, 67)
Row 1836 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 6, 12, 21), 'Emergency Ward', 27, 62)
Row 1837 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 6, 12, 38), 'Maternity Ward', 23, 69)
Row 1838 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 6, 13, 15), 'ICU', 28, 53)
Row 1839 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 6, 13, 23), 'Surgical Ward', 24, 67)
Row 1840 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 6, 13, 35), 'Emergency Ward', 27, 62)
Row 1841 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 6, 13, 59), 'Maternity Ward', 23, 69)
Row 1842 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 6, 14, 34), 'ICU', 28, 53)
Row 1843 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 6, 14, 44), 'Surgical Ward', 24, 67)
Row 1844 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 6, 14, 45), 'Emergency Ward', 27, 62)
Row 1845 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 6, 15, 19), 'Maternity Ward', 24, 69)
Row 1846 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 6, 15, 53), 'ICU', 28, 54)
Row 1847 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 6, 15, 58), 'Surgical Ward', 24, 67)
Row 1848 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 6, 16, 5), 'Emergency Ward', 27, 62)
Row 1849 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 6, 16, 39), 'Maternity Ward', 24, 69)
Row 1850 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 6, 17, 6), 'Surgical Ward', 24, 67)
Row 1851 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 6, 17, 13), 'ICU', 28, 53)
Row 1852 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 6, 17, 28), 'Emergency Ward', 27, 62)
Row 1853 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 6, 18), 'Maternity Ward', 23, 69)
Row 1854 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 6, 18, 28), 'Surgical Ward', 24, 67)
Row 1855 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 6, 18, 32), 'ICU', 28, 54)
Row 1856 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 6, 18, 48), 'Emergency Ward', 27, 62)
Row 1857 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 6, 19, 20), 'Maternity Ward', 24, 69)
Row 1858 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 6, 19, 48), 'Surgical Ward', 24, 67)
Row 1859 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 6, 19, 51), 'ICU', 28, 53)
Row 1860 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 6, 20, 9), 'Emergency Ward', 27, 62)
Row 1861 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 6, 20, 34), 'Maternity Ward', 24, 69)
Row 1862 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 6, 21, 8), 'Surgical Ward', 24, 67)
Row 1863 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 6, 21, 10), 'ICU', 28, 53)
Row 1864 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 6, 21, 30), 'Emergency Ward', 27, 62)
Row 1865 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 6, 21, 42), 'Maternity Ward', 23, 69)
Row 1866 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 6, 22, 28), 'Surgical Ward', 24, 67)
Row 1867 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 6, 22, 29), 'ICU', 28, 53)
Row 1868 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 6, 22, 51), 'Emergency Ward', 27, 62)
Row 1869 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 6, 23, 3), 'Maternity Ward', 24, 69)
Row 1870 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 6, 23, 41), 'ICU', 28, 53)
Row 1871 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 6, 23, 48), 'Surgical Ward', 24, 67)
Row 1872 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 6, 24, 12), 'Emergency Ward', 27, 62)

Row 1873 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 6, 24, 24), 'Maternity Ward', 24, 69)
Row 1874 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 6, 24, 49), 'ICU', 28, 53)
Row 1875 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 6, 25, 9), 'Surgical Ward', 24, 67)
Row 1876 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 6, 25, 33), 'Emergency Ward', 27, 62)
Row 1877 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 6, 25, 44), 'Maternity Ward', 23, 69)
Row 1878 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 6, 26, 8), 'ICU', 28, 53)
Row 1879 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 6, 26, 29), 'Surgical Ward', 24, 67)
Row 1880 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 6, 26, 54), 'Emergency Ward', 27, 62)
Row 1881 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 6, 27, 4), 'Maternity Ward', 23, 69)
Row 1882 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 6, 27, 28), 'ICU', 28, 53)
Row 1883 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 6, 27, 50), 'Surgical Ward', 24, 67)
Row 1884 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 6, 28, 8), 'Emergency Ward', 27, 62)
Row 1885 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 6, 28, 25), 'Maternity Ward', 24, 69)
Row 1886 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 6, 28, 48), 'ICU', 28, 54)
Row 1887 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 6, 29, 10), 'Surgical Ward', 24, 67)
Row 1888 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 6, 29, 18), 'Emergency Ward', 27, 62)
Row 1889 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 6, 29, 45), 'Maternity Ward', 24, 69)
Row 1890 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 6, 30, 6), 'ICU', 28, 53)
Row 1891 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 6, 30, 24), 'Surgical Ward', 24, 67)
Row 1892 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 6, 30, 39), 'Emergency Ward', 27, 62)
Row 1893 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 6, 31, 5), 'Maternity Ward', 24, 69)
Row 1894 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 6, 31, 25), 'ICU', 28, 53)
Row 1895 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 6, 31, 33), 'Surgical Ward', 24, 67)
Row 1896 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 6, 32), 'Emergency Ward', 27, 62)
Row 1897 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 6, 32, 26), 'Maternity Ward', 23, 69)
Row 1898 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 6, 32, 44), 'ICU', 28, 53)
Row 1899 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 6, 32, 53), 'Surgical Ward', 24, 67)
Row 1900 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 6, 33, 22), 'Emergency Ward', 27, 62)
Row 1901 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 6, 33, 46), 'Maternity Ward', 23, 69)
Row 1902 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 6, 34, 3), 'ICU', 28, 53)
Row 1903 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 6, 34, 14), 'Surgical Ward', 24, 67)
Row 1904 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 6, 34, 43), 'Emergency Ward', 27, 62)
Row 1905 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 6, 35), 'Maternity Ward', 23, 68)
Row 1906 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 6, 35, 22), 'ICU', 28, 53)
Row 1907 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 6, 35, 38), 'Surgical Ward', 24, 67)
Row 1908 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 6, 36, 4), 'Emergency Ward', 27, 62)
Row 1909 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 6, 36, 9), 'Maternity Ward', 23, 69)
Row 1910 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 6, 36, 42), 'ICU', 28, 54)
Row 1911 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 6, 36, 55), 'Surgical Ward', 24, 67)
Row 1912 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 6, 37, 25), 'Emergency Ward', 27, 62)
Row 1913 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 6, 37, 29), 'Maternity Ward', 23, 69)
Row 1914 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 6, 37, 53), 'ICU', 28, 54)
Row 1915 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 6, 38, 15), 'Surgical Ward', 24, 67)
Row 1916 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 6, 38, 46), 'Emergency Ward', 27, 62)
Row 1917 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 6, 38, 49), 'Maternity Ward', 23, 69)
Row 1918 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 6, 39, 1), 'ICU', 28, 54)
Row 1919 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 6, 39, 36), 'Surgical Ward', 24, 67)

Row 1920 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 6, 40, 8), 'Emergency Ward', 27, 62)
Row 1921 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 6, 40, 10), 'Maternity Ward', 24, 69)
Row 1922 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 6, 40, 21), 'ICU', 28, 54)
Row 1923 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 6, 40, 56), 'Surgical Ward', 24, 67)
Row 1924 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 6, 41, 28), 'Emergency Ward', 27, 62)
Row 1925 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 6, 41, 30), 'Maternity Ward', 24, 69)
Row 1926 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 6, 41, 40), 'ICU', 28, 54)
Row 1927 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 6, 42, 18), 'Surgical Ward', 24, 67)
Row 1928 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 6, 42, 42), 'Emergency Ward', 27, 62)
Row 1929 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 6, 42, 51), 'Maternity Ward', 23, 69)
Row 1930 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 6, 42, 59), 'ICU', 28, 54)
Row 1931 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 6, 43, 38), 'Surgical Ward', 24, 67)
Row 1932 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 6, 43, 52), 'Emergency Ward', 27, 62)
Row 1933 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 6, 44, 11), 'Maternity Ward', 23, 68)
Row 1934 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 6, 44, 18), 'ICU', 28, 54)
Row 1935 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 6, 44, 51), 'Surgical Ward', 24, 67)
Row 1936 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 6, 45, 13), 'Emergency Ward', 27, 62)
Row 1937 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 6, 45, 31), 'Maternity Ward', 23, 69)
Row 1938 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 6, 45, 38), 'ICU', 28, 53)
Row 1939 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 6, 45, 59), 'Surgical Ward', 24, 67)
Row 1940 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 6, 46, 34), 'Emergency Ward', 27, 62)
Row 1941 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 6, 46, 52), 'Maternity Ward', 24, 69)
Row 1942 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 6, 46, 56), 'ICU', 25, 50)
Row 1943 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 6, 47, 20), 'Surgical Ward', 24, 67)
Row 1944 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 6, 47, 55), 'Emergency Ward', 27, 62)
Row 1945 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 6, 48, 12), 'Maternity Ward', 24, 69)
Row 1946 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 6, 48, 15), 'ICU', 28, 53)
Row 1947 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 6, 48, 40), 'Surgical Ward', 24, 67)
Row 1948 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 6, 49, 18), 'Emergency Ward', 27, 62)
Row 1949 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 6, 49, 26), 'Maternity Ward', 23, 69)
Row 1950 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 6, 49, 34), 'ICU', 28, 54)
Row 1951 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 6, 50, 1), 'Surgical Ward', 24, 67)
Row 1952 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 6, 50, 35), 'Maternity Ward', 23, 69)
Row 1953 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 6, 50, 39), 'Emergency Ward', 27, 62)
Row 1954 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 6, 50, 54), 'ICU', 28, 54)
Row 1955 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 6, 51, 21), 'Surgical Ward', 24, 67)
Row 1956 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 6, 51, 55), 'Maternity Ward', 23, 69)
Row 1957 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 6, 51, 59), 'Emergency Ward', 27, 62)
Row 1958 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 6, 52, 6), 'ICU', 28, 53)
Row 1959 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 6, 52, 42), 'Surgical Ward', 24, 67)
Row 1960 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 6, 53, 13), 'ICU', 28, 53)
Row 1961 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 6, 53, 15), 'Maternity Ward', 23, 69)
Row 1962 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 6, 53, 20), 'Emergency Ward', 27, 62)
Row 1963 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 6, 54, 2), 'Surgical Ward', 24, 67)
Row 1964 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 6, 54, 32), 'ICU', 28, 54)
Row 1965 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 6, 54, 36), 'Maternity Ward', 23, 69)

Row 1966 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 6, 54, 41), 'Emergency Ward', 27, 62)
Row 1967 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 6, 55, 23), 'Surgical Ward', 24, 67)
Row 1968 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 6, 55, 52), 'ICU', 28, 54)
Row 1969 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 6, 55, 56), 'Maternity Ward', 23, 69)
Row 1970 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 6, 56, 2), 'Emergency Ward', 27, 62)
Row 1971 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 6, 56, 43), 'Surgical Ward', 24, 67)
Row 1972 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 6, 57, 11), 'ICU', 28, 53)
Row 1973 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 6, 57, 16), 'Emergency Ward', 27, 62)
Row 1974 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 6, 57, 19), 'Maternity Ward', 24, 69)
Row 1975 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 6, 58, 4), 'Surgical Ward', 24, 67)
Row 1976 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 6, 58, 26), 'Emergency Ward', 27, 62)
Row 1977 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 6, 58, 30), 'ICU', 28, 53)
Row 1978 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 6, 58, 38), 'Maternity Ward', 23, 69)
Row 1979 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 6, 59, 18), 'Surgical Ward', 24, 67)
Row 1980 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 6, 59, 48), 'Emergency Ward', 27, 62)
Row 1981 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 6, 59, 49), 'ICU', 28, 54)
Row 1982 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 6, 59, 58), 'Maternity Ward', 23, 69)
Row 1983 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 7, 0, 26), 'Surgical Ward', 24, 67)
Row 1984 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 7, 1, 8), 'Emergency Ward', 27, 62)
Row 1985 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 7, 1, 9), 'ICU', 28, 54)
Row 1986 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 7, 1, 18), 'Maternity Ward', 23, 69)
Row 1987 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 7, 1, 48), 'Surgical Ward', 24, 67)
Row 1988 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 7, 2, 28), 'ICU', 28, 54)
Row 1989 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 7, 2, 29), 'Emergency Ward', 27, 62)
Row 1990 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 7, 2, 38), 'Maternity Ward', 23, 69)
Row 1991 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 7, 3, 8), 'Surgical Ward', 24, 67)
Row 1992 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 7, 3, 48), 'ICU', 28, 53)
Row 1993 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 7, 3, 50), 'Emergency Ward', 27, 62)
Row 1994 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 7, 3, 52), 'Maternity Ward', 23, 69)
Row 1995 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 7, 4, 28), 'Surgical Ward', 24, 67)
Row 1996 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 7, 5, 1), 'Maternity Ward', 23, 69)
Row 1997 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 7, 5, 6), 'ICU', 28, 53)
Row 1998 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 7, 5, 12), 'Emergency Ward', 27, 62)
Row 1999 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 7, 5, 48), 'Surgical Ward', 24, 67)
Row 2000 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 7, 6, 18), 'ICU', 28, 53)
Row 2001 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 7, 6, 21), 'Maternity Ward', 24, 69)
Row 2002 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 7, 6, 33), 'Emergency Ward', 27, 62)
Row 2003 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 7, 7, 8), 'Surgical Ward', 24, 67)
Row 2004 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 7, 7, 25), 'ICU', 28, 53)
Row 2005 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 7, 7, 41), 'Maternity Ward', 24, 69)
Row 2006 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 7, 7, 54), 'Emergency Ward', 27, 62)
Row 2007 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 7, 8, 29), 'Surgical Ward', 24, 67)
Row 2008 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 7, 8, 45), 'ICU', 28, 54)
Row 2009 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 7, 9, 2), 'Maternity Ward', 24, 69)
Row 2010 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 7, 9, 15), 'Emergency Ward', 27, 62)
Row 2011 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 7, 9, 49), 'Surgical Ward', 24, 67)
Row 2012 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 7, 10, 4), 'ICU', 28, 54)

Row 2013 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 7, 10, 22), 'Maternity Ward', 23, 69)
Row 2014 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 7, 10, 36), 'Emergency Ward', 27, 62)
Row 2015 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 7, 11, 10), 'Surgical Ward', 24, 67)
Row 2016 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 7, 11, 23), 'ICU', 28, 53)
Row 2017 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 7, 11, 43), 'Maternity Ward', 24, 69)
Row 2018 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 7, 11, 50), 'Emergency Ward', 27, 62)
Row 2019 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 7, 12, 30), 'Surgical Ward', 24, 67)
Row 2020 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 7, 12, 42), 'ICU', 28, 53)
Row 2021 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 7, 13), 'Emergency Ward', 27, 62)
Row 2022 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 7, 13, 3), 'Maternity Ward', 23, 69)
Row 2023 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 7, 13, 44), 'Surgical Ward', 24, 67)
Row 2024 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 7, 14, 1), 'ICU', 28, 54)
Row 2025 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 7, 14, 21), 'Emergency Ward', 27, 62)
Row 2026 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 7, 14, 23), 'Maternity Ward', 23, 69)
Row 2027 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 7, 14, 53), 'Surgical Ward', 24, 67)
Row 2028 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 7, 15, 20), 'ICU', 28, 54)
Row 2029 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 7, 15, 42), 'Emergency Ward', 27, 62)
Row 2030 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 7, 15, 44), 'Maternity Ward', 23, 69)
Row 2031 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 7, 16, 13), 'Surgical Ward', 24, 67)
Row 2032 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 7, 16, 39), 'ICU', 28, 53)
Row 2033 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 7, 17, 3), 'Emergency Ward', 27, 62)
Row 2034 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 7, 17, 4), 'Maternity Ward', 23, 69)
Row 2035 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 7, 17, 34), 'Surgical Ward', 24, 67)
Row 2036 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 7, 17, 59), 'ICU', 28, 54)
Row 2037 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 7, 18, 18), 'Maternity Ward', 23, 69)
Row 2038 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 7, 18, 24), 'Emergency Ward', 27, 62)
Row 2039 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 7, 18, 54), 'Surgical Ward', 24, 67)
Row 2040 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 7, 19, 18), 'ICU', 28, 53)
Row 2041 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 7, 19, 28), 'Maternity Ward', 24, 69)
Row 2042 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 7, 19, 45), 'Emergency Ward', 27, 62)
Row 2043 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 7, 20, 15), 'Surgical Ward', 24, 67)
Row 2044 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 7, 20, 30), 'ICU', 28, 53)
Row 2045 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 7, 20, 48), 'Maternity Ward', 23, 69)
Row 2046 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 7, 21, 8), 'Emergency Ward', 27, 62)
Row 2047 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 7, 21, 35), 'Surgical Ward', 24, 67)
Row 2048 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 7, 21, 38), 'ICU', 28, 53)
Row 2049 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 7, 22, 8), 'Maternity Ward', 23, 69)
Row 2050 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 7, 22, 28), 'Emergency Ward', 27, 62)
Row 2051 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 7, 22, 56), 'Surgical Ward', 24, 67)
Row 2052 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 7, 22, 58), 'ICU', 28, 53)
Row 2053 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 7, 23, 28), 'Maternity Ward', 23, 69)
Row 2054 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 7, 23, 49), 'Emergency Ward', 27, 62)
Row 2055 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 7, 24, 16), 'ICU', 28, 53)
Row 2056 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 7, 24, 18), 'Surgical Ward', 24, 67)
Row 2057 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 7, 24, 48), 'Maternity Ward', 23, 69)
Row 2058 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 7, 25, 10), 'Emergency Ward', 27, 62)
Row 2059 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 7, 25, 35), 'ICU', 28, 53)

Row 2060 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 7, 25, 38), 'Surgical Ward', 24, 66)
Row 2061 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 7, 26, 9), 'Maternity Ward', 24, 69)
Row 2062 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 7, 26, 24), 'Emergency Ward', 27, 62)
Row 2063 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 7, 26, 54), 'ICU', 28, 53)
Row 2064 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 7, 26, 58), 'Surgical Ward', 24, 66)
Row 2065 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 7, 27, 29), 'Maternity Ward', 24, 69)
Row 2066 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 7, 27, 34), 'Emergency Ward', 27, 62)
Row 2067 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 7, 28, 11), 'Surgical Ward', 24, 66)
Row 2068 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 7, 28, 13), 'ICU', 28, 53)
Row 2069 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 7, 28, 49), 'Maternity Ward', 23, 69)
Row 2070 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 7, 28, 55), 'Emergency Ward', 27, 62)
Row 2071 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 7, 29, 20), 'Surgical Ward', 24, 66)
Row 2072 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 7, 29, 32), 'ICU', 28, 53)
Row 2073 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 7, 30, 10), 'Maternity Ward', 23, 69)
Row 2074 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 7, 30, 16), 'Emergency Ward', 27, 62)
Row 2075 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 7, 30, 40), 'Surgical Ward', 24, 67)
Row 2076 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 7, 30, 52), 'ICU', 28, 53)
Row 2077 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 7, 31, 31), 'Maternity Ward', 23, 69)
Row 2078 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 7, 31, 38), 'Emergency Ward', 27, 62)
Row 2079 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 7, 32, 1), 'Surgical Ward', 24, 66)
Row 2080 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 7, 32, 11), 'ICU', 28, 53)
Row 2081 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 7, 32, 44), 'Maternity Ward', 23, 69)
Row 2082 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 7, 32, 58), 'Emergency Ward', 27, 62)
Row 2083 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 7, 33, 21), 'Surgical Ward', 24, 67)
Row 2084 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 7, 33, 30), 'ICU', 28, 53)
Row 2085 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 7, 33, 53), 'Maternity Ward', 24, 69)
Row 2086 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 7, 34, 19), 'Emergency Ward', 27, 62)
Row 2087 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 7, 34, 41), 'Surgical Ward', 24, 67)
Row 2088 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 7, 34, 42), 'ICU', 28, 53)
Row 2089 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 7, 35, 13), 'Maternity Ward', 24, 69)
Row 2090 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 7, 35, 41), 'Emergency Ward', 27, 62)
Row 2091 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 7, 35, 50), 'ICU', 28, 53)
Row 2092 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 7, 36, 2), 'Surgical Ward', 24, 67)
Row 2093 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 7, 36, 33), 'Maternity Ward', 23, 69)
Row 2094 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 7, 37, 2), 'Emergency Ward', 27, 62)
Row 2095 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 7, 37, 9), 'ICU', 28, 53)
Row 2096 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 7, 37, 23), 'Surgical Ward', 24, 67)
Row 2097 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 7, 37, 54), 'Maternity Ward', 23, 69)
Row 2098 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 7, 38, 23), 'Emergency Ward', 27, 62)
Row 2099 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 7, 38, 28), 'ICU', 28, 53)
Row 2100 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 7, 38, 43), 'Surgical Ward', 24, 66)
Row 2101 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 7, 39, 14), 'Maternity Ward', 23, 69)
Row 2102 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 7, 39, 44), 'Emergency Ward', 27, 62)
Row 2103 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 7, 39, 48), 'ICU', 28, 54)
Row 2104 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 7, 40, 3), 'Surgical Ward', 24, 67)
Row 2105 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 7, 40, 35), 'Maternity Ward', 24, 69)
Row 2106 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 7, 40, 58), 'Emergency Ward', 27, 62)

Row 2107 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 7, 41, 6), 'ICU', 28, 53)
Row 2108 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 7, 41, 24), 'Surgical Ward', 24, 66)
Row 2109 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 7, 41, 55), 'Maternity Ward', 24, 69)
Row 2110 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 7, 42, 8), 'Emergency Ward', 27, 62)
Row 2111 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 7, 42, 25), 'ICU', 28, 54)
Row 2112 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 7, 42, 38), 'Surgical Ward', 24, 67)
Row 2113 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 7, 43, 15), 'Maternity Ward', 23, 69)
Row 2114 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 7, 43, 29), 'Emergency Ward', 27, 62)
Row 2115 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 7, 43, 44), 'ICU', 28, 53)
Row 2116 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 7, 43, 48), 'Surgical Ward', 24, 66)
Row 2117 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 7, 44, 38), 'Maternity Ward', 23, 69)
Row 2118 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 7, 44, 50), 'Emergency Ward', 27, 62)
Row 2119 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 7, 45, 4), 'ICU', 28, 54)
Row 2120 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 7, 45, 8), 'Surgical Ward', 24, 66)
Row 2121 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 7, 45, 56), 'Maternity Ward', 23, 69)
Row 2122 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 7, 46, 11), 'Emergency Ward', 27, 62)
Row 2123 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 7, 46, 23), 'ICU', 28, 53)
Row 2124 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 7, 46, 28), 'Surgical Ward', 24, 66)
Row 2125 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 7, 47, 10), 'Maternity Ward', 23, 69)
Row 2126 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 7, 47, 32), 'Emergency Ward', 27, 62)
Row 2127 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 7, 47, 42), 'ICU', 28, 53)
Row 2128 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 7, 47, 48), 'Surgical Ward', 24, 66)
Row 2129 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 7, 48, 19), 'Maternity Ward', 23, 69)
Row 2130 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 7, 48, 53), 'Emergency Ward', 27, 62)
Row 2131 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 7, 48, 54), 'ICU', 28, 54)
Row 2132 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 7, 49, 8), 'Surgical Ward', 24, 66)
Row 2133 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 7, 49, 39), 'Maternity Ward', 23, 69)
Row 2134 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 7, 50, 2), 'ICU', 28, 54)
Row 2135 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 7, 50, 14), 'Emergency Ward', 27, 62)
Row 2136 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 7, 50, 29), 'Surgical Ward', 24, 66)
Row 2137 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 7, 50, 59), 'Maternity Ward', 24, 69)
Row 2138 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 7, 51, 21), 'ICU', 25, 49)
Row 2139 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 7, 51, 36), 'Emergency Ward', 27, 62)
Row 2140 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 7, 51, 49), 'Surgical Ward', 24, 66)
Row 2141 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 7, 52, 20), 'Maternity Ward', 23, 69)
Row 2142 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 7, 52, 40), 'ICU', 28, 53)
Row 2143 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 7, 52, 58), 'Emergency Ward', 27, 62)
Row 2144 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 7, 53, 9), 'Surgical Ward', 24, 66)
Row 2145 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 7, 53, 40), 'Maternity Ward', 23, 69)
Row 2146 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 7, 53, 59), 'ICU', 28, 54)
Row 2147 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 7, 54, 18), 'Emergency Ward', 27, 62)
Row 2148 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 7, 54, 30), 'Surgical Ward', 24, 67)
Row 2149 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 7, 55, 1), 'Maternity Ward', 24, 69)
Row 2150 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 7, 55, 18), 'ICU', 28, 54)
Row 2151 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 7, 55, 32), 'Emergency Ward', 27, 62)
Row 2152 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 7, 55, 50), 'Surgical Ward', 24, 67)

Row 2153 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 7, 56, 21), 'Maternity Ward', 24, 69)
Row 2154 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 7, 56, 38), 'ICU', 28, 54)
Row 2155 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 7, 56, 42), 'Emergency Ward', 27, 62)
Row 2156 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 7, 57, 4), 'Surgical Ward', 24, 67)
Row 2157 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 7, 57, 42), 'Maternity Ward', 23, 69)
Row 2158 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 7, 57, 58), 'ICU', 28, 53)
Row 2159 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 7, 58, 4), 'Emergency Ward', 27, 62)
Row 2160 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 7, 58, 13), 'Surgical Ward', 24, 67)
Row 2161 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 7, 59, 2), 'Maternity Ward', 23, 69)
Row 2162 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 7, 59, 16), 'ICU', 28, 54)
Row 2163 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 7, 59, 24), 'Emergency Ward', 27, 62)
Row 2164 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 7, 59, 33), 'Surgical Ward', 24, 67)
Row 2165 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 8, 0, 22), 'Maternity Ward', 24, 69)
Row 2166 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 8, 0, 35), 'ICU', 28, 53)
Row 2167 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 8, 0, 45), 'Emergency Ward', 27, 62)
Row 2168 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 8, 0, 54), 'Surgical Ward', 24, 66)
Row 2169 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 8, 1, 36), 'Maternity Ward', 24, 69)
Row 2170 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 8, 1, 54), 'ICU', 28, 53)
Row 2171 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 8, 2, 8), 'Emergency Ward', 27, 62)
Row 2172 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 8, 2, 14), 'Surgical Ward', 24, 66)
Row 2173 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 8, 2, 45), 'Maternity Ward', 23, 69)
Row 2174 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 8, 3, 6), 'ICU', 28, 53)
Row 2175 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 8, 3, 28), 'Emergency Ward', 27, 62)
Row 2176 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 8, 3, 35), 'Surgical Ward', 24, 67)
Row 2177 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 8, 4, 5), 'Maternity Ward', 23, 69)
Row 2178 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 8, 4, 14), 'ICU', 28, 54)
Row 2179 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 8, 4, 48), 'Emergency Ward', 27, 62)
Row 2180 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 8, 4, 55), 'Surgical Ward', 24, 66)
Row 2181 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 8, 5, 26), 'Maternity Ward', 23, 69)
Row 2182 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 8, 5, 33), 'ICU', 28, 53)
Row 2183 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 8, 6, 9), 'Emergency Ward', 27, 62)
Row 2184 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 8, 6, 16), 'Surgical Ward', 24, 66)
Row 2185 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 8, 6, 46), 'Maternity Ward', 23, 69)
Row 2186 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 8, 6, 52), 'ICU', 28, 54)
Row 2187 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 8, 7, 31), 'Emergency Ward', 27, 62)
Row 2188 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 8, 7, 36), 'Surgical Ward', 24, 66)
Row 2189 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 8, 8, 6), 'Maternity Ward', 24, 69)
Row 2190 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 8, 8, 11), 'ICU', 28, 53)
Row 2191 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 8, 8, 52), 'Emergency Ward', 27, 62)
Row 2192 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 8, 8, 58), 'Surgical Ward', 24, 66)
Row 2193 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 8, 9, 28), 'Maternity Ward', 23, 69)
Row 2194 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 8, 9, 30), 'ICU', 28, 54)
Row 2195 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 8, 10, 6), 'Emergency Ward', 27, 62)
Row 2196 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 8, 10, 18), 'Surgical Ward', 24, 66)
Row 2197 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 8, 10, 48), 'Maternity Ward', 24, 69)
Row 2198 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 8, 10, 49), 'ICU', 28, 53)
Row 2199 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 8, 11, 15), 'Emergency Ward', 27, 62)
Row 2200 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 8, 11, 31), 'Surgical Ward', 24, 66)

Row 2201 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 8, 12, 8), 'Maternity Ward', 23, 69)
Row 2202 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 8, 12, 9), 'ICU', 28, 53)
Row 2203 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 8, 12, 38), 'Emergency Ward', 27, 62)
Row 2204 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 8, 12, 40), 'Surgical Ward', 24, 66)
Row 2205 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 8, 13, 28), 'Maternity Ward', 24, 69)
Row 2206 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 8, 13, 58), 'Emergency Ward', 27, 62)
Row 2207 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 8, 14), 'Surgical Ward', 24, 66)
Row 2208 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 8, 14, 48), 'ICU', 25, 50)
Row 2209 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 8, 14, 49), 'Maternity Ward', 23, 69)
Row 2210 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 8, 15, 19), 'Emergency Ward', 27, 62)
Row 2211 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 8, 15, 21), 'Surgical Ward', 24, 66)
Row 2212 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 8, 16, 2), 'Maternity Ward', 23, 69)
Row 2213 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 8, 16, 6), 'ICU', 28, 54)
Row 2214 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 8, 16, 40), 'Emergency Ward', 27, 62)
Row 2215 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 8, 16, 41), 'Surgical Ward', 24, 66)
Row 2216 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 8, 17, 11), 'Maternity Ward', 23, 69)
Row 2217 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 8, 17, 18), 'ICU', 25, 50)
Row 2218 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 8, 18, 1), 'Emergency Ward', 27, 62)
Row 2219 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 8, 18, 2), 'Surgical Ward', 24, 66)
Row 2220 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 8, 18, 26), 'ICU', 28, 54)
Row 2221 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 8, 18, 31), 'Maternity Ward', 24, 69)
Row 2222 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 8, 19, 22), 'Surgical Ward', 24, 66)
Row 2223 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 8, 19, 23), 'Emergency Ward', 27, 62)
Row 2224 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 8, 19, 45), 'ICU', 28, 54)
Row 2225 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 8, 19, 52), 'Maternity Ward', 23, 69)
Row 2226 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 8, 20, 42), 'Surgical Ward', 24, 66)
Row 2227 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 8, 20, 43), 'Emergency Ward', 27, 62)
Row 2228 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 8, 21, 4), 'ICU', 28, 53)
Row 2229 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 8, 21, 12), 'Maternity Ward', 23, 69)
Row 2230 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 8, 22, 3), 'Surgical Ward', 24, 66)
Row 2231 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 8, 22, 4), 'Emergency Ward', 27, 62)
Row 2232 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 8, 22, 23), 'ICU', 28, 53)
Row 2233 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 8, 22, 32), 'Maternity Ward', 24, 69)
Row 2234 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 8, 23, 23), 'Surgical Ward', 24, 66)
Row 2235 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 8, 23, 26), 'Emergency Ward', 27, 62)
Row 2236 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 8, 23, 42), 'ICU', 28, 53)
Row 2237 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 8, 23, 53), 'Maternity Ward', 23, 69)
Row 2238 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 8, 24, 40), 'Emergency Ward', 27, 62)
Row 2239 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 8, 24, 44), 'Surgical Ward', 24, 66)
Row 2240 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 8, 25, 2), 'ICU', 28, 54)
Row 2241 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 8, 25, 13), 'Maternity Ward', 23, 69)
Row 2242 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 8, 25, 50), 'Emergency Ward', 27, 62)
Row 2243 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 8, 25, 58), 'Surgical Ward', 24, 66)
Row 2244 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 8, 26, 21), 'ICU', 25, 49)
Row 2245 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 8, 26, 34), 'Maternity Ward', 23, 69)
Row 2246 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 8, 27, 6), 'Surgical Ward', 24, 66)
Row 2247 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 8, 27, 11), 'Emergency Ward', 27, 62)

Row 2248 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 8, 27, 40), 'ICU', 25, 49)
Row 2249 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 8, 27, 55), 'Maternity Ward', 23, 69)
Row 2250 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 8, 28, 28), 'Surgical Ward', 24, 66)
Row 2251 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 8, 28, 32), 'Emergency Ward', 27, 62)
Row 2252 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 8, 29), 'ICU', 25, 50)
Row 2253 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 8, 29, 14), 'Maternity Ward', 23, 69)
Row 2254 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 8, 29, 48), 'Surgical Ward', 24, 66)
Row 2255 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 8, 29, 53), 'Emergency Ward', 27, 62)
Row 2256 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 8, 30, 18), 'ICU', 25, 50)
Row 2257 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 8, 30, 28), 'Maternity Ward', 23, 69)
Row 2258 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 8, 31, 8), 'Surgical Ward', 24, 66)
Row 2259 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 8, 31, 14), 'Emergency Ward', 27, 62)
Row 2260 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 8, 31, 30), 'ICU', 28, 54)
Row 2261 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 8, 31, 38), 'Maternity Ward', 23, 69)
Row 2262 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 8, 32, 28), 'Surgical Ward', 24, 66)
Row 2263 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 8, 32, 35), 'Emergency Ward', 27, 62)
Row 2264 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 8, 32, 38), 'ICU', 28, 53)
Row 2265 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 8, 32, 58), 'Maternity Ward', 24, 69)
Row 2266 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 8, 33, 49), 'Surgical Ward', 24, 66)
Row 2267 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 8, 33, 56), 'Emergency Ward', 27, 62)
Row 2268 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 8, 33, 59), 'ICU', 28, 53)
Row 2269 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 8, 34, 18), 'Maternity Ward', 23, 69)
Row 2270 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 8, 35, 10), 'Surgical Ward', 24, 66)
Row 2271 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 8, 35, 18), 'ICU', 28, 53)
Row 2272 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 8, 35, 19), 'Emergency Ward', 27, 62)
Row 2273 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 8, 35, 38), 'Maternity Ward', 23, 69)
Row 2274 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 8, 36, 30), 'Surgical Ward', 24, 67)
Row 2275 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 8, 36, 35), 'ICU', 28, 54)
Row 2276 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 8, 36, 39), 'Emergency Ward', 27, 62)
Row 2277 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 8, 36, 58), 'Maternity Ward', 23, 69)
Row 2278 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 8, 37, 50), 'Surgical Ward', 24, 67)
Row 2279 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 8, 37, 55), 'ICU', 28, 54)
Row 2280 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 8, 38), 'Emergency Ward', 27, 62)
Row 2281 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 8, 38, 19), 'Maternity Ward', 23, 69)
Row 2282 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 8, 39, 10), 'Surgical Ward', 24, 67)
Row 2283 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 8, 39, 14), 'ICU', 25, 49)
Row 2284 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 8, 39, 15), 'Emergency Ward', 27, 62)
Row 2285 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 8, 39, 39), 'Maternity Ward', 24, 69)
Row 2286 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 8, 40, 24), 'Emergency Ward', 27, 62)
Row 2287 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 8, 40, 25), 'Surgical Ward', 24, 67)
Row 2288 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 8, 40, 33), 'ICU', 28, 54)
Row 2289 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 8, 41), 'Maternity Ward', 24, 69)
Row 2290 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 8, 41, 33), 'Surgical Ward', 24, 67)
Row 2291 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 8, 41, 45), 'Emergency Ward', 27, 62)
Row 2292 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 8, 41, 52), 'ICU', 28, 54)
Row 2293 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 8, 42, 20), 'Maternity Ward', 24, 69)

Row 2294 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 8, 42, 54), 'Surgical Ward', 24, 67)
Row 2295 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 8, 43, 6), 'Emergency Ward', 27, 62)
Row 2296 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 8, 43, 11), 'ICU', 28, 54)
Row 2297 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 8, 43, 40), 'Maternity Ward', 23, 69)
Row 2298 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 8, 44, 14), 'Surgical Ward', 24, 67)
Row 2299 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 8, 44, 28), 'Emergency Ward', 27, 62)
Row 2300 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 8, 44, 30), 'ICU', 28, 54)
Row 2301 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 8, 44, 54), 'Maternity Ward', 23, 69)
Row 2302 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 8, 45, 35), 'Surgical Ward', 24, 67)
Row 2303 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 8, 45, 42), 'ICU', 28, 54)
Row 2304 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 8, 45, 48), 'Emergency Ward', 27, 62)
Row 2305 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 8, 46, 3), 'Maternity Ward', 24, 69)
Row 2306 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 8, 46, 50), 'ICU', 28, 54)
Row 2307 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 8, 46, 55), 'Surgical Ward', 24, 67)
Row 2308 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 8, 47, 9), 'Emergency Ward', 27, 62)
Row 2309 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 8, 47, 23), 'Maternity Ward', 24, 69)
Row 2310 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 8, 48, 9), 'ICU', 28, 54)
Row 2311 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 8, 48, 15), 'Surgical Ward', 24, 67)
Row 2312 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 8, 48, 30), 'Emergency Ward', 27, 62)
Row 2313 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 8, 48, 44), 'Maternity Ward', 23, 69)
Row 2314 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 8, 49, 28), 'ICU', 28, 54)
Row 2315 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 8, 49, 36), 'Surgical Ward', 24, 67)
Row 2316 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 8, 49, 51), 'Emergency Ward', 27, 62)
Row 2317 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 8, 50, 4), 'Maternity Ward', 23, 69)
Row 2318 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 8, 50, 48), 'ICU', 28, 54)
Row 2319 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 8, 50, 58), 'Surgical Ward', 24, 67)
Row 2320 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 8, 51, 13), 'Emergency Ward', 27, 62)
Row 2321 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 8, 51, 25), 'Maternity Ward', 24, 69)
Row 2322 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 8, 52, 8), 'ICU', 28, 54)
Row 2323 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 8, 52, 18), 'Surgical Ward', 24, 67)
Row 2324 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 8, 52, 34), 'Emergency Ward', 27, 62)
Row 2325 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 8, 52, 45), 'Maternity Ward', 23, 69)
Row 2326 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 8, 53, 26), 'ICU', 28, 54)
Row 2327 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 8, 53, 38), 'Surgical Ward', 24, 67)
Row 2328 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 8, 53, 48), 'Emergency Ward', 27, 62)
Row 2329 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 8, 54, 5), 'Maternity Ward', 24, 70)
Row 2330 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 8, 54, 45), 'ICU', 28, 54)
Row 2331 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 8, 54, 51), 'Surgical Ward', 24, 67)
Row 2332 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 8, 54, 58), 'Emergency Ward', 27, 62)
Row 2333 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 8, 55, 26), 'Maternity Ward', 23, 70)
Row 2334 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 8, 56), 'Surgical Ward', 24, 67)
Row 2335 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 8, 56, 4), 'ICU', 28, 54)
Row 2336 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 8, 56, 19), 'Emergency Ward', 27, 62)
Row 2337 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 8, 56, 46), 'Maternity Ward', 23, 70)
Row 2338 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 8, 57, 20), 'Surgical Ward', 24, 67)
Row 2339 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 8, 57, 23), 'ICU', 28, 54)
Row 2340 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 8, 57, 40), 'Emergency Ward', 27, 62)
Row 2341 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 8, 58, 8), 'Maternity Ward', 24, 69)

Row 2342 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 8, 58, 41), 'Surgical Ward', 24, 67)
Row 2343 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 8, 58, 42), 'ICU', 25, 52)
Row 2344 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 8, 59, 1), 'Emergency Ward', 27, 62)
Row 2345 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 8, 59, 20), 'Maternity Ward', 24, 70)
Row 2346 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 8, 59, 55), 'ICU', 25, 53)
Row 2347 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 9, 0, 1), 'Surgical Ward', 24, 67)
Row 2348 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 9, 0, 23), 'Emergency Ward', 27, 62)
Row 2349 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 9, 0, 29), 'Maternity Ward', 24, 70)
Row 2350 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 9, 1, 2), 'ICU', 28, 55)
Row 2351 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 9, 1, 22), 'Surgical Ward', 24, 67)
Row 2352 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 9, 1, 43), 'Emergency Ward', 27, 62)
Row 2353 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 9, 1, 49), 'Maternity Ward', 24, 70)
Row 2354 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 9, 2, 21), 'ICU', 28, 55)
Row 2355 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 9, 2, 42), 'Surgical Ward', 24, 67)
Row 2356 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 9, 3, 4), 'Emergency Ward', 27, 62)
Row 2357 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 9, 3, 10), 'Maternity Ward', 24, 70)
Row 2358 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 9, 3, 40), 'ICU', 28, 56)
Row 2359 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 9, 4, 3), 'Surgical Ward', 24, 67)
Row 2360 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 9, 4, 25), 'Emergency Ward', 27, 62)
Row 2361 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 9, 4, 30), 'Maternity Ward', 24, 70)
Row 2362 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 9, 5), 'ICU', 28, 56)
Row 2363 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 9, 5, 23), 'Surgical Ward', 24, 67)
Row 2364 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 9, 5, 48), 'Emergency Ward', 27, 62)
Row 2365 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 9, 5, 50), 'Maternity Ward', 24, 70)
Row 2366 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 9, 6, 19), 'ICU', 28, 56)
Row 2367 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 9, 6, 44), 'Surgical Ward', 24, 67)
Row 2368 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 9, 7, 8), 'Emergency Ward', 28, 62)
Row 2369 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 9, 7, 11), 'Maternity Ward', 24, 70)
Row 2370 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 9, 7, 38), 'ICU', 28, 56)
Row 2371 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 9, 8, 4), 'Surgical Ward', 24, 67)
Row 2372 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 9, 8, 22), 'Emergency Ward', 27, 62)
Row 2373 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 9, 8, 32), 'Maternity Ward', 24, 70)
Row 2374 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 9, 8, 58), 'ICU', 28, 56)
Row 2375 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 9, 9, 18), 'Surgical Ward', 24, 68)
Row 2376 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 9, 9, 32), 'Emergency Ward', 27, 62)
Row 2377 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 9, 9, 52), 'Maternity Ward', 24, 70)
Row 2378 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 9, 10, 16), 'ICU', 28, 57)
Row 2379 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 9, 10, 28), 'Surgical Ward', 24, 68)
Row 2380 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 9, 10, 53), 'Emergency Ward', 27, 62)
Row 2381 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 9, 11, 12), 'Maternity Ward', 24, 70)
Row 2382 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 9, 11, 35), 'ICU', 28, 56)
Row 2383 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 9, 11, 48), 'Surgical Ward', 24, 68)
Row 2384 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 9, 12, 14), 'Emergency Ward', 28, 62)
Row 2385 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 9, 12, 33), 'Maternity Ward', 24, 70)
Row 2386 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 9, 12, 54), 'ICU', 28, 57)
Row 2387 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 9, 13, 8), 'Surgical Ward', 24, 68)
Row 2388 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 9, 13, 35), 'Emergency Ward', 28, 62)

Row 2389 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 9, 13, 46), 'Maternity Ward', 24, 70)
Row 2390 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 9, 14, 8), 'ICU', 28, 57)
Row 2391 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 9, 14, 28), 'Surgical Ward', 24, 68)
Row 2392 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 9, 14, 55), 'Maternity Ward', 24, 70)
Row 2393 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 9, 14, 56), 'Emergency Ward', 27, 62)
Row 2394 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 9, 15, 14), 'ICU', 28, 57)
Row 2395 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 9, 15, 48), 'Surgical Ward', 24, 68)
Row 2396 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 9, 16, 16), 'Maternity Ward', 24, 70)
Row 2397 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 9, 16, 19), 'Emergency Ward', 27, 62)
Row 2398 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 9, 16, 33), 'ICU', 28, 57)
Row 2399 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 9, 17, 9), 'Surgical Ward', 24, 67)
Row 2400 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 9, 17, 36), 'Maternity Ward', 24, 70)
Row 2401 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 9, 17, 38), 'Emergency Ward', 27, 62)
Row 2402 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 9, 17, 53), 'ICU', 24, 55)
Row 2403 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 9, 18, 29), 'Surgical Ward', 24, 66)
Row 2404 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 9, 18, 56), 'Maternity Ward', 24, 68)
Row 2405 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 9, 18, 59), 'Emergency Ward', 27, 62)
Row 2406 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 9, 19, 12), 'ICU', 28, 55)
Row 2407 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 9, 19, 50), 'Surgical Ward', 24, 65)
Row 2408 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 9, 20, 18), 'Maternity Ward', 23, 67)
Row 2409 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 9, 20, 20), 'Emergency Ward', 27, 62)
Row 2410 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 9, 20, 31), 'ICU', 27, 54)
Row 2411 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 9, 21, 10), 'Surgical Ward', 24, 64)
Row 2412 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 9, 21, 38), 'Maternity Ward', 23, 66)
Row 2413 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 9, 21, 42), 'Emergency Ward', 27, 61)
Row 2414 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 9, 21, 50), 'ICU', 27, 53)
Row 2415 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 9, 22, 31), 'Surgical Ward', 24, 64)
Row 2416 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 9, 22, 56), 'Emergency Ward', 27, 61)
Row 2417 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 9, 22, 57), 'Maternity Ward', 23, 65)
Row 2418 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 9, 23, 9), 'ICU', 27, 53)
Row 2419 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 9, 23, 44), 'Surgical Ward', 24, 64)
Row 2420 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 9, 24, 5), 'Emergency Ward', 27, 60)
Row 2421 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 9, 24, 18), 'Maternity Ward', 23, 65)
Row 2422 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 9, 24, 28), 'ICU', 27, 51)
Row 2423 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 9, 24, 53), 'Surgical Ward', 24, 63)
Row 2424 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 9, 25, 28), 'Emergency Ward', 27, 60)
Row 2425 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 9, 25, 38), 'Maternity Ward', 23, 64)
Row 2426 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 9, 25, 48), 'ICU', 27, 49)
Row 2427 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 9, 26, 14), 'Surgical Ward', 24, 62)
Row 2428 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 9, 26, 48), 'Emergency Ward', 27, 60)
Row 2429 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 9, 26, 59), 'Maternity Ward', 23, 64)
Row 2430 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 9, 27, 8), 'ICU', 27, 48)
Row 2431 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 9, 27, 34), 'Surgical Ward', 23, 62)
Row 2432 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 9, 28, 9), 'Emergency Ward', 27, 60)
Row 2433 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 9, 28, 12), 'Maternity Ward', 23, 63)
Row 2434 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 9, 28, 19), 'ICU', 27, 47)
Row 2435 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 9, 28, 55), 'Surgical Ward', 23, 62)
Row 2436 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 9, 29, 21), 'Maternity Ward', 23, 62)

Row 2437 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 9, 29, 28), 'ICU', 27, 47)
Row 2438 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 9, 29, 30), 'Emergency Ward', 27, 59)
Row 2439 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 9, 30, 15), 'Surgical Ward', 23, 61)
Row 2440 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 9, 30, 41), 'Maternity Ward', 24, 62)
Row 2441 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 9, 30, 45), 'ICU', 27, 46)
Row 2442 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 9, 30, 51), 'Emergency Ward', 27, 59)
Row 2443 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 9, 31, 35), 'Surgical Ward', 23, 61)
Row 2444 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 9, 32, 2), 'Maternity Ward', 23, 61)
Row 2445 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 9, 32, 10), 'ICU', 27, 46)
Row 2446 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 9, 32, 12), 'Emergency Ward', 27, 59)
Row 2447 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 9, 32, 56), 'Surgical Ward', 23, 61)
Row 2448 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 9, 33, 22), 'Maternity Ward', 23, 61)
Row 2449 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 9, 33, 23), 'ICU', 26, 46)
Row 2450 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 9, 33, 33), 'Emergency Ward', 27, 59)
Row 2451 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 9, 34, 16), 'Surgical Ward', 23, 60)
Row 2452 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 9, 34, 42), 'Maternity Ward', 23, 61)
Row 2453 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 9, 34, 43), 'ICU', 26, 46)
Row 2454 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 9, 34, 54), 'Emergency Ward', 27, 58)
Row 2455 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 9, 35, 38), 'Surgical Ward', 23, 60)
Row 2456 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 9, 36, 2), 'ICU', 26, 46)
Row 2457 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 9, 36, 3), 'Maternity Ward', 23, 61)
Row 2458 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 9, 36, 15), 'Emergency Ward', 26, 60)
Row 2459 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 9, 36, 58), 'Surgical Ward', 23, 59)
Row 2460 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 9, 37, 21), 'ICU', 26, 45)
Row 2461 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 9, 37, 23), 'Maternity Ward', 23, 61)
Row 2462 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 9, 37, 29), 'Emergency Ward', 27, 58)
Row 2463 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 9, 38, 11), 'Surgical Ward', 23, 58)
Row 2464 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 9, 38, 39), 'Emergency Ward', 27, 58)
Row 2465 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 9, 38, 40), 'ICU', 26, 45)
Row 2466 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 9, 38, 44), 'Maternity Ward', 23, 60)
Row 2467 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 9, 39, 20), 'Surgical Ward', 23, 57)
Row 2468 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 9, 39, 59), 'ICU', 26, 45)
Row 2469 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 9, 40), 'Emergency Ward', 27, 57)
Row 2470 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 9, 40, 4), 'Maternity Ward', 23, 59)
Row 2471 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 9, 40, 40), 'Surgical Ward', 23, 56)
Row 2472 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 9, 41, 19), 'ICU', 26, 44)
Row 2473 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 9, 41, 21), 'Emergency Ward', 26, 57)
Row 2474 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 9, 41, 24), 'Maternity Ward', 23, 58)
Row 2475 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 9, 42, 1), 'Surgical Ward', 23, 56)
Row 2476 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 9, 42, 30), 'ICU', 26, 44)
Row 2477 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 9, 42, 38), 'Maternity Ward', 23, 58)
Row 2478 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 9, 42, 42), 'Emergency Ward', 26, 57)
Row 2479 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 9, 43, 21), 'Surgical Ward', 23, 56)
Row 2480 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 9, 43, 38), 'ICU', 26, 44)
Row 2481 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 9, 43, 48), 'Maternity Ward', 23, 57)
Row 2482 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 9, 44, 3), 'Emergency Ward', 26, 58)

Row 2483 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 9, 44, 42), 'Surgical Ward', 23, 56)
Row 2484 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 9, 44, 58), 'ICU', 26, 44)
Row 2485 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 9, 45, 9), 'Maternity Ward', 23, 56)
Row 2486 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 9, 45, 25), 'Emergency Ward', 26, 57)
Row 2487 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 9, 46, 2), 'Surgical Ward', 23, 55)
Row 2488 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 9, 46, 16), 'ICU', 26, 44)
Row 2489 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 9, 46, 29), 'Maternity Ward', 23, 58)
Row 2490 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 9, 46, 46), 'Emergency Ward', 26, 56)
Row 2491 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 9, 47, 22), 'Surgical Ward', 23, 55)
Row 2492 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 9, 47, 35), 'ICU', 26, 43)
Row 2493 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 9, 47, 48), 'Maternity Ward', 23, 56)
Row 2494 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 9, 48, 8), 'Emergency Ward', 26, 56)
Row 2495 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 9, 48, 43), 'Surgical Ward', 23, 55)
Row 2496 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 9, 48, 54), 'ICU', 26, 43)
Row 2497 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 9, 49, 8), 'Maternity Ward', 23, 56)
Row 2498 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 9, 49, 28), 'Emergency Ward', 26, 56)
Row 2499 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 9, 50, 5), 'Surgical Ward', 23, 55)
Row 2500 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 9, 50, 13), 'ICU', 26, 43)
Row 2501 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 9, 50, 29), 'Maternity Ward', 22, 58)
Row 2502 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 9, 50, 49), 'Emergency Ward', 26, 55)
Row 2503 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 9, 51, 24), 'Surgical Ward', 23, 55)
Row 2504 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 9, 51, 33), 'ICU', 26, 43)
Row 2505 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 9, 51, 49), 'Maternity Ward', 23, 55)
Row 2506 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 9, 52, 3), 'Emergency Ward', 26, 56)
Row 2507 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 9, 52, 39), 'Surgical Ward', 23, 54)
Row 2508 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 9, 52, 52), 'ICU', 26, 43)
Row 2509 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 9, 53, 10), 'Maternity Ward', 22, 56)
Row 2510 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 9, 53, 13), 'Emergency Ward', 26, 56)
Row 2511 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 9, 53, 46), 'Surgical Ward', 23, 54)
Row 2512 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 9, 54, 11), 'ICU', 26, 43)
Row 2513 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 9, 54, 30), 'Maternity Ward', 22, 56)
Row 2514 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 9, 54, 34), 'Emergency Ward', 26, 55)
Row 2515 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 9, 55, 8), 'Surgical Ward', 23, 54)
Row 2516 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 9, 55, 30), 'ICU', 26, 43)
Row 2517 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 9, 55, 50), 'Maternity Ward', 23, 55)
Row 2518 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 9, 55, 55), 'Emergency Ward', 26, 55)
Row 2519 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 9, 56, 28), 'Surgical Ward', 22, 54)
Row 2520 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 9, 56, 42), 'ICU', 26, 43)
Row 2521 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 9, 57, 4), 'Maternity Ward', 22, 55)
Row 2522 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 9, 57, 16), 'Emergency Ward', 26, 54)
Row 2523 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 9, 57, 48), 'Surgical Ward', 22, 54)
Row 2524 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 9, 57, 50), 'ICU', 26, 43)
Row 2525 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 9, 58, 13), 'Maternity Ward', 22, 55)
Row 2526 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 9, 58, 38), 'Emergency Ward', 26, 54)
Row 2527 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 9, 59, 8), 'Surgical Ward', 22, 53)
Row 2528 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 9, 59, 10), 'ICU', 26, 43)

Row 2529 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 9, 59, 33), 'Maternity Ward', 22, 55)
Row 2530 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 9, 59, 58), 'Emergency Ward', 26, 54)
Row 2531 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 10, 0, 28), 'ICU', 26, 43)
Row 2532 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 10, 0, 29), 'Surgical Ward', 22, 53)
Row 2533 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 10, 0, 53), 'Maternity Ward', 22, 55)
Row 2534 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 10, 1, 19), 'Emergency Ward', 26, 54)
Row 2535 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 10, 1, 48), 'ICU', 26, 43)
Row 2536 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 10, 1, 49), 'Surgical Ward', 22, 52)
Row 2537 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 10, 2, 14), 'Maternity Ward', 22, 54)
Row 2538 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 10, 2, 40), 'Emergency Ward', 26, 55)
Row 2539 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 10, 3, 6), 'ICU', 26, 42)
Row 2540 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 10, 3, 9), 'Surgical Ward', 22, 52)
Row 2541 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 10, 3, 34), 'Maternity Ward', 22, 53)
Row 2542 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 10, 4, 1), 'Emergency Ward', 26, 54)
Row 2543 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 10, 4, 25), 'ICU', 26, 42)
Row 2544 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 10, 4, 30), 'Surgical Ward', 22, 51)
Row 2545 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 10, 4, 55), 'Maternity Ward', 22, 53)
Row 2546 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 10, 5, 23), 'Emergency Ward', 26, 54)
Row 2547 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 10, 6, 15), 'Maternity Ward', 22, 52)
Row 2548 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 10, 6, 38), 'Emergency Ward', 26, 54)
Row 2549 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 10, 7, 3), 'ICU', 26, 42)
Row 2550 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 10, 7, 4), 'Surgical Ward', 22, 51)
Row 2551 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 10, 7, 35), 'Maternity Ward', 22, 52)
Row 2552 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 10, 7, 46), 'Emergency Ward', 26, 54)
Row 2553 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 10, 8, 13), 'Surgical Ward', 22, 51)
Row 2554 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 10, 8, 22), 'ICU', 26, 42)
Row 2555 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 10, 8, 56), 'Maternity Ward', 22, 50)
Row 2556 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 10, 9, 8), 'Emergency Ward', 26, 53)
Row 2557 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 10, 9, 33), 'Surgical Ward', 22, 50)
Row 2558 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 10, 9, 42), 'ICU', 26, 42)
Row 2559 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 10, 10, 16), 'Maternity Ward', 22, 51)
Row 2560 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 10, 10, 28), 'Emergency Ward', 26, 53)
Row 2561 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 10, 10, 53), 'Surgical Ward', 22, 50)
Row 2562 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 10, 10, 54), 'ICU', 26, 42)
Row 2563 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 10, 11, 30), 'Maternity Ward', 22, 52)
Row 2564 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 10, 11, 50), 'Emergency Ward', 26, 53)
Row 2565 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 10, 12, 1), 'ICU', 26, 42)
Row 2566 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 10, 12, 14), 'Surgical Ward', 22, 50)
Row 2567 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 10, 12, 38), 'Maternity Ward', 22, 51)
Row 2568 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 10, 13, 11), 'Emergency Ward', 26, 53)
Row 2569 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 10, 13, 20), 'ICU', 26, 42)
Row 2570 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 10, 13, 34), 'Surgical Ward', 22, 50)
Row 2571 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 10, 13, 59), 'Maternity Ward', 22, 50)
Row 2572 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 10, 14, 32), 'Emergency Ward', 26, 53)
Row 2573 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 10, 14, 39), 'ICU', 26, 42)
Row 2574 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 10, 14, 56), 'Surgical Ward', 22, 50)
Row 2575 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 10, 15, 19), 'Maternity Ward', 22, 50)

Row 2576 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 10, 15, 53), 'Emergency Ward', 26, 52)
Row 2577 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 10, 15, 58), 'ICU', 26, 42)
Row 2578 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 10, 16, 15), 'Surgical Ward', 22, 50)
Row 2579 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 10, 16, 40), 'Maternity Ward', 22, 50)
Row 2580 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 10, 17, 14), 'Emergency Ward', 26, 52)
Row 2581 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 10, 17, 19), 'ICU', 26, 42)
Row 2582 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 10, 17, 36), 'Surgical Ward', 22, 50)
Row 2583 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 10, 18), 'Maternity Ward', 22, 50)
Row 2584 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 10, 18, 35), 'Emergency Ward', 26, 52)
Row 2585 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 10, 18, 38), 'ICU', 26, 42)
Row 2586 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 10, 18, 56), 'Surgical Ward', 22, 50)
Row 2587 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 10, 19, 20), 'Maternity Ward', 22, 50)
Row 2588 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 10, 19, 56), 'ICU', 26, 42)
Row 2589 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 10, 19, 58), 'Emergency Ward', 26, 51)
Row 2590 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 10, 20, 16), 'Surgical Ward', 22, 50)
Row 2591 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 10, 20, 41), 'Maternity Ward', 22, 50)
Row 2592 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 10, 21, 10), 'Emergency Ward', 26, 51)
Row 2593 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 10, 21, 15), 'ICU', 26, 42)
Row 2594 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 10, 21, 30), 'Surgical Ward', 22, 50)
Row 2595 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 10, 22, 1), 'Maternity Ward', 22, 51)
Row 2596 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 10, 22, 20), 'Emergency Ward', 26, 51)
Row 2597 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 10, 22, 34), 'ICU', 26, 42)
Row 2598 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 10, 22, 39), 'Surgical Ward', 22, 50)
Row 2599 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 10, 23, 21), 'Maternity Ward', 22, 50)
Row 2600 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 10, 23, 42), 'Emergency Ward', 26, 52)
Row 2601 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 10, 23, 53), 'ICU', 26, 42)
Row 2602 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 10, 23, 59), 'Surgical Ward', 22, 50)
Row 2603 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 10, 24, 42), 'Maternity Ward', 22, 50)
Row 2604 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 10, 25, 2), 'Emergency Ward', 26, 52)
Row 2605 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 10, 25, 5), 'ICU', 26, 42)
Row 2606 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 10, 25, 20), 'Surgical Ward', 22, 50)
Row 2607 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 10, 25, 56), 'Maternity Ward', 22, 50)
Row 2608 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 10, 26, 13), 'ICU', 25, 42)
Row 2609 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 10, 26, 23), 'Emergency Ward', 26, 51)
Row 2610 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 10, 26, 40), 'Surgical Ward', 22, 50)
Row 2611 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 10, 27, 4), 'Maternity Ward', 22, 50)
Row 2612 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 10, 27, 32), 'ICU', 26, 42)
Row 2613 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 10, 27, 44), 'Emergency Ward', 26, 51)
Row 2614 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 10, 28, 1), 'Surgical Ward', 22, 50)
Row 2615 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 10, 28, 25), 'Maternity Ward', 22, 50)
Row 2616 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 10, 28, 51), 'ICU', 25, 42)
Row 2617 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 10, 29, 6), 'Emergency Ward', 26, 51)
Row 2618 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 10, 29, 21), 'Surgical Ward', 22, 50)
Row 2619 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 10, 29, 45), 'Maternity Ward', 22, 50)
Row 2620 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 10, 30, 10), 'ICU', 26, 42)
Row 2621 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 10, 30, 26), 'Emergency Ward', 26, 52)

Row 2622 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 10, 30, 41), 'Surgical Ward', 21, 50)
Row 2623 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 10, 31, 5), 'Maternity Ward', 22, 50)
Row 2624 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 10, 31, 29), 'ICU', 26, 42)
Row 2625 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 10, 31, 48), 'Emergency Ward', 26, 52)
Row 2626 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 10, 32, 2), 'Surgical Ward', 22, 50)
Row 2627 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 10, 32, 26), 'Maternity Ward', 22, 50)
Row 2628 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 10, 32, 48), 'ICU', 26, 42)
Row 2629 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 10, 33, 8), 'Emergency Ward', 25, 52)
Row 2630 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 10, 33, 22), 'Surgical Ward', 22, 50)
Row 2631 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 10, 33, 46), 'Maternity Ward', 22, 51)
Row 2632 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 10, 34, 9), 'ICU', 25, 42)
Row 2633 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 10, 34, 30), 'Emergency Ward', 26, 52)
Row 2634 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 10, 34, 43), 'Surgical Ward', 22, 50)
Row 2635 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 10, 35, 6), 'Maternity Ward', 21, 50)
Row 2636 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 10, 35, 26), 'ICU', 25, 42)
Row 2637 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 10, 35, 43), 'Emergency Ward', 25, 52)
Row 2638 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 10, 35, 58), 'Surgical Ward', 22, 50)
Row 2639 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 10, 36, 28), 'Maternity Ward', 22, 50)
Row 2640 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 10, 36, 45), 'ICU', 26, 42)
Row 2641 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 10, 36, 53), 'Emergency Ward', 26, 51)
Row 2642 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 10, 37, 5), 'Surgical Ward', 21, 50)
Row 2643 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 10, 37, 48), 'Maternity Ward', 22, 50)
Row 2644 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 10, 38, 4), 'ICU', 25, 42)
Row 2645 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 10, 38, 14), 'Emergency Ward', 26, 52)
Row 2646 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 10, 38, 25), 'Surgical Ward', 21, 50)
Row 2647 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 10, 39, 8), 'Maternity Ward', 22, 50)
Row 2648 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 10, 39, 16), 'ICU', 25, 42)
Row 2649 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 10, 39, 35), 'Emergency Ward', 25, 52)
Row 2650 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 10, 39, 46), 'Surgical Ward', 22, 50)
Row 2651 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 10, 40, 21), 'Maternity Ward', 22, 50)
Row 2652 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 10, 40, 24), 'ICU', 25, 42)
Row 2653 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 10, 40, 56), 'Emergency Ward', 25, 52)
Row 2654 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 10, 41, 6), 'Surgical Ward', 21, 50)
Row 2655 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 10, 41, 30), 'Maternity Ward', 22, 50)
Row 2656 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 10, 41, 43), 'ICU', 25, 42)
Row 2657 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 10, 42, 18), 'Emergency Ward', 26, 52)
Row 2658 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 10, 42, 28), 'Surgical Ward', 21, 50)
Row 2659 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 10, 42, 50), 'Maternity Ward', 21, 50)
Row 2660 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 10, 43, 2), 'ICU', 25, 42)
Row 2661 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 10, 43, 39), 'Emergency Ward', 26, 51)
Row 2662 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 10, 43, 48), 'Surgical Ward', 21, 50)
Row 2663 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 10, 44, 11), 'Maternity Ward', 22, 50)
Row 2664 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 10, 44, 21), 'ICU', 25, 42)
Row 2665 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 10, 45), 'Emergency Ward', 25, 51)
Row 2666 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 10, 45, 8), 'Surgical Ward', 21, 50)
Row 2667 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 10, 45, 31), 'Maternity Ward', 21, 50)

Row 2668 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 10, 45, 40), 'ICU', 25, 42)
Row 2669 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 10, 46, 21), 'Emergency Ward', 25, 51)
Row 2670 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 10, 46, 28), 'Surgical Ward', 21, 50)
Row 2671 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 10, 46, 51), 'Maternity Ward', 21, 50)
Row 2672 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 10, 46, 59), 'ICU', 25, 42)
Row 2673 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 10, 47, 42), 'Emergency Ward', 25, 51)
Row 2674 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 10, 47, 48), 'Surgical Ward', 21, 50)
Row 2675 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 10, 48, 12), 'Maternity Ward', 22, 52)
Row 2676 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 10, 48, 18), 'ICU', 26, 42)
Row 2677 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 10, 49, 3), 'Emergency Ward', 25, 51)
Row 2678 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 10, 49, 9), 'Surgical Ward', 21, 50)
Row 2679 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 10, 49, 32), 'Maternity Ward', 21, 51)
Row 2680 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 10, 49, 38), 'ICU', 25, 42)
Row 2681 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 10, 50, 18), 'Emergency Ward', 25, 51)
Row 2682 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 10, 50, 22), 'Surgical Ward', 22, 50)
Row 2683 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 10, 50, 44), 'Maternity Ward', 22, 51)
Row 2684 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 10, 50, 58), 'ICU', 25, 42)
Row 2685 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 10, 51, 28), 'Emergency Ward', 25, 51)
Row 2686 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 10, 51, 31), 'Surgical Ward', 21, 50)
Row 2687 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 10, 52, 4), 'Maternity Ward', 21, 50)
Row 2688 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 10, 52, 16), 'ICU', 25, 42)
Row 2689 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 10, 52, 49), 'Emergency Ward', 25, 51)
Row 2690 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 10, 52, 52), 'Surgical Ward', 21, 50)
Row 2691 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 10, 53, 24), 'Maternity Ward', 22, 51)
Row 2692 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 10, 53, 29), 'ICU', 25, 42)
Row 2693 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 10, 54, 9), 'Emergency Ward', 25, 51)
Row 2694 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 10, 54, 12), 'Surgical Ward', 21, 51)
Row 2695 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 10, 54, 35), 'ICU', 25, 42)
Row 2696 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 10, 54, 39), 'Maternity Ward', 21, 50)
Row 2697 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 10, 55, 30), 'Emergency Ward', 25, 49)
Row 2698 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 10, 55, 32), 'Surgical Ward', 21, 50)
Row 2699 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 10, 55, 48), 'Maternity Ward', 21, 53)
Row 2700 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 10, 55, 54), 'ICU', 25, 42)
Row 2701 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 10, 56, 51), 'Emergency Ward', 25, 51)
Row 2702 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 10, 56, 53), 'Surgical Ward', 21, 51)
Row 2703 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 10, 57, 8), 'Maternity Ward', 21, 51)
Row 2704 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 10, 57, 13), 'ICU', 25, 42)
Row 2705 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 10, 58, 12), 'Emergency Ward', 25, 51)
Row 2706 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 10, 58, 13), 'Surgical Ward', 21, 50)
Row 2707 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 10, 58, 29), 'Maternity Ward', 21, 51)
Row 2708 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 10, 58, 33), 'ICU', 25, 42)
Row 2709 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 10, 59, 33), 'Emergency Ward', 25, 51)
Row 2710 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 10, 59, 34), 'Surgical Ward', 21, 51)
Row 2711 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 10, 59, 49), 'Maternity Ward', 21, 51)
Row 2712 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 10, 59, 52), 'ICU', 25, 42)
Row 2713 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 11, 0, 54), 'Emergency Ward', 25, 51)

Row 2714 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 11, 1, 9), 'Maternity Ward', 21, 51)
Row 2715 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 11, 1, 11), 'ICU', 25, 42)
Row 2716 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 11, 2, 14), 'Surgical Ward', 21, 50)
Row 2717 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 11, 2, 15), 'Emergency Ward', 25, 50)
Row 2718 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 11, 2, 29), 'Maternity Ward', 21, 51)
Row 2719 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 11, 2, 30), 'ICU', 25, 42)
Row 2720 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 11, 3, 35), 'Surgical Ward', 21, 50)
Row 2721 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 11, 3, 36), 'Emergency Ward', 25, 51)
Row 2722 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 11, 3, 49), 'ICU', 25, 42)
Row 2723 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 11, 3, 50), 'Maternity Ward', 21, 51)
Row 2724 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 11, 4, 49), 'Surgical Ward', 21, 50)
Row 2725 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 11, 4, 50), 'Emergency Ward', 25, 51)
Row 2726 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 11, 5, 9), 'ICU', 25, 42)
Row 2727 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 11, 5, 10), 'Maternity Ward', 21, 51)
Row 2728 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 11, 5, 59), 'Surgical Ward', 21, 50)
Row 2729 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 11, 6), 'Emergency Ward', 25, 51)
Row 2730 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 11, 6, 28), 'ICU', 25, 42)
Row 2731 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 11, 6, 30), 'Maternity Ward', 21, 51)
Row 2732 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 11, 7, 19), 'Surgical Ward', 21, 50)
Row 2733 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 11, 7, 21), 'Emergency Ward', 25, 52)
Row 2734 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 11, 7, 39), 'ICU', 25, 42)
Row 2735 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 11, 7, 50), 'Maternity Ward', 21, 51)
Row 2736 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 11, 8, 39), 'Surgical Ward', 21, 51)
Row 2737 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 11, 8, 42), 'Emergency Ward', 25, 51)
Row 2738 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 11, 8, 48), 'ICU', 25, 42)
Row 2739 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 11, 9, 4), 'Maternity Ward', 21, 51)
Row 2740 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 11, 9, 59), 'Surgical Ward', 21, 50)
Row 2741 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 11, 10, 3), 'Emergency Ward', 25, 51)
Row 2742 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 11, 10, 6), 'ICU', 25, 42)
Row 2743 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 11, 10, 12), 'Maternity Ward', 21, 53)
Row 2744 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 11, 11, 19), 'Surgical Ward', 21, 51)
Row 2745 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 11, 11, 24), 'Emergency Ward', 25, 52)
Row 2746 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 11, 11, 25), 'ICU', 25, 42)
Row 2747 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 11, 11, 33), 'Maternity Ward', 21, 56)
Row 2748 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 11, 12, 39), 'Surgical Ward', 21, 51)
Row 2749 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 11, 12, 44), 'ICU', 25, 42)
Row 2750 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 11, 12, 45), 'Emergency Ward', 25, 51)
Row 2751 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 11, 12, 53), 'Maternity Ward', 22, 51)
Row 2752 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 11, 14), 'Surgical Ward', 21, 51)
Row 2753 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 11, 14, 3), 'ICU', 25, 42)
Row 2754 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 11, 14, 6), 'Emergency Ward', 25, 51)
Row 2755 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 11, 14, 15), 'Maternity Ward', 21, 51)
Row 2756 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 11, 15, 21), 'Surgical Ward', 21, 51)
Row 2757 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 11, 15, 22), 'ICU', 25, 42)
Row 2758 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 11, 15, 29), 'Emergency Ward', 25, 51)
Row 2759 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 11, 15, 34), 'Maternity Ward', 21, 51)
Row 2760 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 11, 16, 40), 'Surgical Ward', 21, 51)

Row 2761 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 11, 16, 42), 'ICU', 25, 42)
Row 2762 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 11, 16, 49), 'Emergency Ward', 25, 51)
Row 2763 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 11, 16, 55), 'Maternity Ward', 22, 52)
Row 2764 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 11, 18), 'ICU', 25, 42)
Row 2765 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 11, 18, 1), 'Surgical Ward', 21, 51)
Row 2766 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 11, 18, 10), 'Emergency Ward', 25, 52)
Row 2767 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 11, 18, 15), 'Maternity Ward', 21, 51)
Row 2768 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 11, 19, 14), 'Surgical Ward', 21, 51)
Row 2769 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 11, 19, 19), 'ICU', 25, 42)
Row 2770 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 11, 19, 24), 'Emergency Ward', 25, 52)
Row 2771 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 11, 19, 35), 'Maternity Ward', 21, 51)
Row 2772 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 11, 20, 23), 'Surgical Ward', 21, 51)
Row 2773 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 11, 20, 33), 'Emergency Ward', 25, 51)
Row 2774 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 11, 20, 39), 'ICU', 25, 42)
Row 2775 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 11, 20, 55), 'Maternity Ward', 21, 51)
Row 2776 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 11, 21, 44), 'Surgical Ward', 21, 51)
Row 2777 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 11, 21, 50), 'ICU', 25, 42)
Row 2778 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 11, 21, 54), 'Emergency Ward', 25, 51)
Row 2779 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 11, 22, 16), 'Maternity Ward', 21, 51)
Row 2780 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 11, 22, 59), 'ICU', 25, 42)
Row 2781 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 11, 23, 4), 'Surgical Ward', 21, 51)
Row 2782 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 11, 23, 15), 'Emergency Ward', 25, 51)
Row 2783 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 11, 23, 29), 'Maternity Ward', 21, 51)
Row 2784 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 11, 24, 18), 'ICU', 25, 42)
Row 2785 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 11, 24, 25), 'Surgical Ward', 21, 51)
Row 2786 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 11, 24, 36), 'Emergency Ward', 25, 51)
Row 2787 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 11, 24, 39), 'Maternity Ward', 21, 53)
Row 2788 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 11, 25, 36), 'ICU', 25, 42)
Row 2789 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 11, 25, 59), 'Emergency Ward', 25, 51)
Row 2790 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 11, 26), 'Maternity Ward', 21, 52)
Row 2791 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 11, 26, 55), 'ICU', 25, 42)
Row 2792 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 11, 27, 5), 'Surgical Ward', 21, 51)
Row 2793 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 11, 27, 19), 'Emergency Ward', 25, 52)
Row 2794 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 11, 27, 20), 'Maternity Ward', 21, 52)
Row 2795 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 11, 28, 14), 'ICU', 25, 42)
Row 2796 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 11, 28, 26), 'Surgical Ward', 21, 51)
Row 2797 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 11, 28, 39), 'Maternity Ward', 21, 52)
Row 2798 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 11, 28, 40), 'Emergency Ward', 25, 52)
Row 2799 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 11, 29, 33), 'ICU', 25, 42)
Row 2800 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 11, 29, 46), 'Surgical Ward', 21, 51)
Row 2801 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 11, 30), 'Maternity Ward', 21, 52)
Row 2802 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 11, 30, 1), 'Emergency Ward', 25, 52)
Row 2803 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 11, 30, 52), 'ICU', 25, 42)
Row 2804 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 11, 31, 6), 'Surgical Ward', 21, 51)
Row 2805 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 11, 31, 20), 'Maternity Ward', 21, 52)
Row 2806 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 11, 31, 22), 'Emergency Ward', 25, 52)

Row 2807 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 11, 32, 11), 'ICU', 25, 42)
Row 2808 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 11, 32, 40), 'Maternity Ward', 21, 52)
Row 2809 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 11, 32, 43), 'Emergency Ward', 25, 51)
Row 2810 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 11, 33, 31), 'ICU', 25, 42)
Row 2811 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 11, 33, 40), 'Surgical Ward', 21, 51)
Row 2812 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 11, 33, 59), 'Emergency Ward', 25, 52)
Row 2813 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 11, 34, 1), 'Maternity Ward', 21, 53)
Row 2814 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 11, 34, 49), 'Surgical Ward', 21, 51)
Row 2815 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 11, 34, 50), 'ICU', 25, 42)
Row 2816 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 11, 35, 6), 'Emergency Ward', 25, 51)
Row 2817 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 11, 35, 21), 'Maternity Ward', 21, 51)
Row 2818 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 11, 36, 2), 'ICU', 25, 42)
Row 2819 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 11, 36, 10), 'Surgical Ward', 21, 51)
Row 2820 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 11, 36, 29), 'Emergency Ward', 25, 52)
Row 2821 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 11, 36, 41), 'Maternity Ward', 21, 52)
Row 2822 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 11, 37, 9), 'ICU', 25, 42)
Row 2823 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 11, 37, 31), 'Surgical Ward', 21, 51)
Row 2824 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 11, 37, 49), 'Emergency Ward', 25, 51)
Row 2825 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 11, 37, 55), 'Maternity Ward', 21, 51)
Row 2826 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 11, 38, 29), 'ICU', 25, 42)
Row 2827 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 11, 38, 51), 'Surgical Ward', 21, 51)
Row 2828 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 11, 39, 4), 'Maternity Ward', 22, 52)
Row 2829 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 11, 39, 10), 'Emergency Ward', 25, 51)
Row 2830 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 11, 39, 49), 'ICU', 25, 42)
Row 2831 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 11, 40, 11), 'Surgical Ward', 21, 51)
Row 2832 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 11, 40, 24), 'Maternity Ward', 21, 51)
Row 2833 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 11, 40, 31), 'Emergency Ward', 25, 51)
Row 2834 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 11, 41, 7), 'ICU', 25, 42)
Row 2835 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 11, 41, 31), 'Surgical Ward', 21, 51)
Row 2836 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 11, 41, 45), 'Maternity Ward', 21, 51)
Row 2837 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 11, 41, 52), 'Emergency Ward', 25, 52)
Row 2838 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 11, 42, 26), 'ICU', 25, 42)
Row 2839 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 11, 42, 52), 'Surgical Ward', 21, 51)
Row 2840 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 11, 43, 5), 'Maternity Ward', 21, 52)
Row 2841 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 11, 43, 13), 'Emergency Ward', 25, 52)
Row 2842 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 11, 43, 45), 'ICU', 25, 42)
Row 2843 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 11, 44, 12), 'Surgical Ward', 21, 51)
Row 2844 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 11, 44, 25), 'Maternity Ward', 21, 53)
Row 2845 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 11, 44, 34), 'Emergency Ward', 25, 52)
Row 2846 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 11, 45, 33), 'Surgical Ward', 21, 50)
Row 2847 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 11, 45, 46), 'Maternity Ward', 22, 55)
Row 2848 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 11, 45, 55), 'Emergency Ward', 25, 53)
Row 2849 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 11, 46, 23), 'ICU', 26, 42)
Row 2850 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 11, 46, 53), 'Surgical Ward', 22, 50)
Row 2851 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 11, 47, 6), 'Maternity Ward', 21, 52)
Row 2852 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 11, 47, 16), 'Emergency Ward', 25, 53)
Row 2853 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 11, 47, 42), 'ICU', 26, 42)

Row 2854 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 11, 48, 6), 'Surgical Ward', 22, 51)
Row 2855 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 11, 48, 26), 'Maternity Ward', 21, 53)
Row 2856 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 11, 48, 30), 'Emergency Ward', 25, 53)
Row 2857 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 11, 49, 1), 'ICU', 26, 42)
Row 2858 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 11, 49, 15), 'Surgical Ward', 22, 51)
Row 2859 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 11, 49, 40), 'Emergency Ward', 25, 53)
Row 2860 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 11, 49, 47), 'Maternity Ward', 21, 53)
Row 2861 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 11, 50, 14), 'ICU', 26, 42)
Row 2862 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 11, 50, 36), 'Surgical Ward', 22, 51)
Row 2863 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 11, 51, 1), 'Emergency Ward', 25, 53)
Row 2864 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 11, 51, 9), 'Maternity Ward', 21, 55)
Row 2865 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 11, 51, 21), 'ICU', 26, 42)
Row 2866 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 11, 51, 56), 'Surgical Ward', 22, 51)
Row 2867 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 11, 52, 21), 'Maternity Ward', 21, 56)
Row 2868 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 11, 52, 22), 'Emergency Ward', 25, 54)
Row 2869 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 11, 52, 40), 'ICU', 26, 42)
Row 2870 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 11, 53, 17), 'Surgical Ward', 22, 51)
Row 2871 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 11, 53, 29), 'Maternity Ward', 21, 56)
Row 2872 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 11, 53, 43), 'Emergency Ward', 25, 54)
Row 2873 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 11, 53, 59), 'ICU', 26, 42)
Row 2874 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 11, 54, 38), 'Surgical Ward', 22, 51)
Row 2875 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 11, 54, 50), 'Maternity Ward', 21, 57)
Row 2876 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 11, 55, 4), 'Emergency Ward', 25, 54)
Row 2877 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 11, 55, 19), 'ICU', 26, 42)
Row 2878 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 11, 55, 59), 'Surgical Ward', 22, 51)
Row 2879 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 11, 56, 10), 'Maternity Ward', 21, 58)
Row 2880 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 11, 56, 26), 'Emergency Ward', 25, 54)
Row 2881 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 11, 56, 38), 'ICU', 26, 43)
Row 2882 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 11, 57, 19), 'Surgical Ward', 22, 55)
Row 2883 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 11, 57, 30), 'Maternity Ward', 22, 58)
Row 2884 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 11, 57, 46), 'Emergency Ward', 25, 55)
Row 2885 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 11, 57, 56), 'ICU', 26, 43)
Row 2886 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 11, 58, 39), 'Surgical Ward', 22, 57)
Row 2887 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 11, 58, 52), 'Maternity Ward', 22, 60)
Row 2888 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 11, 59, 9), 'Emergency Ward', 25, 55)
Row 2889 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 11, 59, 15), 'ICU', 26, 43)
Row 2890 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 11, 59, 59), 'Surgical Ward', 22, 57)
Row 2891 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 12, 0, 11), 'Maternity Ward', 22, 61)
Row 2892 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 12, 0, 29), 'Emergency Ward', 25, 55)
Row 2893 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 12, 0, 34), 'ICU', 26, 43)
Row 2894 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 12, 1, 19), 'Surgical Ward', 22, 58)
Row 2895 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 12, 1, 32), 'Maternity Ward', 22, 62)
Row 2896 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 12, 1, 50), 'Emergency Ward', 25, 56)
Row 2897 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 12, 1, 54), 'ICU', 26, 43)
Row 2898 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 12, 2, 33), 'Surgical Ward', 22, 59)
Row 2899 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 12, 2, 52), 'Maternity Ward', 22, 62)
Row 2900 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 12, 3, 4), 'Emergency Ward', 25, 56)

Row 2901 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 12, 3, 12), 'ICU', 26, 43)
Row 2902 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 12, 3, 42), 'Surgical Ward', 23, 58)
Row 2903 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 12, 4, 12), 'Maternity Ward', 22, 62)
Row 2904 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 12, 4, 13), 'Emergency Ward', 25, 56)
Row 2905 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 12, 4, 24), 'ICU', 26, 43)
Row 2906 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 12, 5, 2), 'Surgical Ward', 23, 59)
Row 2907 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 12, 5, 32), 'ICU', 27, 42)
Row 2908 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 12, 5, 33), 'Maternity Ward', 22, 63)
Row 2909 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 12, 5, 34), 'Emergency Ward', 25, 58)
Row 2910 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 12, 6, 22), 'Surgical Ward', 23, 60)
Row 2911 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 12, 6, 46), 'Maternity Ward', 22, 63)
Row 2912 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 12, 6, 51), 'ICU', 27, 42)
Row 2913 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 12, 6, 55), 'Emergency Ward', 25, 58)
Row 2914 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 12, 7, 43), 'Surgical Ward', 23, 61)
Row 2915 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 12, 7, 55), 'Maternity Ward', 22, 64)
Row 2916 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 12, 8, 10), 'ICU', 27, 43)
Row 2917 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 12, 8, 17), 'Emergency Ward', 25, 59)
Row 2918 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 12, 9, 3), 'Surgical Ward', 23, 61)
Row 2919 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 12, 9, 15), 'Maternity Ward', 22, 65)
Row 2920 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 12, 9, 29), 'ICU', 27, 43)
Row 2921 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 12, 9, 39), 'Emergency Ward', 25, 60)
Row 2922 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 12, 10, 24), 'Surgical Ward', 23, 62)
Row 2923 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 12, 10, 36), 'Maternity Ward', 22, 65)
Row 2924 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 12, 10, 49), 'ICU', 27, 44)
Row 2925 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 12, 10, 59), 'Emergency Ward', 25, 60)
Row 2926 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 12, 11, 44), 'Surgical Ward', 23, 62)
Row 2927 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 12, 11, 56), 'Maternity Ward', 22, 66)
Row 2928 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 12, 12, 9), 'ICU', 27, 44)
Row 2929 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 12, 12, 20), 'Emergency Ward', 26, 60)
Row 2930 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 12, 13, 5), 'Surgical Ward', 23, 63)
Row 2931 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 12, 13, 17), 'Maternity Ward', 22, 66)
Row 2932 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 12, 13, 28), 'ICU', 27, 45)
Row 2933 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 12, 13, 41), 'Emergency Ward', 26, 60)
Row 2934 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 12, 14, 25), 'Surgical Ward', 23, 63)
Row 2935 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 12, 14, 38), 'Maternity Ward', 22, 67)
Row 2936 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 12, 14, 46), 'ICU', 27, 45)
Row 2937 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 12, 15, 2), 'Emergency Ward', 26, 60)
Row 2938 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 12, 15, 46), 'Surgical Ward', 23, 64)
Row 2939 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 12, 15, 59), 'Maternity Ward', 22, 67)
Row 2940 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 12, 16, 6), 'ICU', 27, 46)
Row 2941 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 12, 16, 23), 'Emergency Ward', 26, 60)
Row 2942 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 12, 16, 59), 'Surgical Ward', 23, 64)
Row 2943 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 12, 17, 19), 'Maternity Ward', 22, 67)
Row 2944 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 12, 17, 24), 'ICU', 27, 46)
Row 2945 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 12, 17, 38), 'Emergency Ward', 26, 60)
Row 2946 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 12, 18, 9), 'Surgical Ward', 23, 64)
Row 2947 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 12, 18, 36), 'ICU', 27, 47)

Row 2948 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 12, 18, 39), 'Maternity Ward', 22, 68)
Row 2949 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 12, 18, 48), 'Emergency Ward', 26, 60)
Row 2950 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 12, 19, 29), 'Surgical Ward', 23, 64)
Row 2951 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 12, 19, 45), 'ICU', 27, 47)
Row 2952 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 12, 19, 59), 'Maternity Ward', 22, 68)
Row 2953 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 12, 20, 9), 'Emergency Ward', 26, 60)
Row 2954 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 12, 20, 50), 'Surgical Ward', 23, 64)
Row 2955 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 12, 21, 3), 'ICU', 27, 47)
Row 2956 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 12, 21, 12), 'Maternity Ward', 22, 69)
Row 2957 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 12, 21, 29), 'Emergency Ward', 26, 60)
Row 2958 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 12, 22, 9), 'Surgical Ward', 23, 64)
Row 2959 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 12, 22, 21), 'Maternity Ward', 22, 68)
Row 2960 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 12, 22, 22), 'ICU', 27, 48)
Row 2961 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 12, 22, 50), 'Emergency Ward', 26, 60)
Row 2962 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 12, 23, 30), 'Surgical Ward', 23, 64)
Row 2963 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 12, 24, 11), 'Emergency Ward', 26, 60)
Row 2964 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 12, 24, 50), 'Surgical Ward', 23, 65)
Row 2965 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 12, 25), 'ICU', 27, 49)
Row 2966 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 12, 25, 2), 'Maternity Ward', 22, 68)
Row 2967 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 12, 25, 32), 'Emergency Ward', 26, 61)
Row 2968 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 12, 26, 11), 'Surgical Ward', 23, 65)
Row 2969 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 12, 26, 19), 'ICU', 27, 50)
Row 2970 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 12, 26, 22), 'Maternity Ward', 22, 68)
Row 2971 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 12, 26, 53), 'Emergency Ward', 26, 61)
Row 2972 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 12, 27, 31), 'Surgical Ward', 23, 65)
Row 2973 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 12, 27, 39), 'ICU', 27, 51)
Row 2974 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 12, 27, 42), 'Maternity Ward', 22, 68)
Row 2975 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 12, 28, 15), 'Emergency Ward', 26, 61)
Row 2976 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 12, 28, 52), 'Surgical Ward', 23, 65)
Row 2977 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 12, 28, 59), 'ICU', 24, 49)
Row 2978 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 12, 29, 3), 'Maternity Ward', 22, 68)
Row 2979 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 12, 29, 36), 'Emergency Ward', 26, 61)
Row 2980 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 12, 30, 12), 'Surgical Ward', 23, 65)
Row 2981 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 12, 30, 17), 'ICU', 27, 52)
Row 2982 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 12, 30, 23), 'Maternity Ward', 22, 68)
Row 2983 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 12, 30, 57), 'Emergency Ward', 26, 61)
Row 2984 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 12, 31, 25), 'Surgical Ward', 23, 64)
Row 2985 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 12, 31, 36), 'ICU', 27, 52)
Row 2986 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 12, 31, 43), 'Maternity Ward', 22, 68)
Row 2987 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 12, 32, 11), 'Emergency Ward', 26, 61)
Row 2988 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 12, 32, 34), 'Surgical Ward', 23, 64)
Row 2989 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 12, 32, 49), 'ICU', 27, 52)
Row 2990 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 12, 33, 4), 'Maternity Ward', 22, 68)
Row 2991 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 12, 33, 21), 'Emergency Ward', 26, 61)
Row 2992 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 12, 33, 55), 'Surgical Ward', 23, 64)
Row 2993 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 12, 33, 56), 'ICU', 27, 52)
Row 2994 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 12, 34, 24), 'Maternity Ward', 22, 68)

Row 2995 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 12, 34, 43), 'Emergency Ward', 26, 61)
Row 2996 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 12, 35, 15), 'ICU', 24, 49)
Row 2997 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 12, 35, 16), 'Surgical Ward', 23, 64)
Row 2998 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 12, 35, 39), 'Maternity Ward', 22, 68)
Row 2999 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 12, 36, 3), 'Emergency Ward', 26, 61)
Row 3000 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 12, 36, 34), 'ICU', 27, 52)
Row 3001 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 12, 36, 36), 'Surgical Ward', 23, 64)
Row 3002 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 12, 36, 47), 'Maternity Ward', 22, 68)
Row 3003 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 12, 37, 24), 'Emergency Ward', 26, 61)
Row 3004 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 12, 37, 53), 'ICU', 27, 52)
Row 3005 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 12, 37, 56), 'Surgical Ward', 23, 64)
Row 3006 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 12, 38, 8), 'Maternity Ward', 23, 67)
Row 3007 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 12, 38, 45), 'Emergency Ward', 26, 61)
Row 3008 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 12, 39, 12), 'ICU', 27, 52)
Row 3009 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 12, 39, 17), 'Surgical Ward', 23, 64)
Row 3010 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 12, 39, 29), 'Maternity Ward', 22, 67)
Row 3011 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 12, 40, 6), 'Emergency Ward', 26, 61)
Row 3012 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 12, 40, 31), 'ICU', 27, 51)
Row 3013 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 12, 40, 38), 'Surgical Ward', 23, 64)
Row 3014 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 12, 40, 49), 'Maternity Ward', 22, 67)
Row 3015 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 12, 41, 28), 'Emergency Ward', 26, 61)
Row 3016 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 12, 41, 50), 'ICU', 27, 50)
Row 3017 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 12, 41, 59), 'Surgical Ward', 23, 64)
Row 3018 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 12, 42, 9), 'Maternity Ward', 22, 67)
Row 3019 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 12, 42, 49), 'Emergency Ward', 26, 61)
Row 3020 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 12, 43, 9), 'ICU', 27, 49)
Row 3021 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 12, 43, 19), 'Surgical Ward', 23, 64)
Row 3022 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 12, 43, 29), 'Maternity Ward', 22, 66)
Row 3023 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 12, 44, 9), 'Emergency Ward', 26, 60)
Row 3024 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 12, 44, 29), 'ICU', 27, 48)
Row 3025 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 12, 44, 39), 'Surgical Ward', 23, 64)
Row 3026 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 12, 44, 49), 'Maternity Ward', 22, 66)
Row 3027 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 12, 45, 31), 'Emergency Ward', 26, 61)
Row 3028 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 12, 45, 49), 'ICU', 27, 48)
Row 3029 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 12, 45, 52), 'Surgical Ward', 23, 64)
Row 3030 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 12, 46, 10), 'Maternity Ward', 22, 66)
Row 3031 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 12, 46, 44), 'Emergency Ward', 26, 61)
Row 3032 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 12, 46, 59), 'ICU', 27, 48)
Row 3033 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 12, 47, 1), 'Surgical Ward', 23, 64)
Row 3034 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 12, 47, 30), 'Maternity Ward', 23, 65)
Row 3035 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 12, 47, 54), 'Emergency Ward', 26, 60)
Row 3036 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 12, 48, 8), 'ICU', 27, 47)
Row 3037 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 12, 48, 21), 'Surgical Ward', 23, 64)
Row 3038 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 12, 48, 50), 'Maternity Ward', 23, 65)
Row 3039 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 12, 49, 15), 'Emergency Ward', 26, 61)
Row 3040 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 12, 49, 26), 'ICU', 27, 48)
Row 3041 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 12, 49, 42), 'Surgical Ward', 23, 64)

Row 3042 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 12, 50, 4), 'Maternity Ward', 23, 65)
Row 3043 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 12, 50, 36), 'Emergency Ward', 26, 60)
Row 3044 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 12, 50, 45), 'ICU', 27, 47)
Row 3045 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 12, 51, 2), 'Surgical Ward', 23, 63)
Row 3046 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 12, 51, 12), 'Maternity Ward', 23, 65)
Row 3047 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 12, 51, 59), 'Emergency Ward', 26, 60)
Row 3048 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 12, 52, 4), 'ICU', 27, 48)
Row 3049 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 12, 52, 23), 'Surgical Ward', 23, 63)
Row 3050 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 12, 52, 33), 'Maternity Ward', 23, 65)
Row 3051 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 12, 53, 19), 'Emergency Ward', 26, 60)
Row 3052 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 12, 53, 23), 'ICU', 27, 47)
Row 3053 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 12, 53, 43), 'Surgical Ward', 23, 63)
Row 3054 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 12, 53, 53), 'Maternity Ward', 23, 65)
Row 3055 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 12, 54, 40), 'Emergency Ward', 26, 60)
Row 3056 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 12, 54, 43), 'ICU', 27, 47)
Row 3057 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 12, 55, 4), 'Surgical Ward', 23, 63)
Row 3058 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 12, 55, 14), 'Maternity Ward', 23, 65)
Row 3059 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 12, 56, 1), 'Emergency Ward', 26, 60)
Row 3060 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 12, 56, 2), 'ICU', 24, 47)
Row 3061 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 12, 56, 24), 'Surgical Ward', 23, 63)
Row 3062 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 12, 56, 34), 'Maternity Ward', 23, 65)
Row 3063 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 12, 57, 21), 'ICU', 27, 47)
Row 3064 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 12, 57, 22), 'Emergency Ward', 26, 60)
Row 3065 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 12, 57, 45), 'Surgical Ward', 23, 63)
Row 3066 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 12, 57, 54), 'Maternity Ward', 23, 65)
Row 3067 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 12, 58, 40), 'ICU', 27, 47)
Row 3068 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 12, 58, 43), 'Emergency Ward', 26, 60)
Row 3069 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 12, 59, 5), 'Surgical Ward', 23, 63)
Row 3070 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 12, 59, 15), 'Maternity Ward', 23, 64)
Row 3071 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 12, 59, 59), 'ICU', 24, 47)
Row 3072 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 13, 0, 4), 'Emergency Ward', 26, 60)
Row 3073 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 13, 0, 19), 'Surgical Ward', 23, 62)
Row 3074 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 13, 0, 35), 'Maternity Ward', 23, 64)
Row 3075 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 13, 1, 11), 'ICU', 24, 47)
Row 3076 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 13, 1, 19), 'Emergency Ward', 26, 60)
Row 3077 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 13, 1, 29), 'Surgical Ward', 23, 62)
Row 3078 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 13, 1, 56), 'Maternity Ward', 23, 64)
Row 3079 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 13, 2, 19), 'ICU', 27, 47)
Row 3080 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 13, 2, 29), 'Emergency Ward', 26, 60)
Row 3081 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 13, 2, 49), 'Surgical Ward', 24, 62)
Row 3082 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 13, 3, 16), 'Maternity Ward', 23, 64)
Row 3083 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 13, 3, 39), 'ICU', 27, 47)
Row 3084 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 13, 3, 49), 'Emergency Ward', 26, 60)
Row 3085 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 13, 4, 9), 'Surgical Ward', 24, 62)
Row 3086 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 13, 4, 30), 'Maternity Ward', 23, 64)
Row 3087 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 13, 4, 58), 'ICU', 27, 47)
Row 3088 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 13, 5, 10), 'Emergency Ward', 26, 60)

Row 3089 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 13, 5, 29), 'Surgical Ward', 24, 62)
Row 3090 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 13, 5, 39), 'Maternity Ward', 23, 64)
Row 3091 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 13, 6, 16), 'ICU', 24, 47)
Row 3092 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 13, 6, 31), 'Emergency Ward', 26, 60)
Row 3093 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 13, 6, 49), 'Surgical Ward', 23, 62)
Row 3094 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 13, 6, 59), 'Maternity Ward', 23, 64)
Row 3095 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 13, 7, 35), 'ICU', 24, 47)
Row 3096 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 13, 7, 52), 'Emergency Ward', 26, 60)
Row 3097 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 13, 8, 10), 'Surgical Ward', 24, 62)
Row 3098 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 13, 8, 19), 'Maternity Ward', 23, 64)
Row 3099 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 13, 8, 54), 'ICU', 27, 47)
Row 3100 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 13, 9, 13), 'Emergency Ward', 26, 60)
Row 3101 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 13, 9, 30), 'Surgical Ward', 24, 62)
Row 3102 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 13, 9, 40), 'Maternity Ward', 23, 64)
Row 3103 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 13, 10, 13), 'ICU', 27, 47)
Row 3104 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 13, 10, 35), 'Emergency Ward', 26, 60)
Row 3105 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 13, 10, 51), 'Surgical Ward', 24, 62)
Row 3106 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 13, 11), 'Maternity Ward', 23, 64)
Row 3107 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 13, 11, 33), 'ICU', 28, 47)
Row 3108 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 13, 11, 56), 'Emergency Ward', 26, 60)
Row 3109 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 13, 12, 20), 'Maternity Ward', 23, 64)
Row 3110 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 13, 12, 52), 'ICU', 24, 47)
Row 3111 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 13, 13, 18), 'Emergency Ward', 26, 60)
Row 3112 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 13, 13, 32), 'Surgical Ward', 24, 62)
Row 3113 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 13, 13, 41), 'Maternity Ward', 23, 64)
Row 3114 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 13, 14, 11), 'ICU', 27, 47)
Row 3115 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 13, 14, 39), 'Emergency Ward', 26, 60)
Row 3116 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 13, 14, 45), 'Surgical Ward', 24, 62)
Row 3117 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 13, 15, 1), 'Maternity Ward', 23, 64)
Row 3118 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 13, 15, 23), 'ICU', 28, 47)
Row 3119 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 13, 15, 52), 'Emergency Ward', 26, 60)
Row 3120 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 13, 15, 54), 'Surgical Ward', 23, 62)
Row 3121 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 13, 16, 21), 'Maternity Ward', 23, 64)
Row 3122 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 13, 16, 31), 'ICU', 28, 47)
Row 3123 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 13, 17, 2), 'Emergency Ward', 26, 60)
Row 3124 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 13, 17, 14), 'Surgical Ward', 24, 62)
Row 3125 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 13, 17, 42), 'Maternity Ward', 23, 64)
Row 3126 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 13, 17, 50), 'ICU', 27, 47)
Row 3127 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 13, 18, 23), 'Emergency Ward', 26, 60)
Row 3128 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 13, 18, 35), 'Surgical Ward', 24, 62)
Row 3129 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 13, 18, 56), 'Maternity Ward', 23, 64)
Row 3130 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 13, 19, 9), 'ICU', 24, 46)
Row 3131 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 13, 19, 44), 'Emergency Ward', 26, 60)
Row 3132 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 13, 19, 55), 'Surgical Ward', 24, 62)
Row 3133 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 13, 20, 4), 'Maternity Ward', 23, 64)
Row 3134 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 13, 20, 29), 'ICU', 27, 47)

Row 3135 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 13, 21, 5), 'Emergency Ward', 26, 60)
Row 3136 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 13, 21, 16), 'Surgical Ward', 24, 62)
Row 3137 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 13, 21, 48), 'ICU', 27, 46)
Row 3138 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 13, 22, 26), 'Emergency Ward', 26, 60)
Row 3139 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 13, 22, 38), 'Surgical Ward', 24, 62)
Row 3140 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 13, 22, 45), 'Maternity Ward', 23, 63)
Row 3141 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 13, 23, 6), 'ICU', 27, 46)
Row 3142 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 13, 23, 48), 'Emergency Ward', 26, 60)
Row 3143 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 13, 23, 57), 'Surgical Ward', 24, 62)
Row 3144 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 13, 24, 6), 'Maternity Ward', 23, 63)
Row 3145 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 13, 24, 25), 'ICU', 27, 46)
Row 3146 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 13, 25, 9), 'Emergency Ward', 26, 60)
Row 3147 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 13, 25, 19), 'Surgical Ward', 24, 61)
Row 3148 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 13, 25, 26), 'Maternity Ward', 23, 63)
Row 3149 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 13, 25, 44), 'ICU', 27, 46)
Row 3150 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 13, 26, 30), 'Emergency Ward', 26, 60)
Row 3151 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 13, 26, 39), 'Surgical Ward', 24, 61)
Row 3152 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 13, 26, 46), 'Maternity Ward', 23, 63)
Row 3153 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 13, 27, 3), 'ICU', 27, 46)
Row 3154 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 13, 27, 51), 'Emergency Ward', 26, 60)
Row 3155 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 13, 27, 59), 'Surgical Ward', 24, 61)
Row 3156 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 13, 28, 7), 'Maternity Ward', 23, 64)
Row 3157 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 13, 28, 23), 'ICU', 27, 46)
Row 3158 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 13, 29, 12), 'Surgical Ward', 24, 61)
Row 3159 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 13, 29, 13), 'Emergency Ward', 26, 60)
Row 3160 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 13, 29, 29), 'Maternity Ward', 23, 63)
Row 3161 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 13, 29, 35), 'ICU', 27, 46)
Row 3162 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 13, 30, 21), 'Surgical Ward', 24, 61)
Row 3163 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 13, 30, 26), 'Emergency Ward', 26, 60)
Row 3164 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 13, 30, 42), 'ICU', 27, 46)
Row 3165 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 13, 30, 49), 'Maternity Ward', 23, 63)
Row 3166 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 13, 31, 35), 'Emergency Ward', 26, 60)
Row 3167 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 13, 31, 41), 'Surgical Ward', 24, 61)
Row 3168 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 13, 32, 1), 'ICU', 28, 46)
Row 3169 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 13, 32, 9), 'Maternity Ward', 23, 63)
Row 3170 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 13, 32, 57), 'Emergency Ward', 26, 60)
Row 3171 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 13, 33, 2), 'Surgical Ward', 24, 61)
Row 3172 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 13, 33, 21), 'ICU', 27, 46)
Row 3173 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 13, 33, 22), 'Maternity Ward', 23, 62)
Row 3174 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 13, 34, 19), 'Emergency Ward', 26, 60)
Row 3175 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 13, 34, 23), 'Surgical Ward', 24, 61)
Row 3176 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 13, 34, 30), 'Maternity Ward', 23, 62)
Row 3177 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 13, 34, 40), 'ICU', 27, 46)
Row 3178 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 13, 35, 39), 'Emergency Ward', 26, 60)
Row 3179 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 13, 35, 42), 'Surgical Ward', 24, 61)
Row 3180 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 13, 35, 51), 'Maternity Ward', 23, 62)
Row 3181 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 13, 35, 59), 'ICU', 24, 45)
Row 3182 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 13, 37), 'Emergency Ward', 26, 60)

Row 3183 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 13, 37, 3), 'Surgical Ward', 24, 61)
Row 3184 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 13, 37, 11), 'Maternity Ward', 23, 62)
Row 3185 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 13, 37, 19), 'ICU', 24, 45)
Row 3186 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 13, 38, 21), 'Emergency Ward', 26, 60)
Row 3187 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 13, 38, 23), 'Surgical Ward', 24, 61)
Row 3188 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 13, 38, 32), 'Maternity Ward', 23, 62)
Row 3189 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 13, 38, 38), 'ICU', 24, 45)
Row 3190 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 13, 39, 42), 'Emergency Ward', 26, 60)
Row 3191 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 13, 39, 44), 'Surgical Ward', 24, 61)
Row 3192 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 13, 39, 52), 'Maternity Ward', 23, 62)
Row 3193 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 13, 39, 56), 'ICU', 27, 45)
Row 3194 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 13, 41, 3), 'Emergency Ward', 26, 60)
Row 3195 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 13, 41, 4), 'Surgical Ward', 24, 61)
Row 3196 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 13, 41, 12), 'Maternity Ward', 23, 62)
Row 3197 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 13, 41, 15), 'ICU', 27, 45)
Row 3198 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 13, 42, 24), 'Emergency Ward', 27, 59)
Row 3199 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 13, 42, 25), 'Surgical Ward', 24, 61)
Row 3200 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 13, 42, 33), 'Maternity Ward', 23, 62)
Row 3201 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 13, 42, 34), 'ICU', 27, 45)
Row 3202 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 13, 43, 39), 'Surgical Ward', 24, 61)
Row 3203 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 13, 43, 45), 'Emergency Ward', 26, 60)
Row 3204 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 13, 43, 47), 'ICU', 27, 45)
Row 3205 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 13, 43, 53), 'Maternity Ward', 23, 62)
Row 3206 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 13, 44, 49), 'Surgical Ward', 24, 61)
Row 3207 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 13, 44, 54), 'ICU', 27, 45)
Row 3208 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 13, 45), 'Emergency Ward', 27, 59)
Row 3209 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 13, 45, 13), 'Maternity Ward', 23, 62)
Row 3210 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 13, 46, 9), 'Surgical Ward', 24, 61)
Row 3211 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 13, 46, 10), 'Emergency Ward', 26, 60)
Row 3212 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 13, 46, 13), 'ICU', 27, 45)
Row 3213 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 13, 46, 34), 'Maternity Ward', 23, 63)
Row 3214 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 13, 47, 29), 'Surgical Ward', 24, 61)
Row 3215 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 13, 47, 30), 'Emergency Ward', 26, 60)
Row 3216 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 13, 47, 32), 'ICU', 27, 45)
Row 3217 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 13, 47, 49), 'Maternity Ward', 23, 63)
Row 3218 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 13, 48, 49), 'Surgical Ward', 24, 61)
Row 3219 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 13, 48, 51), 'Emergency Ward', 26, 60)
Row 3220 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 13, 48, 56), 'Maternity Ward', 23, 62)
Row 3221 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 13, 50, 9), 'Surgical Ward', 24, 61)
Row 3222 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 13, 50, 11), 'ICU', 27, 45)
Row 3223 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 13, 50, 13), 'Emergency Ward', 26, 60)
Row 3224 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 13, 50, 17), 'Maternity Ward', 23, 62)
Row 3225 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 13, 51, 30), 'ICU', 24, 45)
Row 3226 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 13, 51, 31), 'Surgical Ward', 24, 61)
Row 3227 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 13, 51, 34), 'Emergency Ward', 26, 60)
Row 3228 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 13, 51, 38), 'Maternity Ward', 23, 62)
Row 3229 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 13, 52, 49), 'ICU', 28, 45)

Row 3230 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 13, 52, 50), 'Surgical Ward', 24, 61)
Row 3231 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 13, 52, 55), 'Emergency Ward', 26, 60)
Row 3232 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 13, 52, 59), 'Maternity Ward', 23, 62)
Row 3233 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 13, 54, 9), 'ICU', 27, 45)
Row 3234 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 13, 54, 11), 'Surgical Ward', 24, 61)
Row 3235 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 13, 54, 16), 'Emergency Ward', 26, 60)
Row 3236 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 13, 54, 19), 'Maternity Ward', 23, 62)
Row 3237 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 13, 55, 28), 'ICU', 28, 45)
Row 3238 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 13, 55, 31), 'Surgical Ward', 24, 61)
Row 3239 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 13, 55, 38), 'Emergency Ward', 27, 59)
Row 3240 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 13, 55, 39), 'Maternity Ward', 23, 62)
Row 3241 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 13, 56, 46), 'ICU', 24, 44)
Row 3242 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 13, 56, 51), 'Surgical Ward', 24, 61)
Row 3243 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 13, 56, 59), 'Emergency Ward', 26, 60)
Row 3244 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 13, 57), 'Maternity Ward', 23, 62)
Row 3245 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 13, 57, 59), 'ICU', 28, 45)
Row 3246 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 13, 58, 5), 'Surgical Ward', 24, 61)
Row 3247 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 13, 58, 19), 'Maternity Ward', 23, 62)
Row 3248 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 13, 58, 21), 'Emergency Ward', 27, 59)
Row 3249 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 13, 59, 6), 'ICU', 24, 44)
Row 3250 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 13, 59, 14), 'Surgical Ward', 24, 61)
Row 3251 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 13, 59, 33), 'Emergency Ward', 26, 60)
Row 3252 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 13, 59, 39), 'Maternity Ward', 23, 61)
Row 3253 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 14, 0, 25), 'ICU', 27, 45)
Row 3254 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 14, 0, 34), 'Surgical Ward', 24, 61)
Row 3255 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 14, 0, 43), 'Emergency Ward', 27, 59)
Row 3256 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 14, 1), 'Maternity Ward', 23, 62)
Row 3257 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 14, 1, 44), 'ICU', 27, 45)
Row 3258 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 14, 1, 56), 'Surgical Ward', 24, 61)
Row 3259 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 14, 2, 5), 'Emergency Ward', 27, 59)
Row 3260 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 14, 2, 15), 'Maternity Ward', 23, 62)
Row 3261 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 14, 3, 4), 'ICU', 27, 45)
Row 3262 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 14, 3, 15), 'Surgical Ward', 24, 61)
Row 3263 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 14, 3, 22), 'Maternity Ward', 23, 62)
Row 3264 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 14, 3, 25), 'Emergency Ward', 27, 59)
Row 3265 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 14, 4, 23), 'ICU', 28, 45)
Row 3266 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 14, 4, 36), 'Surgical Ward', 24, 61)
Row 3267 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 14, 4, 43), 'Maternity Ward', 24, 62)
Row 3268 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 14, 4, 46), 'Emergency Ward', 27, 59)
Row 3269 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 14, 5, 42), 'ICU', 24, 44)
Row 3270 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 14, 5, 56), 'Surgical Ward', 24, 60)
Row 3271 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 14, 6, 3), 'Maternity Ward', 23, 62)
Row 3272 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 14, 6, 9), 'Emergency Ward', 27, 59)
Row 3273 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 14, 7, 1), 'ICU', 28, 44)
Row 3274 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 14, 7, 17), 'Surgical Ward', 24, 61)
Row 3275 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 14, 7, 23), 'Maternity Ward', 23, 61)

Row 3276 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 14, 7, 29), 'Emergency Ward', 27, 59)
Row 3277 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 14, 8, 20), 'ICU', 27, 44)
Row 3278 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 14, 8, 38), 'Surgical Ward', 24, 61)
Row 3279 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 14, 8, 44), 'Maternity Ward', 23, 62)
Row 3280 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 14, 8, 50), 'Emergency Ward', 27, 59)
Row 3281 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 14, 9, 39), 'ICU', 27, 44)
Row 3282 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 14, 9, 59), 'Surgical Ward', 24, 61)
Row 3283 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 14, 10, 4), 'Maternity Ward', 23, 61)
Row 3284 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 14, 10, 11), 'Emergency Ward', 27, 59)
Row 3285 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 14, 10, 59), 'ICU', 24, 43)
Row 3286 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 14, 11, 19), 'Surgical Ward', 24, 61)
Row 3287 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 14, 11, 25), 'Maternity Ward', 23, 61)
Row 3288 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 14, 11, 32), 'Emergency Ward', 27, 59)
Row 3289 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 14, 12, 10), 'ICU', 24, 43)
Row 3290 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 14, 12, 31), 'Surgical Ward', 24, 61)
Row 3291 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 14, 12, 45), 'Maternity Ward', 23, 61)
Row 3292 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 14, 12, 54), 'Emergency Ward', 27, 59)
Row 3293 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 14, 13, 19), 'ICU', 28, 43)
Row 3294 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 14, 13, 40), 'Surgical Ward', 24, 60)
Row 3295 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 14, 14, 5), 'Maternity Ward', 23, 61)
Row 3296 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 14, 14, 10), 'Emergency Ward', 27, 59)
Row 3297 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 14, 14, 38), 'ICU', 24, 43)
Row 3298 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 14, 15, 1), 'Surgical Ward', 24, 60)
Row 3299 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 14, 15, 19), 'Emergency Ward', 27, 59)
Row 3300 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 14, 15, 26), 'Maternity Ward', 23, 61)
Row 3301 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 14, 15, 56), 'ICU', 27, 43)
Row 3302 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 14, 16, 21), 'Surgical Ward', 24, 60)
Row 3303 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 14, 16, 39), 'Emergency Ward', 27, 59)
Row 3304 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 14, 16, 40), 'Maternity Ward', 23, 61)
Row 3305 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 14, 17, 15), 'ICU', 27, 43)
Row 3306 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 14, 17, 42), 'Surgical Ward', 24, 60)
Row 3307 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 14, 17, 49), 'Maternity Ward', 23, 61)
Row 3308 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 14, 18), 'Emergency Ward', 27, 58)
Row 3309 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 14, 18, 35), 'ICU', 27, 42)
Row 3310 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 14, 19, 2), 'Surgical Ward', 24, 59)
Row 3311 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 14, 19, 9), 'Maternity Ward', 23, 60)
Row 3312 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 14, 19, 21), 'Emergency Ward', 27, 58)
Row 3313 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 14, 19, 54), 'ICU', 27, 42)
Row 3314 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 14, 20, 23), 'Surgical Ward', 24, 58)
Row 3315 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 14, 20, 29), 'Maternity Ward', 23, 60)
Row 3316 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 14, 20, 42), 'Emergency Ward', 27, 59)
Row 3317 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 14, 21, 13), 'ICU', 27, 42)
Row 3318 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 14, 21, 43), 'Surgical Ward', 24, 57)
Row 3319 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 14, 21, 49), 'Maternity Ward', 23, 59)
Row 3320 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 14, 22, 3), 'Emergency Ward', 27, 58)
Row 3321 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 14, 22, 32), 'ICU', 27, 42)
Row 3322 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 14, 23, 4), 'Surgical Ward', 24, 57)
Row 3323 is Updated!!!

INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 14, 23, 10), 'Maternity Ward', 23, 59)
Row 3324 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 14, 23, 24), 'Emergency Ward', 27, 58)
Row 3325 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 14, 23, 52), 'ICU', 24, 41)
Row 3326 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 14, 24, 24), 'Surgical Ward', 24, 57)
Row 3327 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 14, 24, 30), 'Maternity Ward', 23, 60)
Row 3328 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 14, 24, 46), 'Emergency Ward', 27, 58)
Row 3329 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 14, 25, 10), 'ICU', 27, 42)
Row 3330 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 14, 25, 48), 'Surgical Ward', 24, 57)
Row 3331 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 14, 25, 52), 'Maternity Ward', 23, 59)
Row 3332 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 14, 26, 7), 'Emergency Ward', 27, 58)
Row 3333 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 14, 26, 22), 'ICU', 28, 42)
Row 3334 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 14, 26, 59), 'Surgical Ward', 24, 57)
Row 3335 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 14, 27, 11), 'Maternity Ward', 23, 60)
Row 3336 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 14, 27, 29), 'Emergency Ward', 27, 58)
Row 3337 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 14, 27, 30), 'ICU', 27, 43)
Row 3338 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 14, 28, 8), 'Surgical Ward', 24, 57)
Row 3339 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 14, 28, 43), 'Emergency Ward', 27, 58)
Row 3340 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 14, 28, 50), 'ICU', 27, 43)
Row 3341 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 14, 29, 29), 'Surgical Ward', 24, 57)
Row 3342 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 14, 29, 53), 'Maternity Ward', 23, 61)
Row 3343 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 14, 30, 11), 'ICU', 28, 43)
Row 3344 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 14, 30, 50), 'Surgical Ward', 24, 58)
Row 3345 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 14, 31, 6), 'Maternity Ward', 23, 61)
Row 3346 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 14, 31, 13), 'Emergency Ward', 27, 58)
Row 3347 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 14, 31, 28), 'ICU', 24, 42)
Row 3348 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 14, 32, 9), 'Surgical Ward', 24, 58)
Row 3349 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 14, 32, 15), 'Maternity Ward', 23, 61)
Row 3350 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 14, 32, 34), 'Emergency Ward', 27, 58)
Row 3351 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 14, 32, 46), 'ICU', 24, 42)
Row 3352 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 14, 33, 29), 'Surgical Ward', 24, 58)
Row 3353 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 14, 33, 35), 'Maternity Ward', 23, 61)
Row 3354 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 14, 33, 55), 'Emergency Ward', 27, 58)
Row 3355 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 14, 34, 6), 'ICU', 28, 43)
Row 3356 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 14, 34, 49), 'Surgical Ward', 24, 59)
Row 3357 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 14, 34, 55), 'Maternity Ward', 23, 61)
Row 3358 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 14, 35, 17), 'Emergency Ward', 27, 58)
Row 3359 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 14, 35, 25), 'ICU', 24, 43)
Row 3360 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 14, 36, 10), 'Surgical Ward', 24, 59)
Row 3361 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 14, 36, 15), 'Maternity Ward', 23, 61)
Row 3362 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 14, 36, 39), 'Emergency Ward', 27, 59)
Row 3363 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 14, 36, 44), 'ICU', 28, 44)
Row 3364 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 14, 37, 30), 'Surgical Ward', 24, 59)
Row 3365 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 14, 37, 36), 'Maternity Ward', 23, 61)
Row 3366 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 14, 37, 59), 'Emergency Ward', 27, 59)
Row 3367 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 14, 38, 3), 'ICU', 28, 44)
Row 3368 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 14, 38, 51), 'Surgical Ward', 24, 59)

Row 3369 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 14, 38, 56), 'Maternity Ward', 23, 61)
Row 3370 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 14, 39, 20), 'Emergency Ward', 27, 59)
Row 3371 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 14, 39, 22), 'ICU', 24, 43)
Row 3372 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 14, 40, 11), 'Surgical Ward', 24, 59)
Row 3373 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 14, 40, 17), 'Maternity Ward', 23, 61)
Row 3374 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 14, 40, 41), 'Emergency Ward', 27, 59)
Row 3375 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 14, 41, 25), 'Surgical Ward', 24, 60)
Row 3376 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 14, 41, 38), 'Maternity Ward', 23, 61)
Row 3377 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 14, 41, 42), 'ICU', 28, 44)
Row 3378 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 14, 42, 2), 'Emergency Ward', 27, 59)
Row 3379 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 14, 42, 59), 'Maternity Ward', 23, 61)
Row 3380 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 14, 43, 1), 'ICU', 28, 44)
Row 3381 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 14, 43, 17), 'Emergency Ward', 27, 59)
Row 3382 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 14, 43, 54), 'Surgical Ward', 24, 60)
Row 3383 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 14, 44, 19), 'Maternity Ward', 23, 61)
Row 3384 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 14, 44, 21), 'ICU', 24, 44)
Row 3385 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 14, 44, 26), 'Emergency Ward', 27, 59)
Row 3386 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 14, 45, 15), 'Surgical Ward', 24, 60)
Row 3387 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 14, 45, 31), 'Maternity Ward', 23, 61)
Row 3388 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 14, 45, 39), 'ICU', 24, 44)
Row 3389 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 14, 45, 49), 'Emergency Ward', 27, 59)
Row 3390 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 14, 46, 35), 'Surgical Ward', 24, 60)
Row 3391 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 14, 46, 40), 'Maternity Ward', 23, 61)
Row 3392 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 14, 46, 59), 'ICU', 24, 44)
Row 3393 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 14, 47, 9), 'Emergency Ward', 27, 59)
Row 3394 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 14, 47, 56), 'Surgical Ward', 24, 60)
Row 3395 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 14, 48, 1), 'Maternity Ward', 23, 61)
Row 3396 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 14, 48, 19), 'ICU', 28, 44)
Row 3397 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 14, 48, 30), 'Emergency Ward', 27, 59)
Row 3398 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 14, 49, 16), 'Surgical Ward', 24, 60)
Row 3399 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 14, 49, 21), 'Maternity Ward', 23, 61)
Row 3400 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 14, 49, 36), 'ICU', 24, 44)
Row 3401 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 14, 49, 51), 'Emergency Ward', 28, 59)
Row 3402 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 14, 50, 37), 'Surgical Ward', 24, 60)
Row 3403 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 14, 50, 42), 'Maternity Ward', 23, 61)
Row 3404 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 14, 50, 56), 'ICU', 24, 44)
Row 3405 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 14, 51, 12), 'Emergency Ward', 27, 59)
Row 3406 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 14, 51, 57), 'Surgical Ward', 24, 60)
Row 3407 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 14, 52, 2), 'Maternity Ward', 23, 61)
Row 3408 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 14, 52, 15), 'ICU', 24, 44)
Row 3409 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 14, 52, 33), 'Emergency Ward', 27, 59)
Row 3410 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 14, 53, 19), 'Surgical Ward', 24, 60)
Row 3411 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 14, 53, 22), 'Maternity Ward', 23, 61)
Row 3412 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 14, 53, 34), 'ICU', 28, 44)
Row 3413 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 14, 53, 54), 'Emergency Ward', 28, 59)
Row 3414 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 14, 54, 40), 'Surgical Ward', 24, 60)
Row 3415 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 14, 54, 45), 'Maternity Ward', 23, 61)
Row 3416 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 14, 54, 46), 'ICU', 24, 44)

Row 3417 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 14, 55, 16), 'Emergency Ward', 27, 59)
Row 3418 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 14, 55, 51), 'Surgical Ward', 24, 60)
Row 3419 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 14, 55, 54), 'ICU', 24, 44)
Row 3420 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 14, 57), 'Surgical Ward', 24, 61)
Row 3421 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 14, 57, 13), 'ICU', 28, 44)
Row 3422 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 14, 57, 23), 'Maternity Ward', 23, 61)
Row 3423 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 14, 57, 53), 'Emergency Ward', 28, 59)
Row 3424 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 14, 58, 21), 'Surgical Ward', 24, 61)
Row 3425 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 14, 58, 33), 'ICU', 28, 45)
Row 3426 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 14, 58, 44), 'Maternity Ward', 23, 62)
Row 3427 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 14, 59, 2), 'Emergency Ward', 27, 59)
Row 3428 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 14, 59, 43), 'Surgical Ward', 24, 61)
Row 3429 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 14, 59, 51), 'ICU', 24, 44)
Row 3430 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 15, 0), 'Maternity Ward', 24, 61)
Row 3431 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 15, 0, 22), 'Emergency Ward', 28, 59)
Row 3432 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 15, 1, 2), 'Surgical Ward', 24, 61)
Row 3433 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 15, 1, 6), 'Maternity Ward', 24, 61)
Row 3434 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 15, 1, 11), 'ICU', 28, 45)
Row 3435 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 15, 1, 43), 'Emergency Ward', 28, 59)
Row 3436 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 15, 2, 22), 'Surgical Ward', 24, 61)
Row 3437 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 15, 2, 27), 'Maternity Ward', 24, 62)
Row 3438 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 15, 2, 29), 'ICU', 24, 44)
Row 3439 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 15, 3, 4), 'Emergency Ward', 27, 59)
Row 3440 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 15, 3, 43), 'Surgical Ward', 24, 61)
Row 3441 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 15, 3, 48), 'Maternity Ward', 24, 62)
Row 3442 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 15, 3, 50), 'ICU', 24, 44)
Row 3443 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 15, 4, 26), 'Emergency Ward', 27, 59)
Row 3444 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 15, 5, 4), 'Surgical Ward', 24, 61)
Row 3445 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 15, 5, 9), 'Maternity Ward', 23, 62)
Row 3446 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 15, 5, 50), 'Emergency Ward', 28, 59)
Row 3447 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 15, 6, 28), 'Surgical Ward', 24, 61)
Row 3448 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 15, 6, 30), 'ICU', 28, 45)
Row 3449 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 15, 6, 32), 'Maternity Ward', 24, 62)
Row 3450 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 15, 7, 10), 'Emergency Ward', 28, 59)
Row 3451 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 15, 7, 45), 'Surgical Ward', 24, 61)
Row 3452 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 15, 7, 49), 'ICU', 28, 45)
Row 3453 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 15, 7, 52), 'Maternity Ward', 24, 62)
Row 3454 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 15, 8, 29), 'Emergency Ward', 28, 59)
Row 3455 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 15, 9), 'ICU', 24, 44)
Row 3456 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 15, 9, 6), 'Surgical Ward', 24, 61)
Row 3457 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 15, 9, 10), 'Maternity Ward', 24, 62)
Row 3458 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 15, 9, 50), 'Emergency Ward', 28, 59)
Row 3459 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 15, 10, 6), 'ICU', 28, 45)
Row 3460 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 15, 10, 20), 'Surgical Ward', 24, 61)
Row 3461 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 15, 10, 29), 'Maternity Ward', 24, 62)
Row 3462 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 15, 11, 12), 'Emergency Ward', 28, 59)
Row 3463 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 15, 11, 25), 'ICU', 28, 45)
Row 3464 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 15, 11, 27), 'Surgical Ward', 24, 61)

Row 3465 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 15, 11, 50), 'Maternity Ward', 23, 62)
Row 3466 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 15, 12, 25), 'Emergency Ward', 28, 59)
Row 3467 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 15, 12, 45), 'ICU', 24, 45)
Row 3468 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 15, 12, 49), 'Surgical Ward', 24, 61)
Row 3469 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 15, 13, 10), 'Maternity Ward', 23, 62)
Row 3470 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 15, 13, 35), 'Emergency Ward', 28, 59)
Row 3471 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 15, 14, 3), 'ICU', 28, 46)
Row 3472 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 15, 14, 9), 'Surgical Ward', 24, 61)
Row 3473 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 15, 14, 24), 'Maternity Ward', 24, 62)
Row 3474 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 15, 14, 57), 'Emergency Ward', 28, 59)
Row 3475 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 15, 15, 23), 'ICU', 28, 46)
Row 3476 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 15, 15, 29), 'Surgical Ward', 24, 61)
Row 3477 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 15, 15, 33), 'Maternity Ward', 24, 62)
Row 3478 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 15, 16, 20), 'Emergency Ward', 28, 59)
Row 3479 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 15, 16, 44), 'ICU', 28, 46)
Row 3480 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 15, 16, 49), 'Surgical Ward', 24, 61)
Row 3481 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 15, 16, 55), 'Maternity Ward', 24, 62)
Row 3482 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 15, 17, 40), 'Emergency Ward', 28, 59)
Row 3483 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 15, 18, 1), 'ICU', 24, 45)
Row 3484 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 15, 18, 10), 'Surgical Ward', 24, 61)
Row 3485 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 15, 18, 13), 'Maternity Ward', 24, 62)
Row 3486 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 15, 19), 'Emergency Ward', 28, 59)
Row 3487 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 15, 19, 20), 'ICU', 28, 46)
Row 3488 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 15, 19, 30), 'Surgical Ward', 24, 61)
Row 3489 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 15, 19, 33), 'Maternity Ward', 24, 62)
Row 3490 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 15, 20, 21), 'Emergency Ward', 28, 59)
Row 3491 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 15, 20, 39), 'ICU', 28, 46)
Row 3492 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 15, 20, 50), 'Surgical Ward', 24, 61)
Row 3493 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 15, 20, 54), 'Maternity Ward', 24, 63)
Row 3494 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 15, 21, 42), 'Emergency Ward', 28, 59)
Row 3495 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 15, 21, 59), 'ICU', 28, 46)
Row 3496 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 15, 22, 11), 'Surgical Ward', 24, 61)
Row 3497 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 15, 22, 14), 'Maternity Ward', 24, 62)
Row 3498 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 15, 23, 4), 'Emergency Ward', 28, 59)
Row 3499 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 15, 23, 10), 'ICU', 24, 45)
Row 3500 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 15, 23, 31), 'Surgical Ward', 24, 61)
Row 3501 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 15, 23, 35), 'Maternity Ward', 23, 63)
Row 3502 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 15, 24, 19), 'ICU', 28, 46)
Row 3503 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 15, 24, 24), 'Emergency Ward', 28, 59)
Row 3504 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 15, 24, 45), 'Surgical Ward', 24, 61)
Row 3505 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 15, 24, 55), 'Maternity Ward', 24, 63)
Row 3506 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 15, 25, 37), 'ICU', 28, 46)
Row 3507 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 15, 25, 46), 'Emergency Ward', 28, 59)
Row 3508 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 15, 25, 55), 'Surgical Ward', 24, 61)
Row 3509 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 15, 26, 16), 'Maternity Ward', 24, 63)
Row 3510 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 15, 26, 56), 'ICU', 28, 46)

Row 3511 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 15, 27), 'Emergency Ward', 28, 59)
Row 3512 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 15, 27, 14), 'Surgical Ward', 24, 61)
Row 3513 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 15, 27, 36), 'Maternity Ward', 24, 62)
Row 3514 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 15, 28, 9), 'Emergency Ward', 28, 59)
Row 3515 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 15, 28, 15), 'ICU', 24, 45)
Row 3516 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 15, 28, 35), 'Surgical Ward', 24, 61)
Row 3517 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 15, 28, 50), 'Maternity Ward', 24, 63)
Row 3518 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 15, 29, 31), 'Emergency Ward', 28, 59)
Row 3519 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 15, 29, 34), 'ICU', 28, 46)
Row 3520 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 15, 29, 55), 'Surgical Ward', 24, 61)
Row 3521 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 15, 29, 59), 'Maternity Ward', 24, 62)
Row 3522 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 15, 30, 52), 'Emergency Ward', 28, 59)
Row 3523 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 15, 30, 53), 'ICU', 28, 46)
Row 3524 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 15, 31, 16), 'Surgical Ward', 24, 61)
Row 3525 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 15, 31, 19), 'Maternity Ward', 24, 62)
Row 3526 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 15, 32, 12), 'ICU', 24, 45)
Row 3527 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 15, 32, 13), 'Emergency Ward', 28, 59)
Row 3528 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 15, 32, 39), 'Maternity Ward', 24, 62)
Row 3529 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 15, 33, 32), 'ICU', 28, 46)
Row 3530 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 15, 33, 34), 'Emergency Ward', 28, 59)
Row 3531 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 15, 33, 57), 'Surgical Ward', 24, 61)
Row 3532 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 15, 34), 'Maternity Ward', 24, 62)
Row 3533 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 15, 34, 51), 'ICU', 24, 45)
Row 3534 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 15, 34, 55), 'Emergency Ward', 28, 59)
Row 3535 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 15, 35, 17), 'Surgical Ward', 24, 61)
Row 3536 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 15, 35, 20), 'Maternity Ward', 24, 62)
Row 3537 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 15, 36, 10), 'ICU', 24, 45)
Row 3538 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 15, 36, 16), 'Emergency Ward', 28, 59)
Row 3539 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 15, 36, 39), 'Surgical Ward', 24, 61)
Row 3540 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 15, 36, 40), 'Maternity Ward', 24, 62)
Row 3541 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 15, 37, 23), 'ICU', 28, 46)
Row 3542 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 15, 37, 39), 'Emergency Ward', 28, 59)
Row 3543 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 15, 37, 59), 'Surgical Ward', 24, 61)
Row 3544 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 15, 38, 1), 'Maternity Ward', 24, 62)
Row 3545 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 15, 38, 31), 'ICU', 28, 46)
Row 3546 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 15, 38, 59), 'Emergency Ward', 28, 59)
Row 3547 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 15, 39, 11), 'Surgical Ward', 25, 60)
Row 3548 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 15, 39, 21), 'Maternity Ward', 24, 62)
Row 3549 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 15, 39, 49), 'ICU', 28, 46)
Row 3550 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 15, 40, 20), 'Emergency Ward', 28, 59)
Row 3551 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 15, 40, 21), 'Surgical Ward', 25, 60)
Row 3552 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 15, 40, 42), 'Maternity Ward', 24, 62)
Row 3553 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 15, 41, 9), 'ICU', 28, 46)
Row 3554 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 15, 41, 34), 'Emergency Ward', 28, 59)
Row 3555 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 15, 41, 41), 'Surgical Ward', 24, 61)
Row 3556 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 15, 42, 2), 'Maternity Ward', 24, 62)
Row 3557 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 15, 42, 27), 'ICU', 24, 45)

Row 3558 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 15, 42, 44), 'Emergency Ward', 28, 59)
Row 3559 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 15, 43, 1), 'Surgical Ward', 24, 61)
Row 3560 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 15, 43, 16), 'Maternity Ward', 23, 62)
Row 3561 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 15, 43, 46), 'ICU', 28, 46)
Row 3562 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 15, 44, 5), 'Emergency Ward', 28, 59)
Row 3563 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 15, 44, 22), 'Surgical Ward', 24, 61)
Row 3564 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 15, 44, 24), 'Maternity Ward', 24, 62)
Row 3565 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 15, 45, 5), 'ICU', 28, 46)
Row 3566 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 15, 45, 26), 'Emergency Ward', 28, 59)
Row 3567 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 15, 45, 42), 'Surgical Ward', 25, 60)
Row 3568 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 15, 45, 45), 'Maternity Ward', 23, 62)
Row 3569 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 15, 46, 24), 'ICU', 25, 44)
Row 3570 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 15, 46, 47), 'Emergency Ward', 28, 59)
Row 3571 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 15, 47, 3), 'Surgical Ward', 24, 61)
Row 3572 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 15, 47, 5), 'Maternity Ward', 23, 62)
Row 3573 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 15, 47, 44), 'ICU', 24, 45)
Row 3574 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 15, 48, 10), 'Emergency Ward', 28, 59)
Row 3575 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 15, 48, 23), 'Surgical Ward', 24, 61)
Row 3576 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 15, 48, 26), 'Maternity Ward', 24, 62)
Row 3577 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 15, 49, 3), 'ICU', 28, 46)
Row 3578 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 15, 49, 29), 'Emergency Ward', 28, 59)
Row 3579 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 15, 49, 44), 'Surgical Ward', 24, 61)
Row 3580 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 15, 49, 46), 'Maternity Ward', 24, 62)
Row 3581 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 15, 50, 22), 'ICU', 28, 46)
Row 3582 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 15, 50, 51), 'Emergency Ward', 28, 59)
Row 3583 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 15, 51, 4), 'Surgical Ward', 24, 61)
Row 3584 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 15, 51, 7), 'Maternity Ward', 25, 61)
Row 3585 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 15, 51, 34), 'ICU', 24, 45)
Row 3586 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 15, 52, 12), 'Emergency Ward', 28, 59)
Row 3587 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 15, 52, 25), 'Surgical Ward', 24, 61)
Row 3588 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 15, 52, 27), 'Maternity Ward', 24, 62)
Row 3589 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 15, 52, 42), 'ICU', 28, 46)
Row 3590 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 15, 53, 33), 'Emergency Ward', 28, 59)
Row 3591 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 15, 53, 39), 'Surgical Ward', 24, 61)
Row 3592 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 15, 53, 47), 'Maternity Ward', 24, 62)
Row 3593 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 15, 54, 1), 'ICU', 28, 45)
Row 3594 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 15, 54, 47), 'Surgical Ward', 24, 61)
Row 3595 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 15, 54, 54), 'Emergency Ward', 28, 59)
Row 3596 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 15, 55, 9), 'Maternity Ward', 24, 62)
Row 3597 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 15, 55, 20), 'ICU', 28, 45)
Row 3598 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 15, 56, 9), 'Surgical Ward', 24, 61)
Row 3599 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 15, 56, 10), 'Emergency Ward', 28, 59)
Row 3600 is Updated!!!
INSERT INTO hospital_A (Timestamp, Room, Temperature, Humidity) VALUES (%s, %s, %s, %s) (datetime.datetime(2018, 10, 13, 15, 56, 29), 'Maternity Ward', 24, 61)
Row 3601 is Updated!!!

In [13]:
aws_cursor.close()
gear_cursor.close()

True